// frontend/src/pages/UEBAOverview.svelte
<!--
  UEBA Overview — anomaly + profile feed from UEBAService.
-->
<script lang="ts">
  import { onMount } from 'svelte';
  import { PageLayout, Badge, Button, KPI, DataTable, PopOutButton } from '@components/ui';
  import { Users, AlertTriangle, RefreshCw, TrendingUp } from 'lucide-svelte';
  import { IS_BROWSER } from '@lib/context';
  import { push } from '@lib/router.svelte';
  import { appStore } from '@lib/stores/app.svelte';

  type Anomaly = {
    id?: string; user_id?: string; entity?: string; score?: number;
    description?: string; severity?: string; detected_at?: string;
  };
  type Profile = {
    user_id?: string; baseline?: any; risk_score?: number; last_seen?: string;
  };

  let anomalies = $state<Anomaly[]>([]);
  let profiles = $state<Profile[]>([]);
  let loading = $state(false);

  const stats = $derived.by(() => ({
    anomalies: anomalies.length,
    high: anomalies.filter((a) => (a.severity ?? '').toLowerCase() === 'high' || (a.score ?? 0) >= 0.8).length,
    profiles: profiles.length,
    avgRisk: profiles.length === 0 ? 0
      : Math.round(profiles.reduce((s, p) => s + (p.risk_score ?? 0), 0) / profiles.length * 100),
  }));

  async function refresh() {
    loading = true;
    try {
      if (IS_BROWSER) { anomalies = []; profiles = []; return; }
      const ueba = await import(
        '@wailsjs/github.com/kingknull/oblivrashell/internal/services/uebaservice'
      );
      const [an, pr] = await Promise.all([ueba.GetAnomalies(), ueba.GetProfiles()]);
      anomalies = (an ?? []) as Anomaly[];
      profiles = (pr ?? []) as Profile[];
    } catch (e: any) {
      appStore.notify(`UEBA load failed: ${e?.message ?? e}`, 'error');
    } finally { loading = false; }
  }

  onMount(refresh);
</script>

<PageLayout title="User & Entity Behaviour Analytics" subtitle="Detected anomalies and risky-user profiles">
  {#snippet toolbar()}
    <Button variant="secondary" size="sm" icon={RefreshCw} onclick={refresh}>{loading ? 'Loading…' : 'Refresh'}</Button>
    <PopOutButton route="/ueba" title="UEBA Overview" />
  {/snippet}

  <div class="flex flex-col h-full gap-4">
    <div class="grid grid-cols-1 md:grid-cols-4 gap-3 shrink-0">
      <KPI label="Live Anomalies"   value={stats.anomalies.toString()} variant={stats.anomalies > 0 ? 'critical' : 'muted'} />
      <KPI label="High Severity"    value={stats.high.toString()}      variant={stats.high > 0 ? 'critical' : 'muted'} />
      <KPI label="Profiled Users"   value={stats.profiles.toString()}  variant="accent" />
      <KPI label="Avg Risk Score"   value={`${stats.avgRisk}%`}        variant={stats.avgRisk >= 60 ? 'warning' : 'muted'} />
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4 flex-1 min-h-0">
      <section class="lg:col-span-2 flex flex-col bg-surface-1 border border-border-primary rounded-md min-h-0">
        <div class="flex items-center gap-2 p-3 border-b border-border-primary">
          <AlertTriangle size={14} class="text-warning" />
          <span class="text-[10px] uppercase tracking-widest font-bold">Recent Anomalies</span>
          <span class="ml-auto text-[10px] text-text-muted">{anomalies.length}</span>
        </div>
        <div class="flex-1 overflow-auto">
          {#if anomalies.length === 0}
            <div class="p-6 text-sm text-text-muted text-center">{loading ? 'Loading…' : 'No anomalies detected.'}</div>
          {:else}
            <DataTable
              data={anomalies}
              columns={[
                { key: 'severity',    label: 'Sev',    width: '70px' },
                { key: 'entity',      label: 'Entity', width: '140px' },
                { key: 'description', label: 'Anomaly' },
                { key: 'score',       label: 'Score',  width: '70px' },
                { key: 'detected_at', label: 'Time',   width: '140px' },
              ]}
              compact
            >
              {#snippet render({ col, row })}
                {#if col.key === 'severity'}
                  <Badge variant={(row.severity ?? '').toLowerCase() === 'high' ? 'critical' : (row.severity ?? '').toLowerCase() === 'medium' ? 'warning' : 'info'} size="xs">
                    {row.severity ?? '—'}
                  </Badge>
                {:else if col.key === 'entity'}
                  <span class="font-mono text-[10px] text-accent">{row.entity ?? row.user_id ?? '—'}</span>
                {:else if col.key === 'score'}
                  <span class="font-mono text-[10px] {(row.score ?? 0) >= 0.8 ? 'text-error' : (row.score ?? 0) >= 0.5 ? 'text-warning' : 'text-text-muted'}">{row.score?.toFixed(2) ?? '—'}</span>
                {:else if col.key === 'detected_at'}
                  <span class="font-mono text-[10px] text-text-muted">{row.detected_at?.slice(0, 19) ?? '—'}</span>
                {:else}
                  <span class="text-[11px]">{row[col.key] ?? '—'}</span>
                {/if}
              {/snippet}
            </DataTable>
          {/if}
        </div>
      </section>

      <section class="flex flex-col bg-surface-1 border border-border-primary rounded-md min-h-0">
        <div class="flex items-center gap-2 p-3 border-b border-border-primary">
          <TrendingUp size={14} class="text-accent" />
          <span class="text-[10px] uppercase tracking-widest font-bold">Top Risk Users</span>
        </div>
        <div class="flex-1 overflow-auto p-2">
          {#if profiles.length === 0}
            <div class="p-4 text-sm text-text-muted text-center">{loading ? 'Loading…' : 'No profiles yet.'}</div>
          {:else}
            {#each profiles.slice().sort((a, b) => (b.risk_score ?? 0) - (a.risk_score ?? 0)).slice(0, 20) as p (p.user_id)}
              <button
                class="w-full text-left px-2 py-1.5 rounded-md hover:bg-surface-2 flex items-center gap-2"
                onclick={() => push(`/ueba-overview?user=${encodeURIComponent(p.user_id ?? '')}`)}
              >
                <Users size={11} class="text-text-muted" />
                <span class="font-mono text-[11px] flex-1 truncate">{p.user_id ?? '—'}</span>
                <span class="font-mono text-[10px] {(p.risk_score ?? 0) >= 0.8 ? 'text-error' : (p.risk_score ?? 0) >= 0.5 ? 'text-warning' : 'text-text-muted'}">
                  {Math.round((p.risk_score ?? 0) * 100)}
                </span>
              </button>
            {/each}
          {/if}
        </div>
      </section>
    </div>
  </div>
</PageLayout>

// frontend/src/components/analytics/UEBAOverview.tsx
// UEBAOverview.tsx — Phase 10 Web: entity analytics and risk visualization
import { Component, createSignal, onMount, For, Show, createMemo } from 'solid-js';
import { IS_BROWSER } from '@core/context';
import { 
    PageLayout, 
    Panel, 
    Badge, 
    KPI, 
    KPIGrid,
    Input,
    Button,
    EmptyState,
    LoadingScreen
} from '@components/ui';
import '../../styles/ueba-overview.css';

export const UEBAOverview: Component = () => {
    const [profiles, setProfiles] = createSignal<any[]>([]);
    const [loading, setLoading] = createSignal(true);
    const [selected, setSelected] = createSignal<any>(null);
    const [sortBy, setSortBy] = createSignal<'risk' | 'entity'>('risk');
    const [filter, setFilter] = createSignal('');

    const fetchData = async () => {
        setLoading(true);
        if (IS_BROWSER) { setLoading(false); return; }
        try {
            const { GetProfiles } = await import('../../../wailsjs/go/services/UEBAService');
            const data = await (GetProfiles as any)() ?? [];
            setProfiles(data);
        } catch (err) {
            console.error('Failed to fetch UEBA profiles:', err);
            setProfiles([]);
        } finally {
            setLoading(false);
        }
    };

    onMount(() => fetchData());

    const sorted = createMemo(() => {
        let list = profiles().filter(p =>
            !filter() || p.entity_id?.toLowerCase().includes(filter().toLowerCase())
        );
        if (sortBy() === 'risk') {
            list = [...list].sort((a, b) => (b.risk_score ?? 0) - (a.risk_score ?? 0));
        } else {
            list = [...list].sort((a, b) => (a.entity_id ?? '').localeCompare(b.entity_id ?? ''));
        }
        return list;
    });

    const getRiskSeverity = (score: number) => {
        if (score > 75) return 'critical';
        if (score > 45) return 'high';
        if (score > 20) return 'medium';
        return 'low';
    };

    const getRiskColor = (score: number) => {
        if (score > 75) return 'var(--alert-critical)';
        if (score > 45) return 'var(--alert-high)';
        if (score > 20) return 'var(--alert-medium)';
        return 'var(--alert-low)';
    };

    const avgRisk = createMemo(() => {
        const p = profiles();
        if (!p.length) return 0;
        return p.reduce((acc, x) => acc + (x.risk_score ?? 0), 0) / p.length;
    });

    const criticalCount = createMemo(() => profiles().filter(p => (p.risk_score ?? 0) > 75).length);

    return (
        <PageLayout 
            title="User & Entity Behavior Analytics" 
            subtitle="BEHAVIORAL_BASELINE_DETECTION"
            actions={
                <div style="display: flex; gap: 8px;">
                    <Button variant="ghost" size="sm" onClick={fetchData}>REFRESH_PROFILES</Button>
                </div>
            }
        >
            <div class="ueba-container">
                <KPIGrid cols={3}>
                    <KPI 
                        label="TOTAL_ENTITIES" 
                        value={profiles().length} 
                    />
                    <KPI 
                        label="CRITICAL_RISK" 
                        value={criticalCount()} 
                        color="var(--alert-critical)" 
                    />
                    <KPI 
                        label="AVERAGE_RISK_SCORE" 
                        value={avgRisk().toFixed(1)} 
                        color={getRiskColor(avgRisk())} 
                    />
                </KPIGrid>

                <div class="ueba-controls">
                    <Input 
                        placeholder="Filter by entity ID..." 
                        value={filter()} 
                        onInput={setFilter}
                        style="width: 260px;"
                    />
                    <Button 
                        variant={sortBy() === 'risk' ? 'blue' : 'ghost'} 
                        size="sm" 
                        onClick={() => setSortBy('risk')}
                    >
                        SORT_BY_RISK
                    </Button>
                    <Button 
                        variant={sortBy() === 'entity' ? 'blue' : 'ghost'} 
                        size="sm" 
                        onClick={() => setSortBy('entity')}
                    >
                        SORT_BY_ENTITY
                    </Button>
                </div>

                <Show when={loading()}>
                    <div style="flex: 1; min-height: 200px; display: flex; align-items: center; justify-content: center;">
                        <LoadingScreen message="ANALYZING_BEHAVIORAL_PROFILES..." />
                    </div>
                </Show>

                <Show when={!loading() && sorted().length === 0}>
                    <EmptyState
                        icon="🧠"
                        title="NO_BEHAVIORAL_PROFILES"
                        description="Profiles are built automatically as agents report activity. Baselines typically require 24-48 hours of telemetry."
                    />
                </Show>

                <Show when={!loading() && sorted().length > 0}>
                    <div class="ueba-grid">
                        <For each={sorted()}>
                            {(profile) => {
                                const score = profile.risk_score ?? 0;
                                const severity = getRiskSeverity(score);
                                const color = getRiskColor(score);
                                const isSelected = () => selected()?.entity_id === profile.entity_id;

                                return (
                                    <div
                                        class="ueba-card"
                                        classList={{ selected: isSelected() }}
                                        style={{ "border-left-color": color }}
                                        onClick={() => setSelected(isSelected() ? null : profile)}
                                    >
                                        <div class="ueba-card-header">
                                            <div>
                                                <div class="ueba-entity-id">{profile.entity_id ?? '—'}</div>
                                                <div class="ueba-entity-type">{profile.entity_type ?? 'user'}</div>
                                            </div>
                                            <div class="ueba-risk-score">
                                                <div class="ueba-score-value" style={{ color: color }}>{score.toFixed(0)}</div>
                                                <div class="ueba-score-label" style={{ color: color }}>{severity.toUpperCase()}</div>
                                            </div>
                                        </div>
                                        <div class="ueba-risk-bar-bg">
                                            <div class="ueba-risk-bar-fill" style={{ width: `${Math.min(100, score)}%`, background: color }} />
                                        </div>
                                        <Show when={profile.anomaly_count}>
                                            <div class="ueba-meta">
                                                {profile.anomaly_count} ANOMALIES · {profile.last_activity?.slice(0, 10) ?? 'UNKNOWN'}
                                            </div>
                                        </Show>
                                    </div>
                                );
                            }}
                        </For>
                    </div>
                </Show>

                <Show when={selected()}>
                    <div class="ueba-detail-panel">
                        <div class="ob-section-header">ENTITY_DETAIL: {selected()?.entity_id}</div>
                        <div class="ueba-detail-grid">
                            <For each={Object.entries(selected() ?? {}).filter(([k]) => !['entity_id', 'risk_score'].includes(k))}>
                                {([k, v]) => (
                                    <div class="ueba-detail-item">
                                        <div class="ueba-detail-label">{k.replace(/_/g, ' ')}</div>
                                        <div class="ueba-detail-val">{String(v) || '—'}</div>
                                    </div>
                                )}
                            </For>
                        </div>
                    </div>
                </Show>
            </div>
        </PageLayout>
);
};

export default UEBAOverview;
