// frontend-web/src/pages/EvidenceVault.tsx
/**
 * EvidenceVault.tsx — Legal-Grade Digital Evidence Vault (Phase 6.5)
 *
 * Chain-of-custody browser, evidence submission, integrity verification,
 * and forensic export. Connects to /api/v1/forensics/*.
 */

import { createSignal, createResource, For, Show } from 'solid-js';
import { request } from '../services/api';

// ── Types ─────────────────────────────────────────────────────────────────────
interface ChainEntry {
  action: string;
  actor: string;
  timestamp: string;
  notes?: string;
  previous_hash: string;
  entry_hash: string;
}
interface EvidenceItem {
  id: string;
  incident_id: string;
  type: string;
  name: string;
  description?: string;
  sha256: string;
  size: number;
  collector: string;
  collected_at: string;
  sealed: boolean;
  sealed_at?: string;
  chain_of_custody: ChainEntry[];
  tags?: string[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────
const TYPE_ICONS: Record<string, string> = {
  file: '📄', log: '📋', screenshot: '🖼', pcap: '🌐',
  memory_dump: '💾', artifact: '🔍',
};
const ACTION_COLORS: Record<string, string> = {
  collected: '#00ff88', analyzed: '#ffaa00', transferred: '#0099ff',
  sealed: '#607070', exported: '#c8d8d8', verified: '#5cc05c',
};
const fmt = (n: number) => n < 1024 ? `${n} B`
  : n < 1048576 ? `${(n/1024).toFixed(1)} KB`
  : `${(n/1048576).toFixed(2)} MB`;

type Tab = 'all' | 'unsealed' | 'sealed';

// ── Component ─────────────────────────────────────────────────────────────────
export default function EvidenceVault() {
  const [tab, setTab] = createSignal<Tab>('all');
  const [selected, setSelected] = createSignal<EvidenceItem | null>(null);
  const [verifying, setVerifying] = createSignal<string | null>(null);
  const [verifyResult, setVerifyResult] = createSignal<Record<string, boolean>>({});
  const [search, setSearch] = createSignal('');

  const [items, { refetch }] = createResource<EvidenceItem[]>(async () => {
    const r = await request<{ items: EvidenceItem[] }>('/forensics/evidence');
    return r.items ?? [];
  });

  const filtered = () => {
    const q = search().toLowerCase();
    return (items() ?? []).filter(i => {
      if (tab() === 'sealed' && !i.sealed) return false;
      if (tab() === 'unsealed' && i.sealed) return false;
      return !q || i.name.toLowerCase().includes(q) || i.incident_id.toLowerCase().includes(q) || i.type.includes(q);
    });
  };

  async function verify(id: string) {
    setVerifying(id);
    try {
      const r = await request<{ valid: boolean }>(`/forensics/evidence/${id}/verify`);
      setVerifyResult(prev => ({ ...prev, [id]: r.valid }));
    } catch { setVerifyResult(prev => ({ ...prev, [id]: false })); }
    setVerifying(null);
  }

  async function seal(id: string) {
    await request(`/forensics/evidence/${id}/seal`, { method: 'POST' });
    refetch();
  }

  async function exportVault() {
    const url = `/api/v1/forensics/export`;
    const token = localStorage.getItem('oblivra_token');
    const a = document.createElement('a');
    a.href = url + (token ? `?token=${token}` : '');
    a.download = `oblivra-evidence-${Date.now()}.json`;
    a.click();
  }

  const TAB = (t: Tab) =>
    `padding:0.5rem 1.2rem; cursor:pointer; font-size:0.78rem; letter-spacing:0.12em; border:none; border-bottom:2px solid ${tab()===t ? '#ff3355' : 'transparent'}; background:none; color:${tab()===t ? '#ff3355' : '#607070'};`;

  return (
    <div style="padding:2rem; color:#c8d8d8; font-family:'JetBrains Mono',monospace; min-height:100vh; background:#080f12;">
      {/* Header */}
      <div style="display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:1.5rem;">
        <div>
          <h1 style="font-size:1.4rem; letter-spacing:0.15em; margin:0; color:#ff3355;">⬡ EVIDENCE VAULT</h1>
          <p style="margin:0.25rem 0 0; font-size:0.75rem; color:#607070;">
            Chain-of-custody · Integrity verification · Legal-grade forensics
          </p>
        </div>
        <div style="display:flex; gap:0.75rem;">
          <button onClick={exportVault}
            style="background:#ff3355; color:#080f12; border:none; padding:0.45rem 1rem; border-radius:3px; cursor:pointer; font-weight:700; font-size:0.75rem; letter-spacing:0.08em;">
            ↓ EXPORT VAULT
          </button>
          <button onClick={() => refetch()}
            style="background:#0d1a1f; border:1px solid #1e3040; color:#607070; padding:0.45rem 0.75rem; border-radius:3px; cursor:pointer; font-size:0.75rem;">
            ↻
          </button>
        </div>
      </div>

      {/* Stats strip */}
      <Show when={!items.loading}>
        <div style="display:grid; grid-template-columns:repeat(4,1fr); gap:1rem; margin-bottom:1.5rem;">
          {[
            { label: 'TOTAL', value: (items()??[]).length, color: '#c8d8d8' },
            { label: 'SEALED', value: (items()??[]).filter(i=>i.sealed).length, color: '#607070' },
            { label: 'ACTIVE', value: (items()??[]).filter(i=>!i.sealed).length, color: '#00ff88' },
            { label: 'INCIDENTS', value: new Set((items()??[]).map(i=>i.incident_id)).size, color: '#ffaa00' },
          ].map(s => (
            <div style="background:#0d1a1f; border:1px solid #1e3040; border-top:2px solid #1e3040; padding:0.9rem; border-radius:4px;">
              <div style={`font-size:1.4rem; font-weight:700; color:${s.color};`}>{s.value}</div>
              <div style="font-size:0.65rem; color:#607070; letter-spacing:0.12em;">{s.label}</div>
            </div>
          ))}
        </div>
      </Show>

      {/* Filter + tabs */}
      <div style="display:flex; align-items:center; justify-content:space-between; border-bottom:1px solid #1e3040; margin-bottom:1.25rem;">
        <div>
          {(['all','unsealed','sealed'] as Tab[]).map(t => (
            <button style={TAB(t)} onClick={() => setTab(t)}>{t.toUpperCase()}</button>
          ))}
        </div>
        <input type="text" value={search()} onInput={e => setSearch(e.currentTarget.value)}
          placeholder="Filter by name, incident, type…"
          style="background:#0d1a1f; border:1px solid #1e3040; color:#c8d8d8; padding:0.35rem 0.75rem; border-radius:3px; font-size:0.75rem; width:260px; margin-bottom:0.5rem;" />
      </div>

      {/* Evidence table */}
      <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; overflow:hidden; margin-bottom:1.5rem;">
        <table style="width:100%; border-collapse:collapse; font-size:0.74rem;">
          <thead>
            <tr style="border-bottom:1px solid #1e3040; background:#0a1318;">
              {['TYPE','NAME','INCIDENT','SIZE','COLLECTOR','STATUS','ACTIONS'].map(h => (
                <th style="padding:0.6rem 0.9rem; text-align:left; color:#607070; letter-spacing:0.1em; font-weight:400;">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            <Show when={!items.loading} fallback={
              <tr><td colspan="7" style="padding:1.5rem; text-align:center; color:#607070;">Loading evidence…</td></tr>
            }>
              <For each={filtered()} fallback={
                <tr><td colspan="7" style="padding:1.5rem; text-align:center; color:#607070;">No evidence items found.</td></tr>
              }>
                {(item) => (
                  <tr style="border-bottom:1px solid #0a1318; cursor:pointer;"
                    onMouseEnter={e => (e.currentTarget as HTMLElement).style.background = '#111f28'}
                    onMouseLeave={e => (e.currentTarget as HTMLElement).style.background = ''}
                    onClick={() => setSelected(selected()?.id === item.id ? null : item)}>
                    <td style="padding:0.55rem 0.9rem; color:#607070;">{TYPE_ICONS[item.type] ?? '?'} {item.type}</td>
                    <td style="padding:0.55rem 0.9rem; color:#c8d8d8; max-width:180px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;" title={item.name}>{item.name}</td>
                    <td style="padding:0.55rem 0.9rem; color:#607070; font-size:0.68rem;">{item.incident_id.slice(0,12)}…</td>
                    <td style="padding:0.55rem 0.9rem; color:#607070;">{fmt(item.size)}</td>
                    <td style="padding:0.55rem 0.9rem; color:#607070;">{item.collector}</td>
                    <td style="padding:0.55rem 0.9rem;">
                      <span style={`font-size:0.65rem; font-weight:700; letter-spacing:0.1em; color:${item.sealed ? '#607070' : '#00ff88'};`}>
                        {item.sealed ? '🔒 SEALED' : '● ACTIVE'}
                      </span>
                    </td>
                    <td style="padding:0.55rem 0.9rem;">
                      <div style="display:flex; gap:0.4rem;">
                        <button onClick={e => { e.stopPropagation(); verify(item.id); }}
                          disabled={verifying() === item.id}
                          style={`background:${verifyResult()[item.id] === true ? '#001a0a' : verifyResult()[item.id] === false ? '#2a0d15' : '#0a1318'}; border:1px solid ${verifyResult()[item.id] === true ? '#00ff88' : verifyResult()[item.id] === false ? '#ff3355' : '#1e3040'}; color:${verifyResult()[item.id] === true ? '#00ff88' : verifyResult()[item.id] === false ? '#ff3355' : '#607070'}; padding:0.25rem 0.5rem; border-radius:2px; cursor:pointer; font-size:0.65rem;`}>
                          {verifying() === item.id ? '…' : verifyResult()[item.id] === true ? '✓ OK' : verifyResult()[item.id] === false ? '✗ FAIL' : 'VERIFY'}
                        </button>
                        <Show when={!item.sealed}>
                          <button onClick={e => { e.stopPropagation(); seal(item.id); }}
                            style="background:#0a1318; border:1px solid #1e3040; color:#607070; padding:0.25rem 0.5rem; border-radius:2px; cursor:pointer; font-size:0.65rem;">
                            SEAL
                          </button>
                        </Show>
                      </div>
                    </td>
                  </tr>
                )}
              </For>
            </Show>
          </tbody>
        </table>
      </div>

      {/* Detail panel — Chain of Custody */}
      <Show when={selected()}>
        {(item) => (
          <div style="background:#0d1a1f; border:1px solid #1e3040; border-top:2px solid #ff3355; border-radius:6px; padding:1.25rem;">
            <div style="display:flex; justify-content:space-between; margin-bottom:1rem;">
              <div>
                <div style="font-size:0.88rem; color:#ff3355; letter-spacing:0.08em;">{item().name}</div>
                <div style="font-size:0.7rem; color:#607070; margin-top:0.25rem;">SHA-256: {item().sha256}</div>
              </div>
              <button onClick={() => setSelected(null)} style="background:none; border:none; color:#607070; cursor:pointer; font-size:1rem;">✕</button>
            </div>

            <div style="font-size:0.65rem; color:#607070; letter-spacing:0.12em; margin-bottom:0.75rem;">CHAIN OF CUSTODY</div>
            <div style="display:flex; flex-direction:column; gap:0;">
              <For each={item().chain_of_custody}>
                {(entry, idx) => (
                  <div style={`display:flex; gap:1rem; padding:0.6rem 0; ${idx() < item().chain_of_custody.length-1 ? 'border-bottom:1px solid #0a1318' : ''}`}>
                    <div style="display:flex; flex-direction:column; align-items:center; gap:0;">
                      <div style={`width:8px; height:8px; border-radius:50%; background:${ACTION_COLORS[entry.action] ?? '#607070'}; flex-shrink:0;`}></div>
                      <Show when={idx() < item().chain_of_custody.length-1}>
                        <div style="width:1px; background:#1e3040; flex:1; min-height:12px;"></div>
                      </Show>
                    </div>
                    <div style="flex:1;">
                      <div style="display:flex; gap:0.75rem; align-items:baseline;">
                        <span style={`font-size:0.7rem; font-weight:700; color:${ACTION_COLORS[entry.action] ?? '#607070'}; letter-spacing:0.1em;`}>{entry.action.toUpperCase()}</span>
                        <span style="font-size:0.68rem; color:#607070;">{entry.actor}</span>
                        <span style="font-size:0.65rem; color:#3a5060; margin-left:auto;">{new Date(entry.timestamp).toLocaleString()}</span>
                      </div>
                      <Show when={entry.notes}>
                        <div style="font-size:0.68rem; color:#607070; margin-top:0.15rem;">{entry.notes}</div>
                      </Show>
                      <div style="font-size:0.6rem; color:#1e3040; margin-top:0.15rem; font-family:monospace;" title="HMAC entry hash">
                        #{entry.entry_hash.slice(0,16)}…
                      </div>
                    </div>
                  </div>
                )}
              </For>
            </div>
          </div>
        )}
      </Show>
    </div>
  );
}

// frontend-web/src/pages/EvidenceVault.svelte
<!-- OBLIVRA Web — EvidenceVault (Svelte 5) -->
<script lang="ts">
  import { onMount } from 'svelte';
  import { KPI, Badge, PageLayout, Button, DataTable, Spinner, ProgressBar } from '@components/ui';
  import { Lock, Unlock, FileText, Download, History, Search, Filter, ShieldCheck, ShieldAlert, HardDrive } from 'lucide-svelte';
  import { request } from '../services/api';

  // -- Types --
  interface ChainEntry {
    action: string;
    actor: string;
    timestamp: string;
    notes?: string;
    previous_hash: string;
    entry_hash: string;
  }
  interface EvidenceItem {
    id: string;
    incident_id: string;
    type: string;
    name: string;
    description?: string;
    sha256: string;
    size: number;
    collector: string;
    collected_at: string;
    sealed: boolean;
    sealed_at?: string;
    chain_of_custody: ChainEntry[];
    tags?: string[];
  }

  // -- State --
  let items       = $state<EvidenceItem[]>([]);
  let loading     = $state(true);
  let selected    = $state<EvidenceItem | null>(null);
  let search      = $state('');
  let tab         = $state<'all' | 'unsealed' | 'sealed'>('all');
  let verifying   = $state<string | null>(null);
  let verifyRes   = $state<Record<string, boolean>>({});

  // -- Helpers --
  const fmtSize = (n: number) => n < 1024 ? `${n} B` : n < 1048576 ? `${(n/1024).toFixed(1)} KB` : `${(n/1048576).toFixed(2)} MB`;
  const actionColor: Record<string, string> = {
    collected: 'var(--status-online)',
    analyzed: 'var(--alert-high)',
    transferred: 'var(--accent-primary)',
    sealed: 'var(--text-muted)',
    exported: 'var(--text-primary)',
    verified: 'var(--success)'
  };

  // -- Actions --
  async function fetchEvidence() {
    loading = true;
    try {
      const res = await request<{ items: EvidenceItem[] }>('/forensics/evidence');
      items = res.items ?? [];
    } catch {
      items = [];
    } finally {
      loading = false;
    }
  }

  async function verify(id: string) {
    verifying = id;
    try {
      const res = await request<{ valid: boolean }>(`/forensics/evidence/${id}/verify`);
      verifyRes = { ...verifyRes, [id]: res.valid };
    } catch {
      verifyRes = { ...verifyRes, [id]: false };
    } finally {
      verifying = null;
    }
  }

  async function seal(id: string) {
    try {
      await request(`/forensics/evidence/${id}/seal`, { method: 'POST' });
      fetchEvidence();
    } catch (e) {
      console.error('Sealing failed', e);
    }
  }

  function exportVault() {
    const url = `/api/v1/forensics/export`;
    const token = localStorage.getItem('oblivra_token');
    const a = document.createElement('a');
    a.href = url + (token ? `?token=${token}` : '');
    a.download = `oblivra-evidence-${Date.now()}.json`;
    a.click();
  }

  const displayed = $derived.by(() => {
    const q = search.toLowerCase();
    return items.filter(i => {
      if (tab === 'sealed' && !i.sealed) return false;
      if (tab === 'unsealed' && i.sealed) return false;
      return !q || i.name.toLowerCase().includes(q) || i.incident_id.toLowerCase().includes(q) || i.type.includes(q);
    });
  });

  onMount(() => {
    fetchEvidence();
  });
</script>

<PageLayout title="Evidence Vault" subtitle="Immutable forensic storage shards with hardware-backed chain of custody">
  {#snippet toolbar()}
    <div class="flex items-center gap-2">
      <Button variant="secondary" size="sm" onclick={fetchEvidence}>
        <History size={14} class="mr-2" />
        Refresh
      </Button>
      <Button variant="primary" size="sm" onclick={exportVault}>
        <Download size={14} class="mr-2" />
        Export Vault
      </Button>
    </div>
  {/snippet}

  <div class="flex flex-col h-full gap-6">
    <!-- Pulse Stats -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-4 shrink-0">
      <KPI title="Total Artifacts" value={items.length.toString()} trend="Global" variant="accent" />
      <KPI title="Sealed Evidence" value={items.filter(i => i.sealed).length.toString()} trend="Locked" variant="success" />
      <KPI title="Active Forensics" value={items.filter(i => !i.sealed).length.toString()} trend="In Triage" variant="warning" />
      <KPI title="Root Trust" value="VERIFIED" trend="TPM 2.0" variant="success" />
    </div>

    <!-- Main View -->
    <div class="flex flex-col lg:flex-row gap-6 flex-1 min-h-0">
      <!-- Evidence List -->
      <div class="flex-1 flex flex-col bg-surface-1 border border-border-primary rounded-sm overflow-hidden shadow-premium">
        <div class="p-3 bg-surface-2 border-b border-border-primary flex justify-between items-center">
          <div class="flex items-center gap-4">
            <div class="flex border border-border-primary rounded-sm overflow-hidden">
              {#each ['all', 'unsealed', 'sealed'] as t}
                <button
                  class="px-3 py-1 text-[10px] font-bold uppercase tracking-widest transition-colors
                    {tab === t ? 'bg-accent-primary text-black' : 'bg-surface-0 text-text-muted hover:text-text-secondary'}"
                  onclick={() => tab = t as any}
                >
                  {t}
                </button>
              {/each}
            </div>
            <div class="relative w-64">
              <input
                type="text"
                bind:value={search}
                placeholder="Filter evidence..."
                class="w-full bg-surface-0 border border-border-primary text-text-primary px-3 py-1 rounded-sm font-mono text-[10px] focus:outline-hidden"
              />
              <Search size={12} class="absolute right-2 top-1.5 text-text-muted opacity-50" />
            </div>
          </div>
          <Badge variant="secondary" size="xs">{displayed.length} ITEMS</Badge>
        </div>

        <div class="flex-1 overflow-auto">
          {#if loading}
            <div class="h-full flex items-center justify-center">
              <Spinner />
            </div>
          {:else}
            <DataTable
              data={displayed}
              columns={[
                { key: 'type', label: 'TYPE', width: '100px' },
                { key: 'name', label: 'ARTIFACT_NAME' },
                { key: 'incident_id', label: 'CASE_REF', width: '120px' },
                { key: 'size', label: 'SIZE', width: '80px' },
                { key: 'status', label: 'STATE', width: '100px' },
                { key: 'actions', label: 'OPERATIONS', width: '140px' }
              ]}
              compact
              rowKey="id"
              onRowClick={(row) => selected = selected?.id === row.id ? null : row}
            >
              {#snippet cell({ column, row })}
                {#if column.key === 'type'}
                  <div class="flex items-center gap-2">
                    <FileText size={12} class="text-text-muted" />
                    <span class="text-[10px] font-mono text-text-muted uppercase">{row.type}</span>
                  </div>
                {:else if column.key === 'name'}
                  <span class="font-bold text-text-heading truncate block max-w-[200px]">{row.name}</span>
                {:else if column.key === 'incident_id'}
                  <span class="text-[10px] font-mono text-accent-primary">{row.incident_id.slice(0, 12)}…</span>
                {:else if column.key === 'size'}
                  <span class="text-[10px] font-mono text-text-muted">{fmtSize(row.size)}</span>
                {:else if column.key === 'status'}
                  <Badge variant={row.sealed ? 'secondary' : 'success'} size="xs" dot>
                    {row.sealed ? 'SEALED' : 'ACTIVE'}
                  </Badge>
                {:else if column.key === 'actions'}
                  <div class="flex gap-2">
                    <button
                      class="text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 border border-border-primary rounded-sm transition-colors
                        {verifyRes[row.id] === true ? 'border-status-online text-status-online bg-status-online/10' : 
                         verifyRes[row.id] === false ? 'border-alert-critical text-alert-critical bg-alert-critical/10' : 
                         'text-text-muted hover:text-text-primary'}"
                      onclick={(e) => { e.stopPropagation(); verify(row.id); }}
                      disabled={verifying === row.id}
                    >
                      {verifying === row.id ? '...' : verifyRes[row.id] === true ? 'VALID' : verifyRes[row.id] === false ? 'FAILED' : 'VERIFY'}
                    </button>
                    {#if !row.sealed}
                      <button
                        class="text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 border border-border-primary rounded-sm text-text-muted hover:text-alert-high hover:border-alert-high transition-colors"
                        onclick={(e) => { e.stopPropagation(); seal(row.id); }}
                      >
                        SEAL
                      </button>
                    {/if}
                  </div>
                {/if}
              {/snippet}
            </DataTable>
          {/if}
        </div>
      </div>

      <!-- Detail Panel -->
      <div class="w-full lg:w-96 flex flex-col bg-surface-1 border border-border-primary rounded-sm overflow-hidden shadow-premium">
        {#if !selected}
          <div class="flex-1 flex flex-col items-center justify-center text-text-muted opacity-40 gap-4 p-8 text-center">
            <Lock size={48} />
            <p class="font-mono text-[10px] uppercase tracking-widest">Select an artifact to inspect chain of custody</p>
          </div>
        {:else}
          <div class="p-4 bg-surface-2 border-b border-border-primary flex justify-between items-center">
             <div class="flex items-center gap-2">
                {#if selected.sealed}<Lock size={14} class="text-text-muted" />{:else}<Unlock size={14} class="text-status-online" />{/if}
                <span class="text-[10px] font-bold text-text-heading uppercase tracking-widest">Chain of Custody</span>
             </div>
             <button class="text-text-muted hover:text-text-primary" onclick={() => selected = null}>✕</button>
          </div>
          
          <div class="flex-1 overflow-auto p-4 flex flex-col gap-6">
            <div>
              <div class="text-[10px] font-bold text-text-muted uppercase tracking-widest mb-2">Artifact Metadata</div>
              <div class="bg-surface-0 p-3 border border-border-primary rounded-sm space-y-2">
                <div class="flex justify-between items-center">
                  <span class="text-[9px] font-mono text-text-muted">NAME</span>
                  <span class="text-[10px] font-bold text-text-primary truncate ml-4">{selected.name}</span>
                </div>
                <div class="flex flex-col gap-1">
                  <span class="text-[9px] font-mono text-text-muted">SHA-256 HASH</span>
                  <code class="text-[9px] font-mono text-accent-primary break-all bg-surface-1 p-1 rounded-xs border border-border-subtle">{selected.sha256}</code>
                </div>
              </div>
            </div>

            <div class="flex-1 flex flex-col min-h-0">
               <div class="text-[10px] font-bold text-text-muted uppercase tracking-widest mb-3">Custody Timeline</div>
               <div class="relative space-y-0 pl-4 border-l border-border-primary ml-1">
                 {#each selected.chain_of_custody as entry, i}
                    <div class="relative pb-6 last:pb-0">
                      <!-- Dot -->
                      <div class="absolute -left-[20.5px] top-1.5 w-2 h-2 rounded-full border border-surface-1" style="background: {actionColor[entry.action] ?? 'var(--text-muted)'}"></div>
                      
                      <div class="flex flex-col gap-1">
                        <div class="flex justify-between items-center">
                          <span class="text-[10px] font-black uppercase tracking-widest" style="color: {actionColor[entry.action] ?? 'var(--text-muted)'}">{entry.action}</span>
                          <span class="text-[9px] font-mono text-text-muted opacity-50">{new Date(entry.timestamp).toLocaleString()}</span>
                        </div>
                        <div class="text-[11px] font-bold text-text-secondary">{entry.actor}</div>
                        {#if entry.notes}
                          <div class="text-[10px] text-text-muted italic bg-surface-0/50 p-1.5 border-l border-border-primary mt-1">{entry.notes}</div>
                        {/if}
                        <div class="text-[8px] font-mono text-text-muted opacity-30 mt-1 uppercase tracking-tighter">HMAC: {entry.entry_hash.slice(0, 24)}...</div>
                      </div>
                    </div>
                 {/each}
               </div>
            </div>
          </div>
          
          <div class="p-4 bg-surface-2 border-t border-border-primary flex gap-2">
            <Button variant="secondary" size="sm" class="flex-1" icon={ShieldCheck} onclick={() => verify(selected!.id)}>VERIFY INTEGRITY</Button>
            {#if !selected.sealed}
               <Button variant="primary" size="sm" class="flex-1" icon={Lock} onclick={() => seal(selected!.id)}>SEAL ARTIFACT</Button>
            {/if}
          </div>
        {/if}
      </div>
    </div>
  </div>
</PageLayout>

<style>
  :global(.mask-fade-bottom) {
    mask-image: linear-gradient(to bottom, black 90%, transparent 100%);
  }
</style>
