// frontend-web/src/pages/IdentityAdmin.svelte
<!-- OBLIVRA Web — IdentityAdmin (Svelte 5) -->
<script lang="ts">
  import { onMount } from 'svelte';
  import { request } from '../services/api';

  interface User  { id:string; email:string; name:string; role_id:string; role_name:string; tenant_id:string; created_at:string; last_login?:string; mfa_enabled?:boolean; }
  interface Role  { id:string; name:string; permissions:string[]; }

  type Tab = 'users'|'roles'|'providers';
  let tab       = $state<Tab>('users');
  let users     = $state<User[]>([]);
  let roles     = $state<Role[]>([]);
  let loading   = $state(true);
  let userSearch = $state('');

  onMount(async () => {
    try { users = await request<User[]>('/users'); } catch { users = []; }
    try { roles = await request<Role[]>('/roles'); } catch { roles = []; }
    loading = false;
  });

  const filteredUsers = $derived(users.filter(u =>
    u.email.toLowerCase().includes(userSearch.toLowerCase()) ||
    u.name.toLowerCase().includes(userSearch.toLowerCase())
  ));

  const providers = [
    { name:'OIDC / OAuth2', desc:'Google Workspace, Okta, Azure AD', endpoint:'/api/v1/auth/oidc/login', status:'configured' },
    { name:'SAML 2.0',      desc:'Okta SAML, ADFS, PingIdentity',   endpoint:'/api/v1/auth/saml/login',  status:'configured' },
  ];
</script>

<div class="ia-page">
  <div class="ia-header">
    <h1 class="ia-title">⬡ IDENTITY ADMINISTRATION</h1>
    <p class="ia-sub">User management, roles &amp; federated identity configuration</p>
  </div>

  <div class="ia-tabs">
    {#each (['users','roles','providers'] as Tab[]) as t}
      <button class="ia-tab {tab===t ? 'ia-tab--active' : ''}" onclick={() => tab = t}>{t.toUpperCase()}</button>
    {/each}
  </div>

  {#if tab === 'users'}
    <div class="ia-toolbar">
      <input type="text" placeholder="Search users…" bind:value={userSearch} class="ia-search" />
      <button class="ia-invite-btn">+ INVITE USER</button>
    </div>
    <div class="ia-table-wrap">
      <table class="ia-table">
        <thead><tr>{#each ['NAME','EMAIL','ROLE','TENANT','MFA','LAST LOGIN'] as h}<th>{h}</th>{/each}</tr></thead>
        <tbody>
          {#if loading}
            <tr><td colspan="6" class="ia-center">Loading…</td></tr>
          {:else if filteredUsers.length === 0}
            <tr><td colspan="6" class="ia-center">No users found.</td></tr>
          {:else}
            {#each filteredUsers as u (u.id)}
              <tr class="ia-row">
                <td>{u.name}</td>
                <td class="ia-muted">{u.email}</td>
                <td><span class="ia-role-badge">{(u.role_name??u.role_id).toUpperCase()}</span></td>
                <td class="ia-teal">{u.tenant_id||'GLOBAL'}</td>
                <td><span style="color:{u.mfa_enabled ? '#00ff88' : '#ff3355'}">{u.mfa_enabled ? '✓ ON' : '✗ OFF'}</span></td>
                <td class="ia-muted">{u.last_login ? new Date(u.last_login).toLocaleDateString() : '—'}</td>
              </tr>
            {/each}
          {/if}
        </tbody>
      </table>
    </div>

  {:else if tab === 'roles'}
    <div class="ia-grid">
      {#each roles as role (role.id)}
        <div class="ia-role-card">
          <div class="ia-role-header">
            <span class="ia-role-name">{role.name.toUpperCase()}</span>
            <button class="ia-edit-btn">EDIT</button>
          </div>
          <div class="ia-perms">
            {#each role.permissions as p}<span class="ia-perm">{p}</span>{/each}
          </div>
        </div>
      {:else}
        <div class="ia-muted">No roles defined.</div>
      {/each}
    </div>

  {:else}
    <div class="ia-grid">
      {#each providers as p}
        <div class="ia-provider-card">
          <div>
            <div class="ia-provider-name">{p.name}</div>
            <div class="ia-muted">{p.desc}</div>
          </div>
          <div class="ia-provider-right">
            <span class="ia-provider-status">● {p.status.toUpperCase()}</span>
            <button class="ia-test-btn" onclick={() => window.location.href = p.endpoint}>TEST LOGIN</button>
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>

<style>
  .ia-page { padding:28px; color:#c8d8d8; font-family:var(--font-mono); min-height:100vh; background:#080f12; }
  .ia-header { margin-bottom:20px; }
  .ia-title  { font-size:20px; letter-spacing:.14em; margin:0; color:#00ffe7; }
  .ia-sub    { margin:3px 0 0; font-size:11px; color:#607070; }
  .ia-tabs   { display:flex; border-bottom:1px solid #1e3040; margin-bottom:20px; }
  .ia-tab    { padding:8px 18px; cursor:pointer; font-size:11px; letter-spacing:.12em; border:none; border-bottom:2px solid transparent; background:none; color:#607070; font-family:inherit; transition:color 100ms; }
  .ia-tab--active { border-bottom-color:#00ffe7; color:#00ffe7; }
  .ia-toolbar { display:flex; justify-content:space-between; margin-bottom:14px; }
  .ia-search  { background:#0d1a1f; border:1px solid #1e3040; color:#c8d8d8; padding:7px 12px; border-radius:4px; font-size:12px; width:240px; font-family:inherit; outline:none; }
  .ia-invite-btn { background:#1e3040; border:1px solid #00ffe7; color:#00ffe7; padding:7px 14px; border-radius:4px; cursor:pointer; font-size:11px; letter-spacing:.1em; font-family:inherit; }
  .ia-table-wrap { background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; overflow:hidden; }
  .ia-table { width:100%; border-collapse:collapse; font-size:11px; }
  .ia-table thead tr { border-bottom:1px solid #1e3040; background:#0a1318; }
  .ia-table th { padding:9px 14px; text-align:left; color:#607070; letter-spacing:.1em; font-weight:400; font-size:10px; }
  .ia-row { border-bottom:1px solid #0a1318; transition:background 80ms; }
  .ia-row:hover { background:#111f28; }
  .ia-row td { padding:9px 14px; }
  .ia-muted { color:#607070; }
  .ia-teal  { color:#00ffe7; }
  .ia-role-badge { background:#1e3040; color:#00ffe7; padding:2px 7px; border-radius:3px; font-size:10px; letter-spacing:.1em; }
  .ia-center { padding:28px; text-align:center; color:#607070; }
  .ia-grid   { display:flex; flex-direction:column; gap:14px; }
  .ia-role-card { background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:16px; }
  .ia-role-header { display:flex; justify-content:space-between; align-items:center; margin-bottom:10px; }
  .ia-role-name   { color:#00ffe7; font-size:13px; letter-spacing:.12em; }
  .ia-edit-btn { background:none; border:1px solid #1e3040; color:#607070; padding:3px 10px; border-radius:3px; cursor:pointer; font-size:11px; font-family:inherit; }
  .ia-perms { display:flex; flex-wrap:wrap; gap:5px; }
  .ia-perm  { background:#111f28; border:1px solid #1e3040; color:#607070; padding:2px 7px; border-radius:3px; font-size:10px; }
  .ia-provider-card  { background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:18px; display:flex; justify-content:space-between; align-items:center; }
  .ia-provider-name  { color:#00ffe7; font-size:13px; letter-spacing:.12em; margin-bottom:3px; }
  .ia-provider-right { display:flex; align-items:center; gap:14px; }
  .ia-provider-status { color:#00ff88; font-size:11px; letter-spacing:.1em; }
  .ia-test-btn { background:#1e3040; border:1px solid #00ffe7; color:#00ffe7; padding:6px 14px; border-radius:4px; cursor:pointer; font-size:11px; font-family:inherit; }
</style>

// frontend-web/src/pages/IdentityAdmin.tsx
/**
 * IdentityAdmin.tsx — User & Role Administration (Web Only — Phase 0.5)
 *
 * Provides identity management: view/invite users, manage roles,
 * and configure OIDC/SAML identity provider settings.
 * Connects to /api/v1/users and /api/v1/roles.
 */

import { createSignal, createResource, For, Show } from 'solid-js';
import { request } from '../services/api';

interface User {
  id: string;
  email: string;
  name: string;
  role_id: string;
  role_name: string;
  tenant_id: string;
  created_at: string;
  last_login?: string;
  mfa_enabled?: boolean;
}

interface Role {
  id: string;
  name: string;
  permissions: string[];
}

async function fetchUsers(): Promise<User[]> {
  try { return await request<User[]>('/users'); } catch { return []; }
}
async function fetchRoles(): Promise<Role[]> {
  try { return await request<Role[]>('/roles'); } catch { return []; }
}

type Tab = 'users' | 'roles' | 'providers';

export default function IdentityAdmin() {
  const [tab, setTab] = createSignal<Tab>('users');
  const [users] = createResource(fetchUsers);
  const [roles] = createResource(fetchRoles);
  const [userSearch, setUserSearch] = createSignal('');

  const filteredUsers = () =>
    (users() ?? []).filter(u =>
      u.email.toLowerCase().includes(userSearch().toLowerCase()) ||
      u.name.toLowerCase().includes(userSearch().toLowerCase())
    );

  const TAB_STYLE = (active: boolean) =>
    `padding:0.5rem 1.2rem; cursor:pointer; font-size:0.78rem; letter-spacing:0.12em; border:none; border-bottom:2px solid ${active ? '#00ffe7' : 'transparent'}; background:none; color:${active ? '#00ffe7' : '#607070'}; transition:color 0.15s;`;

  return (
    <div style="padding:2rem; color:#c8d8d8; font-family:'JetBrains Mono',monospace; min-height:100vh; background:#080f12;">
      {/* Header */}
      <div style="margin-bottom:1.5rem;">
        <h1 style="font-size:1.4rem; letter-spacing:0.15em; margin:0; color:#00ffe7;">⬡ IDENTITY ADMINISTRATION</h1>
        <p style="margin:0.25rem 0 0; font-size:0.75rem; color:#607070;">User management, roles & federated identity configuration</p>
      </div>

      {/* Tabs */}
      <div style="display:flex; border-bottom:1px solid #1e3040; margin-bottom:1.5rem;">
        {(['users', 'roles', 'providers'] as Tab[]).map(t => (
          <button style={TAB_STYLE(tab() === t)} onClick={() => setTab(t)}>
            {t.toUpperCase()}
          </button>
        ))}
      </div>

      {/* Users Tab */}
      <Show when={tab() === 'users'}>
        <div style="display:flex; justify-content:space-between; margin-bottom:1rem;">
          <input
            type="text" placeholder="Search users…"
            value={userSearch()} onInput={e => setUserSearch(e.currentTarget.value)}
            style="background:#0d1a1f; border:1px solid #1e3040; color:#c8d8d8; padding:0.5rem 0.75rem; border-radius:4px; font-size:0.8rem; width:240px;"
          />
          <button style="background:#1e3040; border:1px solid #00ffe7; color:#00ffe7; padding:0.5rem 1rem; border-radius:4px; cursor:pointer; font-size:0.78rem; letter-spacing:0.1em;">
            + INVITE USER
          </button>
        </div>
        <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; overflow:hidden;">
          <table style="width:100%; border-collapse:collapse; font-size:0.77rem;">
            <thead>
              <tr style="border-bottom:1px solid #1e3040; background:#0a1318;">
                {['NAME', 'EMAIL', 'ROLE', 'TENANT', 'MFA', 'LAST LOGIN'].map(h => (
                  <th style="padding:0.65rem 1rem; text-align:left; color:#607070; letter-spacing:0.1em; font-weight:400;">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              <Show when={!users.loading} fallback={<tr><td colspan="6" style="padding:2rem; text-align:center; color:#607070;">Loading…</td></tr>}>
                <For each={filteredUsers()} fallback={<tr><td colspan="6" style="padding:2rem; text-align:center; color:#607070;">No users found.</td></tr>}>
                  {(u) => (
                    <tr style="border-bottom:1px solid #0a1318;" onMouseEnter={e => (e.currentTarget as HTMLElement).style.background='#111f28'} onMouseLeave={e => (e.currentTarget as HTMLElement).style.background=''}>
                      <td style="padding:0.65rem 1rem; color:#c8d8d8;">{u.name}</td>
                      <td style="padding:0.65rem 1rem; color:#607070;">{u.email}</td>
                      <td style="padding:0.65rem 1rem;">
                        <span style="background:#1e3040; color:#00ffe7; padding:0.15rem 0.5rem; border-radius:3px; font-size:0.7rem; letter-spacing:0.1em;">
                          {(u.role_name ?? u.role_id).toUpperCase()}
                        </span>
                      </td>
                      <td style="padding:0.65rem 1rem; color:#00ffe7;">{u.tenant_id || 'GLOBAL'}</td>
                      <td style="padding:0.65rem 1rem;">
                        <span style={`color:${u.mfa_enabled ? '#00ff88' : '#ff3355'}; font-size:0.7rem;`}>
                          {u.mfa_enabled ? '✓ ON' : '✗ OFF'}
                        </span>
                      </td>
                      <td style="padding:0.65rem 1rem; color:#607070;">
                        {u.last_login ? new Date(u.last_login).toLocaleDateString() : '—'}
                      </td>
                    </tr>
                  )}
                </For>
              </Show>
            </tbody>
          </table>
        </div>
      </Show>

      {/* Roles Tab */}
      <Show when={tab() === 'roles'}>
        <div style="display:grid; gap:1rem;">
          <Show when={!roles.loading} fallback={<div style="color:#607070;">Loading roles…</div>}>
            <For each={roles()} fallback={<div style="color:#607070;">No roles defined.</div>}>
              {(role) => (
                <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:1rem;">
                  <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:0.75rem;">
                    <span style="color:#00ffe7; font-size:0.9rem; letter-spacing:0.12em;">{role.name.toUpperCase()}</span>
                    <button style="background:none; border:1px solid #1e3040; color:#607070; padding:0.25rem 0.75rem; border-radius:3px; cursor:pointer; font-size:0.72rem;">EDIT</button>
                  </div>
                  <div style="display:flex; flex-wrap:wrap; gap:0.4rem;">
                    <For each={role.permissions}>
                      {(p) => (
                        <span style="background:#111f28; border:1px solid #1e3040; color:#607070; padding:0.15rem 0.5rem; border-radius:3px; font-size:0.7rem;">{p}</span>
                      )}
                    </For>
                  </div>
                </div>
              )}
            </For>
          </Show>
        </div>
      </Show>

      {/* Identity Providers Tab */}
      <Show when={tab() === 'providers'}>
        <div style="display:grid; gap:1rem;">
          {[
            { name: 'OIDC / OAuth2', desc: 'Google Workspace, Okta, Azure AD', endpoint: '/api/v1/auth/oidc/login', status: 'configured' },
            { name: 'SAML 2.0',      desc: 'Okta SAML, ADFS, PingIdentity',   endpoint: '/api/v1/auth/saml/login',  status: 'configured' },
          ].map(p => (
            <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:1.25rem; display:flex; justify-content:space-between; align-items:center;">
              <div>
                <div style="color:#00ffe7; font-size:0.9rem; letter-spacing:0.12em; margin-bottom:0.25rem;">{p.name}</div>
                <div style="color:#607070; font-size:0.76rem;">{p.desc}</div>
                <div style="color:#1e3040; font-size:0.7rem; margin-top:0.25rem;">{p.endpoint}</div>
              </div>
              <div style="display:flex; align-items:center; gap:1rem;">
                <span style="color:#00ff88; font-size:0.75rem; letter-spacing:0.1em;">● {p.status.toUpperCase()}</span>
                <button
                  onClick={() => window.location.href = p.endpoint}
                  style="background:#1e3040; border:1px solid #00ffe7; color:#00ffe7; padding:0.4rem 0.9rem; border-radius:4px; cursor:pointer; font-size:0.75rem; letter-spacing:0.1em;"
                >
                  TEST LOGIN
                </button>
              </div>
            </div>
          ))}
        </div>
      </Show>
    </div>
  );
}
