// frontend/src/pages/Login.svelte
<!--
  OBLIVRA — Login Page (Svelte 5)
  Used in BROWSER mode for standard web authentication.
-->
<script lang="ts">
  import { login } from '@lib/services/auth'; // I will create this service next
  import { toastStore } from '@lib/stores/toast.svelte';

  let email = $state('');
  let password = $state('');
  let loading = $state(false);
  let error = $state<string | null>(null);

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    loading = true;
    error = null;

    try {
      await login(email, password);
      // For now, redirect to root or update appStore
      window.location.href = '#/';
      window.location.reload(); // Hard reload to clear state for now
    } catch (err: any) {
      error = err.message || 'Access Denied';
      toastStore.add({
        type: 'error',
        title: 'Authentication Failed',
        message: error || undefined
      });
    } finally {
      loading = false;
    }
  }
</script>

<div class="min-h-screen bg-black flex items-center justify-center p-4 font-mono">
  <!-- Grid background -->
  <div class="fixed inset-0 bg-[linear-gradient(rgba(18,16,16,0.1)_1px,transparent_1px),linear-gradient(90deg,rgba(18,16,16,0.1)_1px,transparent_1px)] bg-[size:40px_40px] pointer-events-none opacity-20"></div>

  <div class="relative w-full max-w-md bg-zinc-900 border border-zinc-700 p-10 shadow-[0_0_100px_rgba(0,0,0,1)] animate-fade-in">
    <div class="mb-10">
      <h1 class="text-3xl font-black text-white tracking-tighter uppercase italic">
        OBLIVRA <span class="bg-red-600 px-1 not-italic text-black font-black">ENTERPRISE</span>
      </h1>
      <p class="text-zinc-500 text-[10px] uppercase tracking-[0.4em] font-bold mt-2">Headless Access Portal v1.0.0</p>
    </div>

    <form onsubmit={handleSubmit} class="space-y-6">
      <div class="space-y-2">
        <label class="block text-zinc-400 text-[10px] uppercase tracking-widest font-bold ml-1">Identity (Email)</label>
        <input
          type="email"
          bind:value={email}
          placeholder="operator@oblivra.org"
          required
          class="w-full bg-black border border-zinc-700 p-4 text-white focus:outline-none focus:border-red-600 transition-all duration-300 placeholder:text-zinc-800"
          disabled={loading}
        />
      </div>

      <div class="space-y-2">
        <label class="block text-zinc-400 text-[10px] uppercase tracking-widest font-bold ml-1">Passphrase</label>
        <input
          type="password"
          bind:value={password}
          placeholder="••••••••••••"
          required
          class="w-full bg-black border border-zinc-700 p-4 text-white focus:outline-none focus:border-red-600 transition-all duration-300 placeholder:text-zinc-800"
          disabled={loading}
        />
      </div>

      <button
        type="submit"
        disabled={loading || !email || !password}
        class="w-full h-14 bg-white text-black font-black uppercase tracking-widest hover:bg-red-600 hover:text-white transition-all duration-300 disabled:opacity-20 disabled:grayscale relative overflow-hidden group"
      >
        <span class="relative z-10">{loading ? 'Verifying...' : 'Authorize Session'}</span>
        {#if !loading}
          <div class="absolute inset-0 bg-red-600 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
        {/if}
      </button>

      {#if error}
        <div class="bg-red-900/20 border border-red-900/50 p-4 text-red-500 text-[10px] font-bold uppercase text-center">
          Access Denied: {error}
        </div>
      {/if}
    </form>

    <div class="mt-12 flex flex-col gap-4">
      <button class="w-full border border-zinc-800 text-zinc-600 text-[10px] uppercase tracking-widest font-bold py-3 hover:border-zinc-500 hover:text-zinc-300 transition-all">
        Single Sign-On (OIDC)
      </button>
      <button class="w-full border border-zinc-800 text-zinc-600 text-[10px] uppercase tracking-widest font-bold py-3 hover:border-zinc-500 hover:text-zinc-300 transition-all">
        Federated Identity (SAML)
      </button>
    </div>

    <div class="mt-10 text-[9px] text-zinc-700 text-center uppercase tracking-[0.3em] font-medium leading-loose">
      Sovereign-Grade Encryption Active<br />
      Attestation Level: <span class="text-green-900/50">PLATINUM-ROOT</span>
    </div>
  </div>
</div>

// frontend-web/src/pages/Login.tsx
import { createSignal } from 'solid-js';
import { login } from '../services/auth';

export default function Login() {
  const [email, setEmail] = createSignal('');
  const [password, setPassword] = createSignal('');
  const [error, setError] = createSignal('');
  const [loading, setLoading] = createSignal(false);

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      await login(email(), password());
      window.location.href = '/';
    } catch (err: any) {
      setError(err.message || 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="min-h-screen bg-black flex items-center justify-center p-4">
      <div class="w-full max-w-md bg-zinc-900 border border-zinc-700 p-8 font-mono shadow-[0_0_50px_rgba(0,0,0,0.5)]">
        <div class="mb-8 border-b border-zinc-700 pb-4">
          <h1 class="text-2xl font-black text-white tracking-tighter uppercase italic">
            OBLIVRA <span class="bg-red-600 px-1 not-italic text-black">ENTERPRISE</span>
          </h1>
          <p class="text-zinc-500 text-xs mt-1 uppercase tracking-widest">Headless Access Portal v1.0.0-MVP</p>
        </div>

        <form onSubmit={handleSubmit} class="space-y-6">
          <div>
            <label class="block text-zinc-400 text-xs uppercase mb-2 tracking-widest font-bold">Identity (Email)</label>
            <input
              type="email"
              value={email()}
              onInput={(e) => setEmail(e.currentTarget.value)}
              class="w-full bg-black border border-zinc-700 p-3 text-white focus:outline-none focus:border-red-600 transition-colors"
              placeholder="operator@oblivra.org"
              required
            />
          </div>

          <div>
            <label class="block text-zinc-400 text-xs uppercase mb-2 tracking-widest font-bold">Passphrase</label>
            <input
              type="password"
              value={password()}
              onInput={(e) => setPassword(e.currentTarget.value)}
              class="w-full bg-black border border-zinc-700 p-3 text-white focus:outline-none focus:border-red-600 transition-colors"
              placeholder="••••••••••••"
              required
            />
          </div>

          {error() && (
            <div class="bg-red-900/30 border border-red-800 p-3 text-red-500 text-xs uppercase font-bold text-center">
              ACCESS DENIED: {error()}
            </div>
          )}

          <button
            type="submit"
            disabled={loading()}
            class="w-full bg-white text-black font-black uppercase py-4 hover:bg-red-600 hover:text-white transition-all disabled:opacity-50 disabled:cursor-not-allowed group relative overflow-hidden"
          >
            <span class={loading() ? 'opacity-0' : 'relative z-10'}>Authorize Session</span>
            {loading() && (
              <div class="absolute inset-0 flex items-center justify-center">
                <div class="w-5 h-5 border-2 border-black border-t-transparent rounded-full animate-spin"></div>
              </div>
            )}
          </button>
        </form>

        <div class="mt-8 pt-6 border-t border-zinc-800 flex flex-col gap-4">
          <button 
            onClick={() => window.location.href = '/api/v1/auth/oidc/login'}
            class="w-full border border-zinc-700 text-zinc-500 text-xs uppercase font-bold py-2 hover:border-zinc-500 hover:text-zinc-300 transition-all"
          >
            Single Sign-On (OIDC)
          </button>
          <button 
            onClick={() => window.location.href = '/api/v1/auth/saml/login'}
            class="w-full border border-zinc-700 text-zinc-500 text-xs uppercase font-bold py-2 hover:border-zinc-500 hover:text-zinc-300 transition-all"
          >
            Federated Identity (SAML)
          </button>
        </div>
        
        <div class="mt-6 text-[10px] text-zinc-600 text-center uppercase tracking-[0.2em] font-medium leading-relaxed">
          Sovereign-Grade Encryption Active<br />
          Hardware Root-of-Trust Attestation: <span class="text-green-900">VERIFIED</span>
        </div>
      </div>
    </div>
  );
}
