// frontend-web/src/pages/Login.tsx
import { createSignal } from 'solid-js';
import { login } from '../services/auth';

export default function Login() {
  const [email, setEmail] = createSignal('');
  const [password, setPassword] = createSignal('');
  const [error, setError] = createSignal('');
  const [loading, setLoading] = createSignal(false);

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      await login(email(), password());
      window.location.href = '/';
    } catch (err: any) {
      setError(err.message || 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="min-h-screen bg-black flex items-center justify-center p-4">
      <div class="w-full max-w-md bg-zinc-900 border border-zinc-700 p-8 font-mono shadow-[0_0_50px_rgba(0,0,0,0.5)]">
        <div class="mb-8 border-b border-zinc-700 pb-4">
          <h1 class="text-2xl font-black text-white tracking-tighter uppercase italic">
            OBLIVRA <span class="bg-red-600 px-1 not-italic text-black">ENTERPRISE</span>
          </h1>
          <p class="text-zinc-500 text-xs mt-1 uppercase tracking-widest">Headless Access Portal v1.0.0-MVP</p>
        </div>

        <form onSubmit={handleSubmit} class="space-y-6">
          <div>
            <label class="block text-zinc-400 text-xs uppercase mb-2 tracking-widest font-bold">Identity (Email)</label>
            <input
              type="email"
              value={email()}
              onInput={(e) => setEmail(e.currentTarget.value)}
              class="w-full bg-black border border-zinc-700 p-3 text-white focus:outline-none focus:border-red-600 transition-colors"
              placeholder="operator@oblivra.org"
              required
            />
          </div>

          <div>
            <label class="block text-zinc-400 text-xs uppercase mb-2 tracking-widest font-bold">Passphrase</label>
            <input
              type="password"
              value={password()}
              onInput={(e) => setPassword(e.currentTarget.value)}
              class="w-full bg-black border border-zinc-700 p-3 text-white focus:outline-none focus:border-red-600 transition-colors"
              placeholder="••••••••••••"
              required
            />
          </div>

          {error() && (
            <div class="bg-red-900/30 border border-red-800 p-3 text-red-500 text-xs uppercase font-bold text-center">
              ACCESS DENIED: {error()}
            </div>
          )}

          <button
            type="submit"
            disabled={loading()}
            class="w-full bg-white text-black font-black uppercase py-4 hover:bg-red-600 hover:text-white transition-all disabled:opacity-50 disabled:cursor-not-allowed group relative overflow-hidden"
          >
            <span class={loading() ? 'opacity-0' : 'relative z-10'}>Authorize Session</span>
            {loading() && (
              <div class="absolute inset-0 flex items-center justify-center">
                <div class="w-5 h-5 border-2 border-black border-t-transparent rounded-full animate-spin"></div>
              </div>
            )}
          </button>
        </form>

        <div class="mt-8 pt-6 border-t border-zinc-800 flex flex-col gap-4">
          <button 
            onClick={() => window.location.href = '/api/v1/auth/oidc/login'}
            class="w-full border border-zinc-700 text-zinc-500 text-xs uppercase font-bold py-2 hover:border-zinc-500 hover:text-zinc-300 transition-all"
          >
            Single Sign-On (OIDC)
          </button>
          <button 
            onClick={() => window.location.href = '/api/v1/auth/saml/login'}
            class="w-full border border-zinc-700 text-zinc-500 text-xs uppercase font-bold py-2 hover:border-zinc-500 hover:text-zinc-300 transition-all"
          >
            Federated Identity (SAML)
          </button>
        </div>
        
        <div class="mt-6 text-[10px] text-zinc-600 text-center uppercase tracking-[0.2em] font-medium leading-relaxed">
          Sovereign-Grade Encryption Active<br />
          Hardware Root-of-Trust Attestation: <span class="text-green-900">VERIFIED</span>
        </div>
      </div>
    </div>
  );
}

// frontend-web/src/pages/Login.svelte
<!-- OBLIVRA Web — Login (Svelte 5) -->
<script lang="ts">
  import { login } from '../services/auth';
  import { push } from '../core/router.svelte';
  import { Button, Spinner } from '@components/ui';
  import { Shield, Lock, Key, Globe, ShieldCheck } from 'lucide-svelte';

  let email    = $state('');
  let password = $state('');
  let error    = $state('');
  let loading  = $state(false);

  async function handleSubmit(e: Event) {
    e.preventDefault();
    error = '';
    loading = true;
    try {
      await login(email, password);
      push('/');
    } catch (err: any) {
      error = err.message || 'Login failed';
    } finally {
      loading = false;
    }
  }
</script>

<div class="min-h-screen bg-surface-0 flex items-center justify-center p-6 font-mono selection:bg-accent-primary selection:text-black relative overflow-hidden">
  <!-- Dynamic Background Shards -->
  <div class="absolute inset-0 overflow-hidden pointer-events-none opacity-20">
    <div class="absolute -top-1/4 -left-1/4 w-full h-full bg-accent-primary/10 rounded-full blur-[120px]"></div>
    <div class="absolute -bottom-1/4 -right-1/4 w-full h-full bg-accent-primary/5 rounded-full blur-[120px]"></div>
  </div>

  <div class="w-full max-w-md bg-surface-1 border border-border-primary p-10 shadow-premium relative z-10 backdrop-blur-sm">
    <div class="text-center mb-10">
      <div class="inline-flex p-4 bg-surface-2 border border-border-primary rounded-sm mb-6 relative group">
        <Shield size={32} class="text-accent-primary group-hover:scale-110 transition-transform duration-500" />
        <div class="absolute inset-0 bg-accent-primary/20 blur-xl opacity-0 group-hover:opacity-100 transition-opacity"></div>
      </div>
      <h1 class="text-3xl font-black italic uppercase tracking-tighter text-text-heading">
        OBLIVRA <span class="bg-accent-primary text-black px-2 not-italic">ORBIT</span>
      </h1>
      <p class="text-[10px] font-mono text-text-muted uppercase tracking-[0.3em] mt-2">Sovereign Access Substrate v1.2.0</p>
    </div>

    <form onsubmit={handleSubmit} class="space-y-6">
      <div class="space-y-2">
        <label for="identity" class="text-[10px] font-black text-text-muted uppercase tracking-widest flex items-center gap-2">
          <Globe size={12} class="text-accent-primary/60" />
          Operator Identity
        </label>
        <div class="relative">
          <input 
            id="identity" 
            type="email" 
            bind:value={email} 
            class="w-full bg-surface-2 border border-border-primary p-4 text-sm text-text-secondary outline-none focus:border-accent-primary transition-colors pl-12" 
            placeholder="operator@oblivra.org" 
            required 
          />
          <div class="absolute left-4 top-1/2 -translate-y-1/2 text-text-muted">
            @
          </div>
        </div>
      </div>

      <div class="space-y-2">
        <label for="passphrase" class="text-[10px] font-black text-text-muted uppercase tracking-widest flex items-center gap-2">
          <Lock size={12} class="text-accent-primary/60" />
          Neural Passphrase
        </label>
        <div class="relative">
          <input 
            id="passphrase" 
            type="password" 
            bind:value={password} 
            class="w-full bg-surface-2 border border-border-primary p-4 text-sm text-text-secondary outline-none focus:border-accent-primary transition-colors pl-12" 
            placeholder="••••••••••••" 
            required 
          />
          <div class="absolute left-4 top-1/2 -translate-y-1/2 text-text-muted">
            <Key size={14} />
          </div>
        </div>
      </div>

      {#if error}
        <div class="p-4 bg-alert-critical/10 border border-alert-critical text-alert-critical text-[10px] font-black uppercase tracking-widest text-center animate-pulse">
          ACCESS_DENIED: {error}
        </div>
      {/if}

      <Button type="submit" disabled={loading} variant="primary" class="w-full py-6 font-black italic tracking-tighter text-lg relative overflow-hidden group">
        {#if loading}
          <Spinner />
        {:else}
          <span class="relative z-10">INITIALIZE_SESSION</span>
          <div class="absolute inset-0 bg-white/10 translate-y-full group-hover:translate-y-0 transition-transform"></div>
        {/if}
      </Button>
    </form>

    <div class="mt-10 pt-8 border-t border-border-primary space-y-3">
      <button 
        onclick={() => window.location.href='/api/v1/auth/oidc/login'} 
        class="w-full border border-border-subtle p-3 text-[10px] font-bold text-text-muted uppercase tracking-widest hover:border-text-muted hover:text-text-secondary transition-all flex items-center justify-center gap-2"
      >
        SINGLE SIGN-ON (OIDC)
      </button>
      <button 
        onclick={() => window.location.href='/api/v1/auth/saml/login'} 
        class="w-full border border-border-subtle p-3 text-[10px] font-bold text-text-muted uppercase tracking-widest hover:border-text-muted hover:text-text-secondary transition-all flex items-center justify-center gap-2"
      >
        FEDERATED IDENTITY (SAML)
      </button>
    </div>

    <div class="mt-10 text-center space-y-2">
      <div class="flex items-center justify-center gap-2 text-[9px] font-mono text-text-muted uppercase tracking-[0.2em]">
        <ShieldCheck size={12} class="text-status-online" />
        Root-of-Trust Attestation: <span class="text-status-online font-black">VERIFIED</span>
      </div>
      <p class="text-[8px] font-mono text-text-muted/40 uppercase tracking-widest">
        End-to-End Encryption Protocol: RSA_4096_L7_AWARE
      </p>
    </div>
  </div>
</div>
