// frontend-web/src/pages/LookupManager.tsx
/**
 * LookupManager.tsx — Lookup Table Management (Hybrid — Phase 1.3)
 *
 * Manage CSV/JSON lookup tables used by the OQL enrichment pipeline.
 * Supports Exact, CIDR, Wildcard, and Regex match strategies.
 * Connects to /api/v1/lookups/*.
 */

import { createSignal, createResource, For, Show } from 'solid-js';
import { request } from '../services/api';

// ── Types ─────────────────────────────────────────────────────────────────────
interface LookupTable {
  name: string;
  match_type: 'exact' | 'cidr' | 'wildcard' | 'regex';
  fields: string[];
  rows?: Record<string, string>[];
}

interface LookupResponse { tables: LookupTable[]; }

type MatchType = 'exact' | 'cidr' | 'wildcard' | 'regex';

// ── Helpers ───────────────────────────────────────────────────────────────────
const MT_COLOR: Record<MatchType, string> = {
  exact:    '#00ffe7',
  cidr:     '#00ff88',
  wildcard: '#ffaa00',
  regex:    '#ff6600',
};

// ── Component ─────────────────────────────────────────────────────────────────
export default function LookupManager() {
  const [tables, { refetch }] = createResource<LookupTable[]>(async () => {
    const res = await request<LookupResponse>('/lookups');
    return res.tables ?? [];
  });

  const [selected, setSelected] = createSignal<LookupTable | null>(null);
  const [queryTable, setQueryTable] = createSignal('');
  const [queryKey, setQueryKey]     = createSignal('');
  const [queryResult, setQueryResult] = createSignal<{match: boolean; data: Record<string,string>|null}|null>(null);

  // Upload state
  const [uploadName,  setUploadName]  = createSignal('');
  const [uploadMT,    setUploadMT]    = createSignal<MatchType>('exact');
  const [uploadFmt,   setUploadFmt]   = createSignal<'csv'|'json'>('csv');
  const [uploadFile,  setUploadFile]  = createSignal<File|null>(null);
  const [uploadMsg,   setUploadMsg]   = createSignal('');

  async function loadTable(name: string) {
    try {
      const t = await request<LookupTable>(`/lookups/${name}`);
      setSelected(t);
    } catch { /* ignore */ }
  }

  async function deleteTable(name: string) {
    try {
      await request(`/lookups/${name}`, { method: 'DELETE' });
      refetch();
      if (selected()?.name === name) setSelected(null);
    } catch(e: any) {
      alert(e.message);
    }
  }

  async function uploadTable() {
    const file = uploadFile();
    if (!file || !uploadName()) return;
    const form = new FormData();
    form.append('name', uploadName());
    form.append('match_type', uploadMT());
    form.append('format', uploadFmt());
    form.append('file', file);
    try {
      await fetch('/api/v1/lookups/upload', {
        method: 'POST',
        headers: { 'X-API-Key': localStorage.getItem('oblivra_token') ?? '' },
        body: form,
      });
      setUploadMsg(`✓ Table "${uploadName()}" uploaded successfully.`);
      refetch();
    } catch(e: any) {
      setUploadMsg(`✗ Upload failed: ${e.message}`);
    }
  }

  async function runQuery() {
    const t = queryTable(), k = queryKey();
    if (!t || !k) return;
    try {
      const res = await request<{match:boolean; data: Record<string,string>|null}>(
        `/lookups/query?table=${encodeURIComponent(t)}&key=${encodeURIComponent(k)}`
      );
      setQueryResult(res);
    } catch { setQueryResult({ match: false, data: null }); }
  }

  return (
    <div style="padding:2rem; color:#c8d8d8; font-family:'JetBrains Mono',monospace; min-height:100vh; background:#080f12;">
      {/* Header */}
      <div style="margin-bottom:1.5rem;">
        <h1 style="font-size:1.4rem; letter-spacing:0.15em; margin:0; color:#00ffe7;">⬡ LOOKUP TABLES</h1>
        <p style="margin:0.25rem 0 0; font-size:0.75rem; color:#607070;">
          Enrichment lookup tables — Exact · CIDR · Wildcard · Regex
        </p>
      </div>

      <div style="display:grid; grid-template-columns:300px 1fr; gap:1.5rem; align-items:start;">
        {/* Left — Table list */}
        <div>
          <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; overflow:hidden; margin-bottom:1rem;">
            <div style="padding:0.65rem 1rem; background:#0a1318; border-bottom:1px solid #1e3040; display:flex; justify-content:space-between; align-items:center;">
              <span style="font-size:0.72rem; color:#607070; letter-spacing:0.12em;">TABLES ({tables()?.length ?? 0})</span>
              <button onClick={() => refetch()} style="background:none; border:none; color:#607070; cursor:pointer; font-size:0.75rem;">↻</button>
            </div>
            <Show when={!tables.loading} fallback={<div style="padding:1rem; color:#607070; font-size:0.76rem;">Loading…</div>}>
              <For each={tables()} fallback={<div style="padding:1rem; color:#607070; font-size:0.76rem;">No tables found.</div>}>
                {(t) => (
                  <div
                    onClick={() => loadTable(t.name)}
                    style={`padding:0.7rem 1rem; cursor:pointer; border-bottom:1px solid #0a1318; border-left:3px solid ${selected()?.name===t.name ? '#00ffe7' : 'transparent'}; background:${selected()?.name===t.name ? '#111f28' : 'transparent'};`}
                  >
                    <div style="display:flex; justify-content:space-between; align-items:center;">
                      <span style="font-size:0.8rem; color:#c8d8d8;">{t.name}</span>
                      <button
                        onClick={e => { e.stopPropagation(); deleteTable(t.name); }}
                        style="background:none; border:none; color:#607070; cursor:pointer; font-size:0.72rem;"
                        title="Delete table"
                      >✕</button>
                    </div>
                    <span style={`font-size:0.65rem; color:${MT_COLOR[t.match_type]}; letter-spacing:0.1em;`}>{t.match_type.toUpperCase()}</span>
                  </div>
                )}
              </For>
            </Show>
          </div>

          {/* Quick Query */}
          <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:1rem;">
            <div style="font-size:0.7rem; color:#607070; letter-spacing:0.12em; margin-bottom:0.75rem;">QUICK QUERY</div>
            <select
              value={queryTable()} onChange={e => setQueryTable(e.currentTarget.value)}
              style="width:100%; background:#0a1318; border:1px solid #1e3040; color:#c8d8d8; padding:0.4rem; border-radius:3px; font-size:0.76rem; margin-bottom:0.5rem;"
            >
              <option value="">Select table…</option>
              <For each={tables()}>
                {(t) => <option value={t.name}>{t.name}</option>}
              </For>
            </select>
            <input
              type="text" placeholder="Key to look up…"
              value={queryKey()} onInput={e => setQueryKey(e.currentTarget.value)}
              onKeyDown={e => e.key === 'Enter' && runQuery()}
              style="width:100%; background:#0a1318; border:1px solid #1e3040; color:#c8d8d8; padding:0.4rem 0.5rem; border-radius:3px; font-size:0.76rem; margin-bottom:0.5rem; box-sizing:border-box;"
            />
            <button
              onClick={runQuery}
              style="width:100%; background:#00ffe7; color:#080f12; border:none; padding:0.45rem; border-radius:3px; cursor:pointer; font-size:0.75rem; font-weight:700; letter-spacing:0.1em;"
            >LOOKUP</button>
            <Show when={queryResult() !== null}>
              <div style={`margin-top:0.75rem; padding:0.65rem; border-radius:3px; background:${queryResult()?.match ? '#002a1a' : '#2a0d15'}; border:1px solid ${queryResult()?.match ? '#00ff88' : '#ff3355'};`}>
                <div style={`font-size:0.68rem; font-weight:700; color:${queryResult()?.match ? '#00ff88' : '#ff3355'}; margin-bottom:${queryResult()?.match ? '0.5rem' : '0'};`}>
                  {queryResult()?.match ? '● MATCH FOUND' : '○ NO MATCH'}
                </div>
                <Show when={queryResult()?.data}>
                  <For each={Object.entries(queryResult()!.data!)}>
                    {([k, v]) => (
                      <div style="font-size:0.7rem; color:#607070;">
                        <span style="color:#c8d8d8;">{k}</span>: {v}
                      </div>
                    )}
                  </For>
                </Show>
              </div>
            </Show>
          </div>
        </div>

        {/* Right — Table detail or Upload form */}
        <div style="display:flex; flex-direction:column; gap:1.5rem;">
          {/* Upload form */}
          <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:1.25rem;">
            <div style="font-size:0.72rem; color:#607070; letter-spacing:0.12em; margin-bottom:1rem;">UPLOAD NEW TABLE</div>
            <div style="display:grid; grid-template-columns:1fr 1fr 1fr; gap:0.75rem; margin-bottom:0.75rem;">
              <div>
                <div style="font-size:0.65rem; color:#607070; margin-bottom:0.25rem;">TABLE NAME</div>
                <input type="text" value={uploadName()} onInput={e => setUploadName(e.currentTarget.value)}
                  placeholder="my_blocklist"
                  style="width:100%; background:#0a1318; border:1px solid #1e3040; color:#c8d8d8; padding:0.4rem; border-radius:3px; font-size:0.76rem; box-sizing:border-box;" />
              </div>
              <div>
                <div style="font-size:0.65rem; color:#607070; margin-bottom:0.25rem;">MATCH TYPE</div>
                <select value={uploadMT()} onChange={e => setUploadMT(e.currentTarget.value as MatchType)}
                  style="width:100%; background:#0a1318; border:1px solid #1e3040; color:#c8d8d8; padding:0.4rem; border-radius:3px; font-size:0.76rem;">
                  <option value="exact">Exact</option>
                  <option value="cidr">CIDR</option>
                  <option value="wildcard">Wildcard</option>
                  <option value="regex">Regex</option>
                </select>
              </div>
              <div>
                <div style="font-size:0.65rem; color:#607070; margin-bottom:0.25rem;">FORMAT</div>
                <select value={uploadFmt()} onChange={e => setUploadFmt(e.currentTarget.value as 'csv'|'json')}
                  style="width:100%; background:#0a1318; border:1px solid #1e3040; color:#c8d8d8; padding:0.4rem; border-radius:3px; font-size:0.76rem;">
                  <option value="csv">CSV</option>
                  <option value="json">JSON</option>
                </select>
              </div>
            </div>
            <div style="display:flex; gap:0.75rem; align-items:center;">
              <input type="file" accept=".csv,.json"
                onChange={e => setUploadFile(e.currentTarget.files?.[0] ?? null)}
                style="flex:1; background:#0a1318; border:1px solid #1e3040; color:#607070; padding:0.4rem; border-radius:3px; font-size:0.76rem;" />
              <button onClick={uploadTable}
                style="background:#00ffe7; color:#080f12; border:none; padding:0.45rem 1.25rem; border-radius:3px; cursor:pointer; font-size:0.76rem; font-weight:700; letter-spacing:0.1em; white-space:nowrap;">
                UPLOAD
              </button>
            </div>
            <Show when={uploadMsg()}>
              <div style={`margin-top:0.6rem; font-size:0.73rem; color:${uploadMsg().startsWith('✓') ? '#00ff88' : '#ff3355'};`}>{uploadMsg()}</div>
            </Show>
          </div>

          {/* Table viewer */}
          <Show when={selected()}>
            {(t) => (
              <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; overflow:hidden;">
                <div style="padding:0.75rem 1rem; background:#0a1318; border-bottom:1px solid #1e3040; display:flex; justify-content:space-between;">
                  <span style="color:#00ffe7; font-size:0.85rem;">{t().name}</span>
                  <span style={`font-size:0.7rem; color:${MT_COLOR[t().match_type]};`}>{t().match_type.toUpperCase()} · {t().rows?.length ?? 0} rows</span>
                </div>
                <div style="overflow-x:auto; max-height:400px; overflow-y:auto;">
                  <table style="width:100%; border-collapse:collapse; font-size:0.75rem;">
                    <thead>
                      <tr style="border-bottom:1px solid #1e3040;">
                        <For each={t().fields}>
                          {(f) => <th style="padding:0.6rem 0.9rem; text-align:left; color:#607070; letter-spacing:0.1em; font-weight:400;">{f.toUpperCase()}</th>}
                        </For>
                      </tr>
                    </thead>
                    <tbody>
                      <For each={t().rows ?? []}>
                        {(row) => (
                          <tr style="border-bottom:1px solid #0a1318;">
                            <For each={t().fields}>
                              {(f) => <td style="padding:0.55rem 0.9rem; color:#c8d8d8;">{row[f] ?? '—'}</td>}
                            </For>
                          </tr>
                        )}
                      </For>
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </Show>
        </div>
      </div>
    </div>
  );
}

// frontend-web/src/pages/LookupManager.svelte
<!-- OBLIVRA Web — Lookup Manager (Svelte 5) -->
<script lang="ts">
  import { onMount } from 'svelte';
  import { KPI, Badge, Button, DataTable, PageLayout, Spinner, Input } from '@components/ui';
  import { Database, Search, Upload, Trash2, History, Filter, CheckCircle, AlertTriangle, Hash, Network, Zap, FileText } from 'lucide-svelte';
  import { request } from '../services/api';

  // -- Types --
  interface LookupTable {
    name: string;
    match_type: 'exact' | 'cidr' | 'wildcard' | 'regex';
    fields: string[];
    rows?: Record<string, string>[];
  }
  type MatchType = 'exact' | 'cidr' | 'wildcard' | 'regex';

  // -- Constants --
  const MT_STYLE = {
    exact:    { color: 'var(--status-online)',  bg: 'rgba(0,200,100,0.1)', icon: Hash },
    cidr:     { color: 'var(--accent-primary)', bg: 'rgba(0,180,255,0.1)', icon: Network },
    wildcard: { color: 'var(--alert-medium)',   bg: 'rgba(200,140,0,0.1)', icon: Zap },
    regex:    { color: 'var(--alert-critical)', bg: 'rgba(200,44,44,0.1)', icon: Filter },
  };

  // -- State --
  let tables       = $state<LookupTable[]>([]);
  let loading      = $state(true);
  let selected     = $state<LookupTable | null>(null);
  
  // Query state
  let queryTable   = $state('');
  let queryKey     = $state('');
  let queryResult  = $state<{match: boolean; data: Record<string,string>|null} | null>(null);
  let querying     = $state(false);

  // Upload state
  let uploadName   = $state('');
  let uploadMT     = $state<MatchType>('exact');
  let uploadFmt    = $state<'csv'|'json'>('csv');
  let uploadFile   = $state<File | null>(null);
  let uploadMsg    = $state('');
  let uploading    = $state(false);

  // -- Actions --
  async function fetchTables() {
    loading = true;
    try {
      const res = await request<{ tables: LookupTable[] }>('/lookups');
      tables = res.tables ?? [];
    } catch (e) {
      console.error('Lookup fetch failed', e);
    } finally {
      loading = false;
    }
  }

  async function loadTable(name: string) {
    try {
      const t = await request<LookupTable>(`/lookups/${name}`);
      selected = t;
    } catch (e) {
      console.error('Table load failed', e);
    }
  }

  async function deleteTable(name: string) {
    if (!confirm(`Confirm destruction of lookup table: ${name}?`)) return;
    try {
      await request(`/lookups/${name}`, { method: 'DELETE' });
      if (selected?.name === name) selected = null;
      fetchTables();
    } catch(e: any) {
      alert(`ERR: ${e.message}`);
    }
  }

  async function runQuery() {
    if (!queryTable || !queryKey) return;
    querying = true;
    try {
      const res = await request<{match:boolean; data: Record<string,string>|null}>(
        `/lookups/query?table=${encodeURIComponent(queryTable)}&key=${encodeURIComponent(queryKey)}`
      );
      queryResult = res;
    } catch { 
      queryResult = { match: false, data: null }; 
    } finally {
      querying = false;
    }
  }

  async function uploadTable() {
    if (!uploadFile || !uploadName) return;
    uploading = true;
    const form = new FormData();
    form.append('name', uploadName);
    form.append('match_type', uploadMT);
    form.append('format', uploadFmt);
    form.append('file', uploadFile);
    try {
      const token = localStorage.getItem('oblivra_token') ?? '';
      const res = await fetch('/api/v1/lookups/upload', {
        method: 'POST',
        headers: { 'X-API-Key': token },
        body: form,
      });
      if (!res.ok) throw new Error(await res.text());
      uploadMsg = `✓ Table "${uploadName}" synchronized.`;
      uploadName = '';
      uploadFile = null;
      fetchTables();
    } catch(e: any) {
      uploadMsg = `✗ Synchronization failed: ${e.message}`;
    } finally {
      uploading = false;
      setTimeout(() => uploadMsg = '', 5000);
    }
  }

  onMount(() => {
    fetchTables();
  });
</script>

<PageLayout title="Lookup Tables" subtitle="High-density enrichment substrate: Manage CSV/JSON mappings for OQL ingestion pipelines">
  {#snippet toolbar()}
    <div class="flex items-center gap-2">
      <Button variant="secondary" size="sm" onclick={fetchTables}>
        <History size={14} class="mr-2" />
        RE-SYNC
      </Button>
      <Button variant="primary" size="sm" icon={Upload}>MASS UPLOAD</Button>
    </div>
  {/snippet}

  <div class="flex flex-col h-full gap-0 -m-6 overflow-hidden">
    <!-- METRIC STRIP -->
    <div class="grid grid-cols-4 gap-px bg-border-primary border-b border-border-primary shrink-0">
        <div class="bg-surface-2 p-3">
            <div class="text-[8px] font-mono text-text-muted uppercase tracking-widest mb-1">Total Tables</div>
            <div class="text-xl font-mono font-bold text-text-heading">{tables.length}</div>
            <div class="text-[9px] text-text-muted mt-1 italic">Active mapping shards</div>
        </div>
        <div class="bg-surface-2 p-3">
            <div class="text-[8px] font-mono text-text-muted uppercase tracking-widest mb-1">Global Strategy</div>
            <div class="text-xl font-mono font-bold text-accent-primary">HYBRID</div>
            <div class="text-[9px] text-status-online mt-1 uppercase tracking-tighter">L7_MATCH_ACTIVE</div>
        </div>
        <div class="bg-surface-2 p-3">
            <div class="text-[8px] font-mono text-text-muted uppercase tracking-widest mb-1">Query Latency</div>
            <div class="text-xl font-mono font-bold text-status-online">&lt; 0.2ms</div>
            <div class="text-[9px] text-text-muted mt-1 italic">In-memory hot path</div>
        </div>
        <div class="bg-surface-2 p-3">
            <div class="text-[8px] font-mono text-text-muted uppercase tracking-widest mb-1">Enrichment State</div>
            <div class="text-xl font-mono font-bold text-text-heading">ACTIVE</div>
            <div class="text-[9px] text-status-online mt-1 uppercase tracking-tighter">✓ Substrate Healthy</div>
        </div>
    </div>

    <!-- MAIN BODY -->
    <div class="flex-1 flex min-h-0 bg-surface-0 overflow-hidden">
        <!-- LEFT SIDEBAR: TABLES & QUERY -->
        <div class="w-80 border-r border-border-primary flex flex-col shrink-0 bg-surface-1 overflow-hidden">
           <!-- Table List -->
           <div class="flex-1 flex flex-col min-h-0">
              <div class="p-3 bg-surface-2 border-b border-border-primary flex justify-between items-center shrink-0">
                 <span class="text-[9px] font-mono font-bold text-text-muted uppercase tracking-widest">Available Shards</span>
                 <Badge variant="secondary" size="xs">{tables.length}</Badge>
              </div>
              <div class="flex-1 overflow-auto p-1 space-y-1">
                 {#if loading}
                    <div class="py-10 flex justify-center"><Spinner size="sm" /></div>
                 {:else}
                    {#each tables as t}
                       {@const Style = MT_STYLE[t.match_type]}
                       <div 
                         role="button"
                         tabindex="0"
                         class="w-full text-left p-3 rounded-sm border transition-all group flex flex-col gap-1 cursor-pointer
                           {selected?.name === t.name ? 'bg-surface-2 border-accent-primary shadow-premium' : 'bg-transparent border-transparent hover:bg-surface-2 hover:border-border-subtle'}"
                         onclick={() => loadTable(t.name)}
                         onkeydown={(e) => e.key === 'Enter' && loadTable(t.name)}
                       >
                          <div class="flex justify-between items-start">
                             <span class="text-[11px] font-bold text-text-heading uppercase tracking-tighter">{t.name}</span>
                             <button type="button" class="opacity-0 group-hover:opacity-100 text-text-muted hover:text-alert-critical transition-opacity" 
                               onclick={(e) => { e.stopPropagation(); deleteTable(t.name); }}>
                                <Trash2 size={12} />
                             </button>
                          </div>
                          <div class="flex items-center gap-2">
                             <Style.icon size={10} style="color: {Style.color}" />
                             <span class="text-[8px] font-mono font-black uppercase tracking-widest italic" style="color: {Style.color}">{t.match_type}</span>
                          </div>
                       </div>
                    {/each}
                 {/if}
              </div>
           </div>

           <!-- Quick Query -->
           <div class="bg-surface-2 border-t border-border-primary p-4 space-y-4">
              <div class="flex items-center gap-2">
                 <Search size={14} class="text-accent-primary" />
                 <span class="text-[9px] font-mono font-bold text-text-heading uppercase tracking-widest">Substrate Query</span>
              </div>
              
              <div class="space-y-3">
                 <select bind:value={queryTable} class="w-full bg-surface-1 border border-border-subtle rounded-sm px-2 py-1.5 text-xs font-mono text-text-secondary focus:border-accent-primary focus:outline-none">
                    <option value="">SELECT TABLE...</option>
                    {#each tables as t}
                       <option value={t.name}>{t.name.toUpperCase()}</option>
                    {/each}
                 </select>
                 <div class="flex gap-2">
                    <input 
                      type="text" 
                      placeholder="KEY_TO_LOOKUP" 
                      class="flex-1 bg-surface-1 border border-border-subtle rounded-sm px-2 py-1.5 text-xs font-mono text-text-secondary focus:border-accent-primary focus:outline-none"
                      bind:value={queryKey}
                      onkeydown={(e) => e.key === 'Enter' && runQuery()}
                    />
                    <Button variant="primary" size="sm" class="font-black italic" onclick={runQuery} loading={querying}>GO</Button>
                 </div>
              </div>

              {#if queryResult}
                 <div class="p-3 rounded-sm border animate-in fade-in duration-300
                   {queryResult.match ? 'bg-status-online/5 border-status-online/40' : 'bg-alert-critical/5 border-alert-critical/40'}"
                 >
                    <div class="flex items-center gap-2 mb-2">
                       <div class="w-1.5 h-1.5 rounded-full {queryResult.match ? 'bg-status-online' : 'bg-alert-critical'}"></div>
                       <span class="text-[9px] font-black uppercase tracking-widest italic {queryResult.match ? 'text-status-online' : 'text-alert-critical'}">
                          {queryResult.match ? 'MATCH_FOUND' : 'NO_MATCH'}
                       </span>
                    </div>
                    {#if queryResult.data}
                       <div class="space-y-1 overflow-auto max-h-32 pr-2">
                          {#each Object.entries(queryResult.data) as [k, v]}
                             <div class="flex flex-col">
                                <span class="text-[8px] font-mono text-text-muted uppercase">{k}</span>
                                <span class="text-[10px] text-text-secondary break-all">{v}</span>
                             </div>
                          {/each}
                       </div>
                    {/if}
                 </div>
              {/if}
           </div>
        </div>

        <!-- RIGHT: TABLE DETAIL & UPLOAD -->
        <div class="flex-1 flex flex-col min-w-0 bg-surface-0 overflow-hidden">
           <!-- UPLOAD AREA -->
           <div class="bg-surface-1 border-b border-border-primary p-5 space-y-4 shrink-0">
              <div class="flex items-center justify-between">
                 <div class="flex items-center gap-2">
                    <Upload size={14} class="text-accent-primary" />
                    <span class="text-[10px] font-black text-text-heading uppercase tracking-widest">Synchronize New Shard</span>
                 </div>
                 {#if uploadMsg}
                    <div class="text-[9px] font-mono font-bold {uploadMsg.startsWith('✓') ? 'text-status-online' : 'text-alert-critical'} animate-pulse">
                       {uploadMsg}
                    </div>
                 {/if}
              </div>

              <div class="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
                 <div class="space-y-1.5">
                    <span class="text-[8px] font-mono text-text-muted uppercase tracking-widest">Table Name</span>
                    <input bind:value={uploadName} class="w-full bg-surface-2 border border-border-subtle rounded-sm px-3 py-1.5 text-xs font-mono text-text-secondary focus:border-accent-primary focus:outline-none" placeholder="threat_actors_v2" />
                 </div>
                 <div class="space-y-1.5">
                    <span class="text-[8px] font-mono text-text-muted uppercase tracking-widest">Match Strategy</span>
                    <select bind:value={uploadMT} class="w-full bg-surface-2 border border-border-subtle rounded-sm px-3 py-1.5 text-xs font-mono text-text-secondary focus:border-accent-primary focus:outline-none">
                       <option value="exact">EXACT</option>
                       <option value="cidr">CIDR</option>
                       <option value="wildcard">WILDCARD</option>
                       <option value="regex">REGEX</option>
                    </select>
                 </div>
                 <div class="space-y-1.5">
                    <span class="text-[8px] font-mono text-text-muted uppercase tracking-widest">Source Shard</span>
                    <div class="flex gap-2">
                       <label class="flex-1 cursor-pointer bg-surface-2 border border-border-subtle rounded-sm px-3 py-1.5 text-xs font-mono text-text-muted hover:border-accent-primary transition-colors truncate">
                          <input type="file" class="hidden" onchange={(e) => uploadFile = e.currentTarget.files?.[0] ?? null} accept=".csv,.json" />
                          {uploadFile ? uploadFile.name : 'CHOOSE FILE (.CSV/JSON)'}
                       </label>
                    </div>
                 </div>
                 <Button variant="primary" class="w-full font-black italic tracking-tighter" onclick={uploadTable} loading={uploading} disabled={!uploadFile || !uploadName}>COMMIT SHARD</Button>
              </div>
           </div>

           <!-- TABLE VIEWER -->
           <div class="flex-1 flex flex-col min-h-0">
              {#if selected}
                 <div class="p-3 bg-surface-2 border-b border-border-primary flex justify-between items-center shrink-0">
                    <div class="flex items-center gap-3">
                       <div class="p-1 bg-accent-primary/10 rounded-xs">
                          <FileText size={14} class="text-accent-primary" />
                       </div>
                       <div class="flex flex-col">
                          <span class="text-[11px] font-black text-text-heading uppercase tracking-tighter">{selected.name}</span>
                          <span class="text-[8px] font-mono text-text-muted uppercase tracking-widest opacity-60">Strategy: {selected.match_type} // Total Rows: {selected.rows?.length ?? 0}</span>
                       </div>
                    </div>
                    <div class="flex items-center gap-2">
                       <Button variant="ghost" size="xs" icon={Filter}>FIELD FILTERS</Button>
                       <Button variant="ghost" size="xs" icon={Trash2} class="text-alert-critical hover:bg-alert-critical/10" onclick={() => deleteTable(selected!.name)}>PURGE</Button>
                    </div>
                 </div>
                 <div class="flex-1 overflow-auto">
                    <DataTable 
                       data={selected.rows ?? []} 
                       columns={selected.fields.map(f => ({ key: f, label: f.toUpperCase() }))} 
                       compact
                    >
                       {#snippet cell({ column, row })}
                          <span class="text-[10px] font-mono text-text-secondary truncate block max-w-xs">{row[column.key] ?? '—'}</span>
                       {/snippet}
                    </DataTable>
                 </div>
              {:else}
                 <div class="flex-1 flex flex-col items-center justify-center gap-4 text-text-muted opacity-30">
                    <Database size={48} />
                    <p class="text-[10px] font-mono uppercase tracking-widest">Select a lookup shard to inspect telemetry</p>
                 </div>
              {/if}
           </div>
        </div>
    </div>

    <!-- STATUS BAR -->
    <div class="bg-surface-2 border-t border-border-primary px-3 py-1 flex items-center gap-4 text-[8px] font-mono text-text-muted shrink-0 uppercase tracking-widest">
        <div class="flex items-center gap-1.5">
            <div class="w-1 h-1 rounded-full bg-status-online"></div>
            <span>LOOKUP_PLANE:</span>
            <span class="text-status-online font-bold italic">ENGAGED</span>
        </div>
        <span class="text-border-primary opacity-30">|</span>
        <div class="flex items-center gap-1.5">
            <span>SYNC_LATENCY:</span>
            <span class="text-status-online font-bold italic">0.02ms</span>
        </div>
        <span class="text-border-primary opacity-30">|</span>
        <div class="flex items-center gap-1.5">
            <span>OQL_ENRICHMENT:</span>
            <span class="text-accent-primary font-bold italic">OPTIMIZED</span>
        </div>
        <div class="ml-auto opacity-40">OBLIVRA_LOOKUP_v2.4.1</div>
    </div>
  </div>
</PageLayout>

<style>
  :global(.flex-1::-webkit-scrollbar) {
    width: 6px;
    height: 6px;
  }
  :global(.flex-1::-webkit-scrollbar-track) {
    background: var(--surface-0);
  }
  :global(.flex-1::-webkit-scrollbar-thumb) {
    background: var(--border-primary);
    border-radius: 3px;
  }
</style>
