// frontend-web/src/pages/PlaybookBuilder.tsx
/**
 * PlaybookBuilder.tsx — Visual Playbook Automation Builder (Web Only — Phase 8)
 *
 * Drag-and-reorder step builder for SOAR playbooks.
 * Connects to /api/v1/playbooks/*.
 */

import { createSignal, createResource, For, Show } from 'solid-js';
import { request } from '../services/api';

interface PlaybookStep {
    id: string;
    action: string;
    params: Record<string, string>;
    enabled: boolean;
}

interface SavedPlaybook {
    id: string;
    name: string;
    steps: PlaybookStep[];
    created_at: string;
    last_run?: string;
}

const STEP_ICONS: Record<string, string> = {
    isolate_host: '🔒', lock_account: '👤', kill_process: '⚡',
    collect_logs: '📋', snapshot_memory: '💾', notify_team: '📢',
    run_scan: '🔍', block_ip: '🚫', webhook: '🌐', default: '⚙️',
};

async function fetchAvailableActions(): Promise<string[]> {
    try {
        const r = await request<{ actions: string[] }>('/playbooks/actions');
        return r.actions ?? [];
    } catch { return ['isolate_host', 'lock_account', 'kill_process', 'collect_logs', 'notify_team', 'block_ip', 'webhook']; }
}

async function fetchPlaybooks(): Promise<SavedPlaybook[]> {
    try {
        const r = await request<{ playbooks: SavedPlaybook[] }>('/playbooks');
        return r.playbooks ?? [];
    } catch { return []; }
}

export default function PlaybookBuilder() {
    const [availableActions] = createResource(fetchAvailableActions);
    const [savedPlaybooks, { refetch }] = createResource(fetchPlaybooks);

    const [steps, setSteps] = createSignal<PlaybookStep[]>([]);
    const [name, setName] = createSignal('');
    const [targetIncident, setTargetIncident] = createSignal('');
    const [running, setRunning] = createSignal(false);
    const [saving, setSaving] = createSignal(false);
    const [result, setResult] = createSignal('');

    const addStep = (action: string) => setSteps(s => [...s, {
        id: `step-${Date.now()}`,
        action, params: {}, enabled: true,
    }]);

    const removeStep = (id: string) => setSteps(s => s.filter(x => x.id !== id));
    const toggleStep = (id: string) => setSteps(s => s.map(x => x.id === id ? { ...x, enabled: !x.enabled } : x));

    const moveUp = (idx: number) => { if (idx === 0) return; setSteps(s => { const a = [...s]; [a[idx-1], a[idx]] = [a[idx], a[idx-1]]; return a; }); };
    const moveDown = (idx: number) => { setSteps(s => { if (idx >= s.length - 1) return s; const a = [...s]; [a[idx], a[idx+1]] = [a[idx+1], a[idx]]; return a; }); };

    const savePlaybook = async () => {
        if (!name().trim() || steps().length === 0) { setResult('✗ Name and at least one step required.'); return; }
        setSaving(true);
        try {
            await request('/playbooks', { method: 'POST', body: JSON.stringify({ name: name(), steps: steps() }) });
            setResult('✓ Playbook saved.');
            refetch();
        } catch (e: any) { setResult('✗ ' + (e?.message ?? e)); }
        setSaving(false);
        setTimeout(() => setResult(''), 4000);
    };

    const executePlaybook = async () => {
        if (!targetIncident().trim()) { setResult('✗ Enter a target incident ID.'); return; }
        if (steps().length === 0) { setResult('✗ Add at least one step.'); return; }
        setRunning(true);
        try {
            await request('/playbooks/run', { method: 'POST', body: JSON.stringify({
                name: name() || 'adhoc-playbook',
                steps: steps().filter(s => s.enabled),
                incident_id: targetIncident(),
            })});
            setResult(`✓ Playbook executed against ${targetIncident()}`);
        } catch (e: any) { setResult('✗ ' + (e?.message ?? e)); }
        setRunning(false);
        setTimeout(() => setResult(''), 5000);
    };

    return (
        <div style="padding:2rem; color:#c8d8d8; font-family:'JetBrains Mono',monospace; min-height:100vh; background:#080f12;">
            <div style="margin-bottom:1.5rem;">
                <h1 style="font-size:1.4rem; letter-spacing:0.15em; margin:0; color:#ff6600;">⬡ PLAYBOOK BUILDER</h1>
                <p style="margin:0.25rem 0 0; font-size:0.75rem; color:#607070;">Visual SOAR automation · Assemble, save, and execute response playbooks</p>
            </div>

            <div style="display:grid; grid-template-columns:220px 1fr 260px; gap:1rem; height:calc(100vh - 120px);">
                {/* Action palette */}
                <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:1rem; overflow-y:auto;">
                    <div style="font-size:0.65rem; color:#607070; letter-spacing:0.12em; margin-bottom:0.75rem;">AVAILABLE ACTIONS</div>
                    <Show when={!availableActions.loading}>
                        <For each={availableActions()}>
                            {(action) => (
                                <div onClick={() => addStep(action)} style="padding:8px 10px; border:1px solid #1e3040; border-radius:3px; margin-bottom:6px; cursor:pointer; font-size:0.76rem; display:flex; align-items:center; gap:8px; background:#0a1318; transition:border-color 0.15s;"
                                    onMouseEnter={e => (e.currentTarget as HTMLElement).style.borderColor = '#ff6600'}
                                    onMouseLeave={e => (e.currentTarget as HTMLElement).style.borderColor = '#1e3040'}>
                                    <span>{STEP_ICONS[action] ?? STEP_ICONS.default}</span>
                                    <span>{action.replace(/_/g,' ')}</span>
                                    <span style="margin-left:auto; color:#ff6600; font-weight:700;">+</span>
                                </div>
                            )}
                        </For>
                    </Show>
                    <div style="margin-top:1.5rem; border-top:1px solid #1e3040; padding-top:1rem;">
                        <div style="font-size:0.65rem; color:#607070; letter-spacing:0.12em; margin-bottom:0.5rem;">SAVED PLAYBOOKS</div>
                        <Show when={!savedPlaybooks.loading}>
                            <For each={savedPlaybooks()} fallback={<div style="color:#607070; font-size:0.72rem;">None saved yet.</div>}>
                                {(pb) => (
                                    <div style="padding:6px 8px; background:#0a1318; border:1px solid #1e3040; border-radius:3px; margin-bottom:4px; cursor:pointer; font-size:0.72rem;"
                                        onClick={() => { setName(pb.name); setSteps(pb.steps); }}
                                        onMouseEnter={e => (e.currentTarget as HTMLElement).style.background = '#111f28'}
                                        onMouseLeave={e => (e.currentTarget as HTMLElement).style.background = '#0a1318'}>
                                        <div style="color:#c8d8d8;">{pb.name}</div>
                                        <div style="color:#607070; font-size:0.65rem;">{pb.steps.length} steps</div>
                                    </div>
                                )}
                            </For>
                        </Show>
                    </div>
                </div>

                {/* Canvas */}
                <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:1rem; overflow-y:auto; display:flex; flex-direction:column; gap:0.75rem;">
                    <input placeholder="Playbook name…" value={name()} onInput={e => setName(e.currentTarget.value)}
                        style="background:#0a1318; border:1px solid #1e3040; color:#c8d8d8; padding:8px 10px; border-radius:3px; font-size:0.82rem; font-family:inherit;" />
                    <Show when={steps().length === 0}>
                        <div style="border:2px dashed #1e3040; border-radius:6px; padding:3rem; text-align:center; color:#607070; font-size:0.76rem; letter-spacing:0.1em;">
                            CLICK ACTIONS IN THE LEFT PANEL TO BUILD YOUR PLAYBOOK
                        </div>
                    </Show>
                    <For each={steps()}>
                        {(step, idx) => (
                            <div style={`background:#0a1318; border:1px solid ${step.enabled ? '#1e3040' : '#0d1a1f'}; border-radius:4px; padding:10px; display:flex; align-items:center; gap:10px; opacity:${step.enabled ? 1 : 0.4};`}>
                                <div style="display:flex; flex-direction:column; gap:2px;">
                                    <button onClick={() => moveUp(idx())} style="background:none; border:none; color:#607070; cursor:pointer; font-size:11px; line-height:1; padding:0;">▲</button>
                                    <button onClick={() => moveDown(idx())} style="background:none; border:none; color:#607070; cursor:pointer; font-size:11px; line-height:1; padding:0;">▼</button>
                                </div>
                                <div style="width:22px; height:22px; border-radius:50%; background:#1e3040; display:flex; align-items:center; justify-content:center; font-size:9px; color:#607070; font-weight:700; flex-shrink:0;">{idx()+1}</div>
                                <span style="font-size:14px;">{STEP_ICONS[step.action] ?? STEP_ICONS.default}</span>
                                <span style="flex:1; font-size:0.78rem; color:#c8d8d8;">{step.action.replace(/_/g,' ').toUpperCase()}</span>
                                <button onClick={() => toggleStep(step.id)}
                                    style={`padding:2px 7px; font-size:0.68rem; letter-spacing:0.1em; border-radius:2px; cursor:pointer; border:1px solid ${step.enabled ? '#00ff88' : '#1e3040'}; background:none; color:${step.enabled ? '#00ff88' : '#607070'};`}>
                                    {step.enabled ? 'ON' : 'OFF'}
                                </button>
                                <button onClick={() => removeStep(step.id)} style="background:none; border:none; color:#607070; cursor:pointer; font-size:15px; padding:0; line-height:1;">✕</button>
                            </div>
                        )}
                    </For>
                </div>

                {/* Execute panel */}
                <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:1rem; display:flex; flex-direction:column; gap:0.75rem; overflow-y:auto;">
                    <div style="font-size:0.65rem; color:#607070; letter-spacing:0.12em;">EXECUTE AGAINST</div>
                    <input placeholder="Incident ID…" value={targetIncident()} onInput={e => setTargetIncident(e.currentTarget.value)}
                        style="background:#0a1318; border:1px solid #1e3040; color:#c8d8d8; padding:8px 10px; border-radius:3px; font-size:0.78rem; font-family:inherit; width:100%; box-sizing:border-box;" />
                    <button onClick={executePlaybook} disabled={running()}
                        style={`width:100%; background:${running() ? 'rgba(255,102,0,0.1)' : '#ff6600'}; border:1px solid #ff6600; color:${running() ? '#ff6600' : '#080f12'}; padding:9px; border-radius:3px; cursor:pointer; font-weight:700; font-size:0.78rem; letter-spacing:0.1em;`}>
                        {running() ? '⏳ EXECUTING…' : '▶ RUN PLAYBOOK'}
                    </button>
                    <button onClick={savePlaybook} disabled={saving()}
                        style="width:100%; background:none; border:1px solid #1e3040; color:#607070; padding:8px; border-radius:3px; cursor:pointer; font-size:0.78rem; letter-spacing:0.1em;">
                        {saving() ? '⏳ SAVING…' : '💾 SAVE PLAYBOOK'}
                    </button>
                    <Show when={result()}>
                        <div style={`padding:8px 10px; border-radius:3px; font-size:0.76rem; background:${result().startsWith('✓') ? '#002a1a' : '#2a0d15'}; border:1px solid ${result().startsWith('✓') ? '#00ff88' : '#ff3355'}; color:${result().startsWith('✓') ? '#00ff88' : '#ff3355'}; line-height:1.5;`}>{result()}</div>
                    </Show>
                    <div style="margin-top:auto; padding:0.75rem; background:#0a1318; border-radius:3px; border:1px solid #1e3040;">
                        <div style="font-size:0.65rem; color:#607070; letter-spacing:0.1em; margin-bottom:0.4rem;">SUMMARY</div>
                        <div style="font-size:0.72rem; color:#c8d8d8; display:flex; flex-direction:column; gap:3px;">
                            <span>Total steps: {steps().length}</span>
                            <span>Active: {steps().filter(s => s.enabled).length}</span>
                            <span>Disabled: {steps().filter(s => !s.enabled).length}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

// frontend-web/src/pages/PlaybookBuilder.svelte
<!-- OBLIVRA Web — Playbook Builder (Svelte 5) -->
<script lang="ts">
  import { onMount } from 'svelte';
  import { Badge, Button, PageLayout } from '@components/ui';
  import { Play, Save, Plus, Trash2, ChevronUp, ChevronDown, Terminal, Shield, Activity, Lock, User, Scissors, Clipboard, Database, Globe } from 'lucide-svelte';
  import { History as HistoryIcon } from 'lucide-svelte';
  import { request } from '../services/api';

  // -- Types --
  interface PlaybookStep {
    id: string;
    action: string;
    params: Record<string, string>;
    enabled: boolean;
  }
  interface SavedPlaybook {
    id: string;
    name: string;
    steps: PlaybookStep[];
    created_at: string;
    last_run?: string;
  }

  // -- Constants --
  const STEP_ICONS: Record<string, any> = {
    isolate_host: Lock,
    lock_account: User,
    kill_process: Scissors,
    collect_logs: Clipboard,
    snapshot_memory: Database,
    notify_team: Activity,
    run_scan: Shield,
    block_ip: XCircle,
    webhook: Globe,
    default: Terminal,
  };

  import { XCircle } from 'lucide-svelte';

  // -- State --
  let availableActions = $state<string[]>([]);
  let savedPlaybooks   = $state<SavedPlaybook[]>([]);
  let steps            = $state<PlaybookStep[]>([]);
  let name             = $state('');
  let targetIncident   = $state('');
  let running          = $state(false);
  let saving           = $state(false);
  let result           = $state('');

  // -- Actions --
  async function fetchData() {
    try {
      const [a, p] = await Promise.all([
        request<{ actions: string[] }>('/playbooks/actions'),
        request<{ playbooks: SavedPlaybook[] }>('/playbooks')
      ]);
      availableActions = a.actions ?? [];
      savedPlaybooks = p.playbooks ?? [];
    } catch (e) {
      console.error('Playbook fetch failed', e);
      availableActions = ['isolate_host', 'lock_account', 'kill_process', 'collect_logs', 'notify_team', 'block_ip', 'webhook'];
    } finally {
      // Done
    }
  }

  const addStep = (action: string) => {
    steps = [...steps, {
      id: `step-${Date.now()}`,
      action, params: {}, enabled: true,
    }];
  };

  const removeStep = (id: string) => {
    steps = steps.filter(x => x.id !== id);
  };

  const toggleStep = (id: string) => {
    steps = steps.map(x => x.id === id ? { ...x, enabled: !x.enabled } : x);
  };

  const moveUp = (idx: number) => {
    if (idx === 0) return;
    const a = [...steps];
    [a[idx-1], a[idx]] = [a[idx], a[idx-1]];
    steps = a;
  };

  const moveDown = (idx: number) => {
    if (idx >= steps.length - 1) return;
    const a = [...steps];
    [a[idx], a[idx+1]] = [a[idx+1], a[idx]];
    steps = a;
  };

  async function savePlaybook() {
    if (!name.trim() || steps.length === 0) {
      result = '✗ Name and at least one step required.';
      return;
    }
    saving = true;
    try {
      await request('/playbooks', { method: 'POST', body: JSON.stringify({ name, steps }) });
      result = '✓ Playbook saved successfully.';
      fetchData();
    } catch (e: any) {
      result = '✗ ' + (e?.message ?? e);
    } finally {
      saving = false;
      setTimeout(() => result = '', 4000);
    }
  }

  async function executePlaybook() {
    if (!targetIncident.trim()) {
      result = '✗ Enter a target incident ID.';
      return;
    }
    if (steps.length === 0) {
      result = '✗ Add at least one step.';
      return;
    }
    running = true;
    try {
      await request('/playbooks/run', {
        method: 'POST',
        body: JSON.stringify({
          name: name || 'adhoc-playbook',
          steps: steps.filter(s => s.enabled),
          incident_id: targetIncident,
        })
      });
      result = `✓ Playbook executed against ${targetIncident}`;
    } catch (e: any) {
      result = '✗ ' + (e?.message ?? e);
    } finally {
      running = false;
      setTimeout(() => result = '', 5000);
    }
  }

  onMount(() => {
    fetchData();
  });
</script>

<PageLayout title="Playbook Builder" subtitle="Tactical SOAR automation: Assemble, verify, and orchestrate mission-critical response sequences">
  {#snippet toolbar()}
    <div class="flex items-center gap-2">
      <Button variant="secondary" size="sm" onclick={fetchData}>
        <HistoryIcon size={14} class="mr-2" />
        RE-SYNC
      </Button>
      <Button variant="primary" size="sm" icon={Plus}>NEW TEMPLATE</Button>
    </div>
  {/snippet}

  <div class="flex h-full gap-4 -m-6 p-6 overflow-hidden bg-surface-0">
    <!-- LEFT: PALETTE -->
    <div class="w-72 flex flex-col gap-4 shrink-0 overflow-hidden">
       <!-- Action Palette -->
       <div class="bg-surface-1 border border-border-primary rounded-sm flex flex-col min-h-0 shadow-premium">
          <div class="p-3 bg-surface-2 border-b border-border-primary flex items-center justify-between">
             <span class="text-[9px] font-mono font-bold text-text-muted uppercase tracking-widest">Available Shards</span>
             <Badge variant="accent" size="xs">L7_ATOMS</Badge>
          </div>
          <div class="flex-1 overflow-auto p-2 space-y-1.5">
             {#each availableActions as action}
                {@const Icon = STEP_ICONS[action] || STEP_ICONS.default}
                <button 
                  class="w-full text-left p-2.5 rounded-sm border border-border-subtle bg-surface-2 hover:border-accent-primary group transition-all flex items-center gap-3"
                  onclick={() => addStep(action)}
                >
                   <div class="p-1.5 bg-surface-1 border border-border-subtle rounded-xs group-hover:border-accent-primary/40 transition-colors">
                      <Icon size={14} class="text-text-secondary group-hover:text-accent-primary" />
                   </div>
                   <span class="text-[10px] font-bold text-text-secondary uppercase group-hover:text-text-heading transition-colors">{action.replace(/_/g, ' ')}</span>
                   <Plus size={12} class="ml-auto text-accent-primary opacity-0 group-hover:opacity-100 transition-opacity" />
                </button>
             {/each}
          </div>
       </div>

       <!-- Saved Playbooks -->
       <div class="bg-surface-1 border border-border-primary rounded-sm flex-1 flex flex-col min-h-0 shadow-premium">
          <div class="p-3 bg-surface-2 border-b border-border-primary flex items-center gap-2">
             <Save size={14} class="text-text-muted" />
             <span class="text-[9px] font-mono font-bold text-text-muted uppercase tracking-widest">Saved Shards</span>
          </div>
          <div class="flex-1 overflow-auto p-2 space-y-1.5">
             {#each savedPlaybooks as pb}
                <button 
                  class="w-full text-left p-3 rounded-sm border border-border-subtle bg-surface-2 hover:border-accent-primary group transition-all"
                  onclick={() => { name = pb.name; steps = [...pb.steps]; }}
                >
                   <div class="text-[11px] font-bold text-text-heading uppercase tracking-tighter mb-1">{pb.name}</div>
                   <div class="flex justify-between items-center text-[8px] font-mono text-text-muted uppercase tracking-widest">
                      <span>{pb.steps.length} Steps</span>
                      <span>{new Date(pb.created_at).toLocaleDateString()}</span>
                   </div>
                </button>
             {:else}
                <div class="py-10 text-center opacity-40 text-[9px] font-mono uppercase">No saved sequences</div>
             {/each}
          </div>
       </div>
    </div>

    <!-- CENTER: CANVAS -->
    <div class="flex-1 flex flex-col min-w-0 bg-surface-1 border border-border-primary rounded-sm shadow-premium overflow-hidden">
       <div class="bg-surface-2 border-b border-border-primary p-4 flex items-center gap-4">
          <div class="p-2 bg-surface-1 border border-border-subtle rounded-xs text-accent-primary">
             <Terminal size={18} />
          </div>
          <input 
             bind:value={name}
             class="flex-1 bg-transparent text-xl font-black text-text-heading uppercase italic tracking-tighter focus:outline-none placeholder:opacity-20" 
             placeholder="UNTITLED_PLAYBOOK_SEQUENCE..."
          />
          <div class="flex items-center gap-2">
             <Badge variant="secondary" size="sm">{steps.length} STEPS</Badge>
          </div>
       </div>

       <div class="flex-1 overflow-auto p-8 relative">
          {#if steps.length === 0}
             <div class="h-full flex flex-col items-center justify-center gap-6 opacity-20 py-20">
                <div class="w-32 h-32 border-2 border-dashed border-text-muted rounded-full flex items-center justify-center">
                   <Plus size={48} />
                </div>
                <div class="text-center space-y-2">
                   <p class="text-sm font-black uppercase tracking-widest">Assemble Logic Bridge</p>
                   <p class="text-[10px] font-mono">Inject atomic actions from the left shard palette</p>
                </div>
             </div>
          {:else}
             <div class="max-w-3xl mx-auto space-y-4">
                {#each steps as step, idx}
                   {@const Icon = STEP_ICONS[step.action] || STEP_ICONS.default}
                   <div class="relative group animate-in slide-in-from-top-2 duration-300">
                      <!-- Connector Line -->
                      {#if idx < steps.length - 1}
                         <div class="absolute left-6 top-full h-4 w-px bg-border-primary z-0"></div>
                      {/if}
                      
                      <div class="bg-surface-2 border border-border-primary p-4 rounded-sm flex items-center gap-4 relative z-10 transition-all
                        {step.enabled ? 'border-l-4 border-l-accent-primary' : 'opacity-40 grayscale'}">
                         
                         <div class="flex flex-col gap-1 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                            <button class="text-text-muted hover:text-text-heading" onclick={() => moveUp(idx)}><ChevronUp size={14} /></button>
                            <button class="text-text-muted hover:text-text-heading" onclick={() => moveDown(idx)}><ChevronDown size={14} /></button>
                         </div>

                         <div class="w-8 h-8 rounded-full bg-surface-1 border border-border-subtle flex items-center justify-center text-[10px] font-black text-text-muted shrink-0">
                            {idx + 1}
                         </div>

                         <div class="p-2 bg-surface-3 border border-border-subtle rounded-xs shrink-0">
                            <Icon size={16} class="text-accent-primary" />
                         </div>

                         <div class="flex-1 min-w-0">
                            <div class="text-[12px] font-black text-text-heading uppercase tracking-tighter">{step.action.replace(/_/g, ' ')}</div>
                            <div class="text-[8px] font-mono text-text-muted uppercase tracking-widest">Shard_ID: {step.id}</div>
                         </div>

                         <div class="flex items-center gap-3">
                            <button 
                               class="text-[9px] font-black uppercase tracking-widest px-3 py-1 rounded-xs border transition-colors
                                 {step.enabled ? 'border-status-online text-status-online hover:bg-status-online/10' : 'border-text-muted text-text-muted hover:text-text-heading'}"
                               onclick={() => toggleStep(step.id)}
                            >
                               {step.enabled ? 'ACTIVE' : 'MUTED'}
                            </button>
                            <button class="text-text-muted hover:text-alert-critical transition-colors" onclick={() => removeStep(step.id)}>
                               <Trash2 size={16} />
                            </button>
                         </div>
                      </div>
                   </div>
                {/each}
             </div>
          {/if}
       </div>
    </div>

    <!-- RIGHT: EXECUTE -->
    <div class="w-72 flex flex-col gap-4 shrink-0 overflow-hidden">
       <div class="bg-surface-1 border border-border-primary rounded-sm p-5 space-y-6 shadow-premium h-full flex flex-col">
          <div class="space-y-4">
             <div class="flex items-center gap-2">
                <Play size={14} class="text-alert-critical" />
                <span class="text-[10px] font-black text-text-heading uppercase tracking-widest">Execute Sequence</span>
             </div>
             
             <div class="space-y-1.5">
                <span class="text-[9px] font-mono text-text-muted uppercase tracking-widest">Target Incident ID</span>
                <input 
                   bind:value={targetIncident}
                   class="w-full bg-surface-2 border border-border-subtle rounded-sm px-3 py-2 text-xs font-mono text-text-secondary focus:border-accent-primary focus:outline-none" 
                   placeholder="INCIDENT-2026-X" 
                />
             </div>

             <Button 
                variant="danger" 
                class="w-full py-4 font-black italic tracking-tighter group overflow-hidden relative" 
                onclick={executePlaybook} 
                loading={running}
             >
                <div class="absolute inset-0 bg-white opacity-0 group-hover:opacity-10 transition-opacity"></div>
                RUN_PLAYBOOK_NOW
             </Button>

             <Button 
                variant="secondary" 
                class="w-full font-black italic tracking-tighter" 
                onclick={savePlaybook} 
                loading={saving}
             >
                SAVE_TO_VAULT
             </Button>

             {#if result}
                <div class="p-3 rounded-sm border animate-in fade-in duration-300 text-[10px] font-bold leading-tight
                   {result.startsWith('✓') ? 'bg-status-online/5 border-status-online/40 text-status-online' : 'bg-alert-critical/5 border-alert-critical/40 text-alert-critical'}"
                >
                   {result}
                </div>
             {/if}
          </div>

          <div class="mt-auto space-y-4 pt-6 border-t border-border-primary">
             <div class="flex items-center gap-2">
                <Activity size={14} class="text-accent-primary" />
                <span class="text-[9px] font-mono font-bold text-text-muted uppercase tracking-widest">Sequence Metrics</span>
             </div>
             <div class="space-y-2">
                <div class="flex justify-between text-[10px] font-mono">
                   <span class="text-text-muted uppercase">Total Atoms</span>
                   <span class="font-bold text-text-heading">{steps.length}</span>
                </div>
                <div class="flex justify-between text-[10px] font-mono">
                   <span class="text-text-muted uppercase">Active Path</span>
                   <span class="font-bold text-status-online">{steps.filter(s => s.enabled).length}</span>
                </div>
                <div class="flex justify-between text-[10px] font-mono">
                   <span class="text-text-muted uppercase">Est. Latency</span>
                   <span class="font-bold text-accent-primary">&lt; 400ms</span>
                </div>
             </div>
             <div class="p-3 bg-surface-2 border border-border-subtle rounded-xs text-[8px] font-mono text-text-muted italic leading-relaxed">
                Sequence execution is atomic. Failures in intermediate steps will trigger rollback protocols unless 'CONTINUE_ON_FAIL' is defined.
             </div>
          </div>
       </div>
    </div>

    <!-- STATUS BAR -->
    <div class="fixed bottom-0 left-0 right-0 bg-surface-2 border-t border-border-primary px-3 py-1 flex items-center gap-4 text-[8px] font-mono text-text-muted z-50 uppercase tracking-widest">
        <div class="flex items-center gap-1.5">
            <div class="w-1 h-1 rounded-full bg-status-online"></div>
            <span>SOAR_ENGINE:</span>
            <span class="text-status-online font-bold italic">CONNECTED</span>
        </div>
        <span class="text-border-primary opacity-30">|</span>
        <div class="flex items-center gap-1.5">
            <span>SEQUENCE_INTEGRITY:</span>
            <span class="text-status-online font-bold italic">VALIDATED</span>
        </div>
        <span class="text-border-primary opacity-30">|</span>
        <div class="flex items-center gap-1.5">
            <span>ORCHESTRATION_L8:</span>
            <span class="text-accent-primary font-bold italic">ARMED</span>
        </div>
        <div class="ml-auto opacity-40">OBLIVRA_SOAR_BUILDER v8.2.0</div>
    </div>
  </div>
</PageLayout>

<style>
  :global(.flex-1::-webkit-scrollbar) {
    width: 6px;
    height: 6px;
  }
  :global(.flex-1::-webkit-scrollbar-track) {
    background: var(--surface-0);
  }
  :global(.flex-1::-webkit-scrollbar-thumb) {
    background: var(--border-primary);
    border-radius: 3px;
  }
</style>
