// frontend-web/src/pages/RegulatorPortal.svelte
<!-- OBLIVRA Web — Regulator Portal (Svelte 5) -->
<script lang="ts">
  import { onMount } from 'svelte';
  import { KPI, Badge, Button, DataTable, PageLayout, Spinner, Input } from '@components/ui';
  import { Shield, FileText, Download, Lock, CheckCircle, AlertTriangle, XCircle, Filter, Calendar, History, FileCheck, Database, Fingerprint } from 'lucide-svelte';
  import { request } from '../services/api';

  // -- Types --
  interface AuditEntry {
    id: string;
    timestamp: string;
    actor: string;
    action: string;
    resource: string;
    outcome: 'success' | 'failure' | 'blocked';
    ip?: string;
    tenant_id?: string;
    entry_hash: string;
    prev_hash: string;
  }
  interface CompliancePackage {
    id: string;
    framework: string;
    generated_at: string;
    records: number;
    integrity_proof: string;
    download_url: string;
  }

  // -- Constants --
  const FRAMEWORKS = ['ALL', 'SOC2', 'ISO27001', 'PCI-DSS', 'HIPAA', 'GDPR'];
  const OUTCOME_STYLE = {
    success: { color: 'var(--status-online)',  bg: 'rgba(0,200,100,0.1)', icon: CheckCircle },
    failure: { color: 'var(--alert-critical)', bg: 'rgba(200,44,44,0.1)', icon: XCircle },
    blocked: { color: 'var(--alert-medium)',   bg: 'rgba(200,140,0,0.1)', icon: AlertTriangle },
  };

  // -- State --
  let tab          = $state<'audit' | 'packages' | 'export'>('audit');
  let framework    = $state('ALL');
  let dateFrom     = $state('');
  let dateTo       = $state('');
  let selectedFw   = $state('SOC2');
  let loading      = $state(true);
  let generating   = $state(false);

  let auditEntries = $state<AuditEntry[]>([]);
  let packages     = $state<CompliancePackage[]>([]);

  // -- Helpers --
  const totalStats = $derived({
    total: auditEntries.length,
    success: auditEntries.filter(e => e.outcome === 'success').length,
    failure: auditEntries.filter(e => e.outcome === 'failure').length,
    blocked: auditEntries.filter(e => e.outcome === 'blocked').length,
  });

  // -- Actions --
  async function fetchAudit() {
    loading = true;
    try {
      const params = new URLSearchParams({ limit: '200' });
      if (framework !== 'ALL') params.set('framework', framework);
      if (dateFrom) params.set('from', dateFrom);
      if (dateTo) params.set('to', dateTo);
      const res = await request<{ entries: AuditEntry[] }>(`/audit/log?${params}`);
      auditEntries = res.entries ?? [];
    } catch (e) {
      console.error('Audit fetch failed', e);
    } finally {
      loading = false;
    }
  }

  async function fetchPackages() {
    try {
      const res = await request<{ packages: CompliancePackage[] }>('/audit/packages');
      packages = res.packages ?? [];
    } catch (e) {
      console.error('Packages fetch failed', e);
    }
  }

  async function generatePackage() {
    generating = true;
    try {
      await request('/audit/packages/generate', {
        method: 'POST',
        body: JSON.stringify({ framework: selectedFw, from: dateFrom, to: dateTo }),
      });
      fetchPackages();
      tab = 'packages';
    } catch (e) {
      console.error('Generation failed', e);
    } finally {
      generating = false;
    }
  }

  onMount(() => {
    fetchAudit();
    fetchPackages();
  });
</script>

<PageLayout title="Regulator Portal" subtitle="Scoped audit exposure and cryptographically-verified compliance artifacts">
  {#snippet toolbar()}
    <div class="flex items-center gap-2">
      <div class="px-3 py-1 bg-surface-2 border border-accent-primary/30 rounded-xs flex items-center gap-2">
        <div class="w-1.5 h-1.5 rounded-full bg-accent-primary animate-pulse"></div>
        <span class="text-[9px] font-mono font-bold text-accent-primary uppercase tracking-widest">Read-Only Auditor Access</span>
      </div>
      <Button variant="secondary" size="sm" onclick={fetchAudit}>
        <History size={14} class="mr-2" />
        RE-SYNC
      </Button>
    </div>
  {/snippet}

  <div class="flex flex-col h-full gap-0 -m-6 overflow-hidden">
    <!-- METRIC STRIP -->
    <div class="grid grid-cols-4 gap-px bg-border-primary border-b border-border-primary shrink-0">
        <div class="bg-surface-2 p-3">
            <div class="text-[8px] font-mono text-text-muted uppercase tracking-widest mb-1">Audit Stream Depth</div>
            <div class="text-xl font-mono font-bold text-accent-primary">{totalStats.total.toLocaleString()}</div>
            <div class="text-[9px] text-text-muted mt-1 italic">Verified L7 entries</div>
        </div>
        <div class="bg-surface-2 p-3">
            <div class="text-[8px] font-mono text-text-muted uppercase tracking-widest mb-1">Validated Outcomes</div>
            <div class="text-xl font-mono font-bold text-status-online">{totalStats.success.toLocaleString()}</div>
            <div class="text-[9px] text-status-online mt-1 uppercase tracking-tighter">✓ Integrity confirmed</div>
        </div>
        <div class="bg-surface-2 p-3">
            <div class="text-[8px] font-mono text-text-muted uppercase tracking-widest mb-1">Audit Failures</div>
            <div class="text-xl font-mono font-bold text-alert-critical">{totalStats.failure.toLocaleString()}</div>
            <div class="text-[9px] text-alert-critical mt-1 uppercase tracking-tighter">⚠ System warnings</div>
        </div>
        <div class="bg-surface-2 p-3">
            <div class="text-[8px] font-mono text-text-muted uppercase tracking-widest mb-1">Policy Blocked</div>
            <div class="text-xl font-mono font-bold text-alert-medium">{totalStats.blocked.toLocaleString()}</div>
            <div class="text-[9px] text-alert-medium mt-1 uppercase tracking-tighter">Proactive containment</div>
        </div>
    </div>

    <!-- MAIN BODY -->
    <div class="flex-1 flex flex-col min-h-0 bg-surface-0 overflow-hidden">
       <!-- TAB BAR -->
       <div class="bg-surface-1 border-b border-border-primary p-3 flex items-center justify-between shrink-0">
          <div class="flex border border-border-primary rounded-sm overflow-hidden">
            {#each ['audit', 'packages', 'export'] as t}
              <button
                class="px-4 py-1.5 text-[10px] font-black uppercase tracking-widest transition-colors
                  {tab === t ? 'bg-accent-primary text-black' : 'bg-surface-0 text-text-muted hover:text-text-secondary'}"
                onclick={() => tab = t as any}
              >
                {t}
              </button>
            {/each}
          </div>
          
          {#if tab === 'audit'}
             <div class="flex items-center gap-3">
                <select bind:value={framework} class="bg-surface-2 border border-border-subtle rounded-sm px-2 py-1 text-[10px] font-mono text-text-secondary focus:border-accent-primary focus:outline-none">
                   {#each FRAMEWORKS as fw}
                      <option value={fw}>{fw}</option>
                   {/each}
                </select>
                <div class="flex items-center gap-2">
                   <Calendar size={12} class="text-text-muted" />
                   <input type="date" bind:value={dateFrom} class="bg-surface-2 border border-border-subtle rounded-sm px-2 py-1 text-[10px] font-mono text-text-secondary" />
                   <span class="text-text-muted text-[10px]">→</span>
                   <input type="date" bind:value={dateTo} class="bg-surface-2 border border-border-subtle rounded-sm px-2 py-1 text-[10px] font-mono text-text-secondary" />
                </div>
                <Button variant="secondary" size="xs" onclick={fetchAudit}>APPLY FILTERS</Button>
             </div>
          {/if}
       </div>

       <div class="flex-1 overflow-auto">
          {#if loading}
             <div class="h-full flex items-center justify-center"><Spinner /></div>
          {:else if tab === 'audit'}
             <DataTable 
               data={auditEntries} 
               columns={[
                 { key: 'timestamp', label: 'EVENT_TIMESTAMP', width: '180px' },
                 { key: 'actor', label: 'ACTOR_IDENTITY', width: '200px' },
                 { key: 'action', label: 'ACTION_VERB', width: '150px' },
                 { key: 'resource', label: 'RESOURCE_TARGET' },
                 { key: 'outcome', label: 'OUTCOME', width: '120px' },
                 { key: 'entry_hash', label: 'INTEGRITY_HASH', width: '140px' }
               ]} 
               compact
               rowKey="id"
             >
                {#snippet cell({ column, row })}
                   {@const style = OUTCOME_STYLE[row.outcome]}
                   {#if column.key === 'timestamp'}
                      <span class="text-[10px] font-mono text-text-muted uppercase">{new Date(row.timestamp).toLocaleString()}</span>
                   {:else if column.key === 'actor'}
                      <div class="flex items-center gap-2">
                         <div class="w-1.5 h-1.5 rounded-full bg-accent-primary/40"></div>
                         <span class="text-[11px] font-bold text-text-heading uppercase">{row.actor}</span>
                      </div>
                   {:else if column.key === 'outcome'}
                      <div class="flex items-center gap-2">
                         <style.icon size={12} style="color: {style.color}" />
                         <span class="text-[9px] font-black uppercase tracking-widest italic" style="color: {style.color}">{row.outcome}</span>
                      </div>
                   {:else if column.key === 'entry_hash'}
                      <span class="text-[9px] font-mono text-text-muted opacity-40 uppercase tracking-tighter" title={row.entry_hash}>#{row.entry_hash.slice(0, 12)}...</span>
                   {:else}
                      <span class="text-[10px] text-text-secondary truncate block max-w-sm" title={row[column.key]}>{row[column.key]}</span>
                   {/if}
                {/snippet}
             </DataTable>
          {:else if tab === 'packages'}
             <div class="p-6 space-y-4 max-w-5xl mx-auto">
                {#each packages as pkg}
                   <div class="bg-surface-1 border border-border-primary p-5 rounded-sm flex justify-between items-center group hover:border-accent-primary transition-colors shadow-premium relative overflow-hidden">
                      <div class="absolute -left-2 -top-2 opacity-[0.03] grayscale">
                         <Lock size={120} />
                      </div>
                      <div class="flex flex-col gap-2 relative z-10">
                         <div class="flex items-center gap-3">
                            <Badge variant="accent" size="xs" class="font-bold">{pkg.framework}</Badge>
                            <span class="text-[13px] font-black text-text-heading uppercase tracking-tighter italic">{pkg.id}</span>
                         </div>
                         <div class="flex gap-4 text-[10px] font-mono text-text-muted uppercase tracking-widest opacity-60">
                            <span class="flex items-center gap-1.5"><Database size={12} /> {pkg.records.toLocaleString()} RECORDS</span>
                            <span class="flex items-center gap-1.5"><Calendar size={12} /> GENERATED {new Date(pkg.generated_at).toLocaleDateString()}</span>
                         </div>
                         <div class="flex items-center gap-2 text-[9px] font-mono text-text-muted uppercase tracking-tighter opacity-40">
                            <Fingerprint size={10} />
                            <span>Proof: {pkg.integrity_proof.slice(0, 32)}...</span>
                         </div>
                      </div>
                      <a href={pkg.download_url} download class="relative z-10 bg-accent-primary hover:bg-accent-secondary text-black px-6 py-2 rounded-xs font-black italic tracking-tighter text-[11px] transition-colors flex items-center gap-2">
                         <Download size={14} />
                         DOWNLOAD_PACKAGE
                      </a>
                   </div>
                {:else}
                   <div class="py-20 text-center opacity-40 flex flex-col items-center gap-4">
                      <FileText size={48} />
                      <p class="text-[10px] font-mono uppercase tracking-widest">No compliance packages archived</p>
                   </div>
                {/each}
             </div>
          {:else if tab === 'export'}
             <div class="p-12 flex items-center justify-center">
                <div class="bg-surface-1 border border-border-primary p-8 rounded-sm shadow-premium max-w-lg w-full space-y-8 relative overflow-hidden">
                   <div class="absolute right-0 top-0 w-24 h-24 bg-accent-primary/5 rounded-bl-full"></div>
                   <div class="space-y-2">
                      <h3 class="text-xl font-black text-text-heading uppercase italic tracking-tighter">Generate Evidence Shard</h3>
                      <p class="text-[11px] text-text-muted leading-relaxed">Select a regulatory framework to encapsulate and sign an immutable audit package for external review.</p>
                   </div>

                   <div class="space-y-6">
                      <div class="space-y-3">
                         <span class="text-[9px] font-black text-text-muted uppercase tracking-widest">Compliance Framework</span>
                         <div class="grid grid-cols-3 gap-2">
                            {#each FRAMEWORKS.filter(f => f !== 'ALL') as fw}
                               <button 
                                 class="p-2.5 rounded-xs border text-[10px] font-bold uppercase tracking-widest transition-all
                                   {selectedFw === fw ? 'bg-accent-primary/10 border-accent-primary text-accent-primary' : 'bg-surface-2 border-border-subtle text-text-muted hover:border-border-primary'}"
                                 onclick={() => selectedFw = fw}
                               >
                                  {fw}
                               </button>
                            {/each}
                         </div>
                      </div>

                      <div class="grid grid-cols-2 gap-4">
                         <div class="space-y-2">
                            <span class="text-[9px] font-black text-text-muted uppercase tracking-widest">Timeline Start</span>
                            <input type="date" bind:value={dateFrom} class="w-full bg-surface-2 border border-border-subtle rounded-sm px-3 py-2 text-xs font-mono text-text-secondary focus:border-accent-primary focus:outline-none" />
                         </div>
                         <div class="space-y-2">
                            <span class="text-[9px] font-black text-text-muted uppercase tracking-widest">Timeline End</span>
                            <input type="date" bind:value={dateTo} class="w-full bg-surface-2 border border-border-subtle rounded-sm px-3 py-2 text-xs font-mono text-text-secondary focus:border-accent-primary focus:outline-none" />
                         </div>
                      </div>

                      <div class="bg-surface-2 border border-border-subtle p-4 rounded-sm space-y-2">
                         <div class="flex items-center gap-2 text-[10px] font-bold text-text-heading uppercase">
                            <FileCheck size={14} class="text-status-online" />
                            Security Attestation
                         </div>
                         <p class="text-[9px] text-text-muted font-mono leading-relaxed opacity-60">
                            Package will include cryptographically-chained logs, Merkle proof, and Evidence Vault manifest signed by OBLIVRA_ORBIT_CA.
                         </p>
                      </div>

                      <Button variant="primary" class="w-full py-3 font-black italic tracking-tighter" onclick={generatePackage} loading={generating}>
                         GENERATE {selectedFw} AUDIT SHARD
                      </Button>
                   </div>
                </div>
             </div>
          {/if}
       </div>
    </div>

    <!-- STATUS BAR -->
    <div class="bg-surface-2 border-t border-border-primary px-3 py-1 flex items-center gap-4 text-[8px] font-mono text-text-muted shrink-0 uppercase tracking-widest">
        <div class="flex items-center gap-1.5">
            <div class="w-1 h-1 rounded-full bg-status-online"></div>
            <span>AUDIT_ENCLAVE:</span>
            <span class="text-status-online font-bold italic">LOCKED_IMMUTABLE</span>
        </div>
        <span class="text-border-primary opacity-30">|</span>
        <div class="flex items-center gap-1.5">
            <span>CHAIN_INTEGRITY:</span>
            <span class="text-status-online font-bold italic">VERIFIED</span>
        </div>
        <span class="text-border-primary opacity-30">|</span>
        <div class="flex items-center gap-1.5">
            <span>REGULATOR_SIG:</span>
            <span class="text-accent-primary font-bold italic">RSA_4096_ACTIVE</span>
        </div>
        <div class="ml-auto opacity-40">OBLIVRA_REGULATOR_v6.6.2</div>
    </div>
  </div>
</PageLayout>

<style>
  :global(.flex-1::-webkit-scrollbar) {
    width: 6px;
    height: 6px;
  }
  :global(.flex-1::-webkit-scrollbar-track) {
    background: var(--surface-0);
  }
  :global(.flex-1::-webkit-scrollbar-thumb) {
    background: var(--border-primary);
    border-radius: 3px;
  }
</style>

// frontend-web/src/pages/RegulatorPortal.tsx
/**
 * RegulatorPortal.tsx — Regulator-Ready Audit Export (Phase 6.6)
 *
 * Scoped, read-only audit viewer for external auditors.
 * One-click compliance package generation and export.
 * Connects to /api/v1/audit/*.
 */

import { createSignal, createResource, For, Show } from 'solid-js';
import { request } from '../services/api';

// ── Types ─────────────────────────────────────────────────────────────────────
interface AuditEntry {
  id: string;
  timestamp: string;
  actor: string;
  action: string;
  resource: string;
  outcome: 'success' | 'failure' | 'blocked';
  ip?: string;
  tenant_id?: string;
  entry_hash: string;
  prev_hash: string;
}
interface CompliancePackage {
  id: string;
  framework: string;
  generated_at: string;
  records: number;
  integrity_proof: string;
  download_url: string;
}

// ── Helpers ───────────────────────────────────────────────────────────────────
const OUTCOME_STYLE: Record<string, { color: string; bg: string }> = {
  success: { color: '#00ff88', bg: '#001a0a' },
  failure: { color: '#ff3355', bg: '#2a0d15' },
  blocked: { color: '#ffaa00', bg: '#2a2000' },
};

const FRAMEWORKS = ['ALL', 'SOC2', 'ISO27001', 'PCI-DSS', 'HIPAA', 'GDPR'];

// ── Component ─────────────────────────────────────────────────────────────────
type Tab = 'audit' | 'packages' | 'export';

export default function RegulatorPortal() {
  const [tab, setTab] = createSignal<Tab>('audit');
  const [framework, setFramework] = createSignal('ALL');
  const [dateFrom, setDateFrom] = createSignal('');
  const [dateTo, setDateTo] = createSignal('');
  const [generating, setGenerating] = createSignal(false);
  const [selectedFw, setSelectedFw] = createSignal('SOC2');

  const [auditLog, { refetch: refetchAudit }] = createResource<AuditEntry[]>(async () => {
    const params = new URLSearchParams({ limit: '200' });
    if (framework() !== 'ALL') params.set('framework', framework());
    if (dateFrom()) params.set('from', dateFrom());
    if (dateTo()) params.set('to', dateTo());
    const r = await request<{ entries: AuditEntry[] }>(`/audit/log?${params}`);
    return r.entries ?? [];
  });

  const [packages, { refetch: refetchPkgs }] = createResource<CompliancePackage[]>(async () => {
    const r = await request<{ packages: CompliancePackage[] }>('/audit/packages');
    return r.packages ?? [];
  });

  async function generatePackage() {
    setGenerating(true);
    try {
      await request('/audit/packages/generate', {
        method: 'POST',
        body: JSON.stringify({ framework: selectedFw(), from: dateFrom(), to: dateTo() }),
      });
      refetchPkgs();
    } finally { setGenerating(false); }
  }

  const TAB = (t: Tab) =>
    `padding:0.5rem 1.2rem; cursor:pointer; font-size:0.78rem; letter-spacing:0.12em; border:none; border-bottom:2px solid ${tab()===t ? '#0099ff' : 'transparent'}; background:none; color:${tab()===t ? '#0099ff' : '#607070'};`;

  return (
    <div style="padding:2rem; color:#c8d8d8; font-family:'JetBrains Mono',monospace; min-height:100vh; background:#080f12;">
      {/* Header */}
      <div style="display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:1.5rem;">
        <div>
          <h1 style="font-size:1.4rem; letter-spacing:0.15em; margin:0; color:#0099ff;">⬡ REGULATOR PORTAL</h1>
          <p style="margin:0.25rem 0 0; font-size:0.75rem; color:#607070;">
            Read-only audit log · Compliance packages · Cryptographic integrity proofs
          </p>
        </div>
        <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:4px; padding:0.5rem 1rem; font-size:0.7rem; color:#607070; text-align:center;">
          <div style="color:#0099ff; font-weight:700; font-size:0.65rem; letter-spacing:0.1em;">READ-ONLY MODE</div>
          <div style="margin-top:0.1rem;">Auditor View</div>
        </div>
      </div>

      {/* Stats */}
      <Show when={!auditLog.loading}>
        <div style="display:grid; grid-template-columns:repeat(4,1fr); gap:1rem; margin-bottom:1.5rem;">
          {[
            { label: 'AUDIT ENTRIES', value: (auditLog()??[]).length, color: '#0099ff' },
            { label: 'SUCCESS', value: (auditLog()??[]).filter(e=>e.outcome==='success').length, color: '#00ff88' },
            { label: 'FAILURES', value: (auditLog()??[]).filter(e=>e.outcome==='failure').length, color: '#ff3355' },
            { label: 'BLOCKED', value: (auditLog()??[]).filter(e=>e.outcome==='blocked').length, color: '#ffaa00' },
          ].map(s => (
            <div style="background:#0d1a1f; border:1px solid #1e3040; border-top:2px solid #1e3040; padding:0.9rem; border-radius:4px;">
              <div style={`font-size:1.4rem; font-weight:700; color:${s.color};`}>{s.value}</div>
              <div style="font-size:0.65rem; color:#607070; letter-spacing:0.12em;">{s.label}</div>
            </div>
          ))}
        </div>
      </Show>

      {/* Tabs */}
      <div style="display:flex; border-bottom:1px solid #1e3040; margin-bottom:1.25rem;">
        {(['audit','packages','export'] as Tab[]).map(t => (
          <button style={TAB(t)} onClick={() => setTab(t)}>{t.toUpperCase()}</button>
        ))}
      </div>

      {/* ── Audit Log tab ── */}
      <Show when={tab() === 'audit'}>
        {/* Filters */}
        <div style="display:flex; gap:0.75rem; margin-bottom:1rem; flex-wrap:wrap;">
          <select value={framework()} onChange={e => setFramework(e.currentTarget.value)}
            style="background:#0d1a1f; border:1px solid #1e3040; color:#c8d8d8; padding:0.4rem; border-radius:3px; font-size:0.75rem;">
            <For each={FRAMEWORKS}>{f => <option value={f}>{f}</option>}</For>
          </select>
          <input type="date" value={dateFrom()} onChange={e => setDateFrom(e.currentTarget.value)}
            style="background:#0d1a1f; border:1px solid #1e3040; color:#c8d8d8; padding:0.4rem 0.6rem; border-radius:3px; font-size:0.75rem;" />
          <input type="date" value={dateTo()} onChange={e => setDateTo(e.currentTarget.value)}
            style="background:#0d1a1f; border:1px solid #1e3040; color:#c8d8d8; padding:0.4rem 0.6rem; border-radius:3px; font-size:0.75rem;" />
          <button onClick={() => refetchAudit()}
            style="background:#0d1a1f; border:1px solid #1e3040; color:#607070; padding:0.4rem 0.75rem; border-radius:3px; cursor:pointer; font-size:0.75rem;">
            ↻ FILTER
          </button>
          <span style="color:#607070; font-size:0.72rem; align-self:center; margin-left:auto;">
            {(auditLog()??[]).length} entries
          </span>
        </div>

        <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; overflow:hidden;">
          <table style="width:100%; border-collapse:collapse; font-size:0.72rem;">
            <thead>
              <tr style="border-bottom:1px solid #1e3040; background:#0a1318;">
                {['TIMESTAMP','ACTOR','ACTION','RESOURCE','OUTCOME','HASH'].map(h => (
                  <th style="padding:0.6rem 0.9rem; text-align:left; color:#607070; letter-spacing:0.08em; font-weight:400;">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              <Show when={!auditLog.loading} fallback={
                <tr><td colspan="6" style="padding:2rem; text-align:center; color:#607070;">Loading audit log…</td></tr>
              }>
                <For each={auditLog()} fallback={
                  <tr><td colspan="6" style="padding:2rem; text-align:center; color:#607070;">No audit entries for selected filters.</td></tr>
                }>
                  {(entry) => {
                    const os = OUTCOME_STYLE[entry.outcome] ?? { color: '#607070', bg: '#0d1a1f' };
                    return (
                      <tr style="border-bottom:1px solid #0a1318;">
                        <td style="padding:0.5rem 0.9rem; color:#607070;">{new Date(entry.timestamp).toLocaleString()}</td>
                        <td style="padding:0.5rem 0.9rem; color:#c8d8d8;">{entry.actor}</td>
                        <td style="padding:0.5rem 0.9rem; color:#c8d8d8;">{entry.action}</td>
                        <td style="padding:0.5rem 0.9rem; color:#607070; max-width:160px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;" title={entry.resource}>{entry.resource}</td>
                        <td style="padding:0.5rem 0.9rem;">
                          <span style={`font-size:0.65rem; font-weight:700; background:${os.bg}; color:${os.color}; border:1px solid ${os.color}33; padding:0.15rem 0.4rem; border-radius:2px; letter-spacing:0.08em;`}>
                            {entry.outcome.toUpperCase()}
                          </span>
                        </td>
                        <td style="padding:0.5rem 0.9rem; color:#1e3040; font-size:0.65rem;" title={entry.entry_hash}>#{entry.entry_hash.slice(0,8)}…</td>
                      </tr>
                    );
                  }}
                </For>
              </Show>
            </tbody>
          </table>
        </div>
      </Show>

      {/* ── Packages tab ── */}
      <Show when={tab() === 'packages'}>
        <Show when={!packages.loading} fallback={<div style="color:#607070; padding:1rem;">Loading packages…</div>}>
          <div style="display:grid; gap:1rem;">
            <For each={packages()} fallback={
              <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:2rem; text-align:center; color:#607070;">
                No compliance packages generated yet. Use the Export tab to create one.
              </div>
            }>
              {(pkg) => (
                <div style="background:#0d1a1f; border:1px solid #1e3040; border-radius:6px; padding:1.25rem; display:flex; justify-content:space-between; align-items:center;">
                  <div>
                    <div style="display:flex; align-items:center; gap:0.75rem;">
                      <span style="background:#0a1318; border:1px solid #0099ff; color:#0099ff; padding:0.2rem 0.5rem; border-radius:3px; font-size:0.68rem; font-weight:700; letter-spacing:0.1em;">{pkg.framework}</span>
                      <span style="color:#c8d8d8; font-size:0.8rem;">{pkg.id}</span>
                    </div>
                    <div style="font-size:0.7rem; color:#607070; margin-top:0.4rem;">
                      {pkg.records.toLocaleString()} records · Generated {new Date(pkg.generated_at).toLocaleString()}
                    </div>
                    <div style="font-size:0.65rem; color:#1e3040; margin-top:0.2rem; font-family:monospace;" title="Merkle root / RFC3161 integrity proof">
                      Proof: {pkg.integrity_proof.slice(0,24)}…
                    </div>
                  </div>
                  <a href={pkg.download_url} download=""
                    style="background:#0099ff; color:#080f12; border:none; padding:0.45rem 1rem; border-radius:3px; cursor:pointer; font-weight:700; font-size:0.75rem; letter-spacing:0.08em; text-decoration:none;">
                    ↓ DOWNLOAD
                  </a>
                </div>
              )}
            </For>
          </div>
        </Show>
      </Show>

      {/* ── Export tab ── */}
      <Show when={tab() === 'export'}>
        <div style="background:#0d1a1f; border:1px solid #1e3040; border-top:2px solid #0099ff; border-radius:6px; padding:1.5rem; max-width:520px;">
          <div style="font-size:0.85rem; color:#c8d8d8; font-weight:600; margin-bottom:1rem;">Generate Compliance Package</div>

          <div style="display:flex; flex-direction:column; gap:1rem;">
            <div>
              <div style="font-size:0.65rem; color:#607070; letter-spacing:0.1em; margin-bottom:0.4rem;">FRAMEWORK</div>
              <div style="display:flex; flex-wrap:wrap; gap:0.4rem;">
                <For each={FRAMEWORKS.filter(f=>f!=='ALL')}>
                  {(f) => (
                    <button onClick={() => setSelectedFw(f)}
                      style={`background:${selectedFw()===f ? '#001833' : '#0a1318'}; border:1px solid ${selectedFw()===f ? '#0099ff' : '#1e3040'}; color:${selectedFw()===f ? '#0099ff' : '#607070'}; padding:0.35rem 0.75rem; border-radius:3px; cursor:pointer; font-size:0.72rem; letter-spacing:0.08em;`}>
                      {f}
                    </button>
                  )}
                </For>
              </div>
            </div>

            <div style="display:grid; grid-template-columns:1fr 1fr; gap:0.75rem;">
              <div>
                <div style="font-size:0.65rem; color:#607070; letter-spacing:0.1em; margin-bottom:0.35rem;">FROM DATE</div>
                <input type="date" value={dateFrom()} onChange={e => setDateFrom(e.currentTarget.value)}
                  style="background:#0a1318; border:1px solid #1e3040; color:#c8d8d8; padding:0.4rem 0.6rem; border-radius:3px; font-size:0.75rem; width:100%;" />
              </div>
              <div>
                <div style="font-size:0.65rem; color:#607070; letter-spacing:0.1em; margin-bottom:0.35rem;">TO DATE</div>
                <input type="date" value={dateTo()} onChange={e => setDateTo(e.currentTarget.value)}
                  style="background:#0a1318; border:1px solid #1e3040; color:#c8d8d8; padding:0.4rem 0.6rem; border-radius:3px; font-size:0.75rem; width:100%;" />
              </div>
            </div>

            <div style="background:#001833; border:1px solid #1e3040; border-radius:4px; padding:0.75rem; font-size:0.7rem; color:#607070; line-height:1.6;">
              Package will include:<br/>
              • Cryptographically chained audit log (JSON Lines)<br/>
              • Merkle tree integrity proof<br/>
              • Evidence locker manifest<br/>
              • Compliance posture snapshot for <strong style="color:#0099ff;">{selectedFw()}</strong>
            </div>

            <button onClick={generatePackage} disabled={generating()}
              style={`background:#0099ff; color:#080f12; border:none; padding:0.6rem 1.25rem; border-radius:3px; cursor:${generating() ? 'wait' : 'pointer'}; font-weight:700; font-size:0.78rem; letter-spacing:0.1em; opacity:${generating() ? '0.6' : '1'};`}>
              {generating() ? 'GENERATING…' : `↓ GENERATE ${selectedFw()} PACKAGE`}
            </button>
          </div>
        </div>
      </Show>
    </div>
  );
}
