// frontend/src/components/layout/CommandRail.svelte
<!--
  OBLIVRA — CommandRail (Svelte 5)
  Vertical navigation rail with all 60+ route items, organized into sections.
  Context-aware: hides desktop-only items in browser mode and vice versa.
-->
<script lang="ts">
  import { appStore } from '@lib/stores/app.svelte';
  import { push } from '@lib/router.svelte';
  import { IS_DESKTOP, IS_BROWSER, IS_HYBRID, isRouteAvailable } from '@lib/context';
  import type { NavTab } from '@lib/types';

  // ── Route map ──────────────────────────────────────────────────────────
  const routeMap: Record<string, string> = {
    dashboard: '/dashboard', siem: '/siem', alerts: '/alerts',
    'alert-management': '/alert-management', 'siem-search': '/siem-search',
    topology: '/topology', health: '/monitoring', ops: '/ops',
    response: '/response', escalation: '/escalation',
    'playbook-builder': '/playbook-builder', ueba: '/ueba',
    'ueba-overview': '/ueba-overview', 'threat-hunter': '/threat-hunter',
    'threat-intel-dashboard': '/threat-intel-dashboard', enrichment: '/enrichment',
    ndr: '/ndr', 'ndr-overview': '/ndr-overview', 'purple-team': '/purple-team',
    graph: '/graph', ransomware: '/ransomware', 'ransomware-ui': '/ransomware-ui',
    simulation: '/simulation', compliance: '/compliance', vault: '/vault',
    'war-mode': '/war-mode', forensics: '/forensics',
    'remote-forensics': '/remote-forensics', security: '/trust',
    temporal: '/temporal-integrity', lineage: '/lineage',
    decisions: '/decisions', ledger: '/ledger', replay: '/response-replay',
    plugins: '/plugins', executive: '/executive', settings: '/workspace',
    'ai-assistant': '/ai-assistant', 'mitre-heatmap': '/mitre-heatmap',
    license: '/license', team: '/team', hosts: '/hosts',
    terminal: '/terminal', tunnels: '/tunnels', recordings: '/recordings',
    snippets: '/snippets', notes: '/notes', sync: '/sync',
    agents: '/agents', 'fleet-management': '/fleet-management',
    identity: '/identity', 'identity-admin': '/identity-admin', soc: '/soc',
  };

  type NavContext = 'both' | 'desktop' | 'browser';

  interface NavItem {
    id: string;
    icon: string;
    label: string;
    context?: NavContext;
    urgent?: boolean;
  }

  function isItemVisible(item: NavItem): boolean {
    const ctx = item.context ?? 'both';
    if (ctx === 'both') return true;
    if (ctx === 'desktop') return IS_DESKTOP || IS_HYBRID;
    if (ctx === 'browser') return IS_BROWSER || IS_HYBRID;
    return true;
  }

  function go(id: string) {
    appStore.setActiveNavTab(id as NavTab);
    const route = routeMap[id];
    if (route) push(route);
  }

  // ── Icon map (SVG path data) ──────────────────────────────────────────
  const icons: Record<string, string> = {
    dashboard: 'M3 3h7v9H3zM14 3h7v5h-7zM14 12h7v9h-7zM3 16h7v5H3z',
    siem: 'M2 3h6a4 4 0 014 4v14a3 3 0 00-3-3H2zM22 3h-6a4 4 0 00-4 4v14a3 3 0 013-3h7z',
    alerts: 'M18 8A6 6 0 006 8c0 7-3 9-3 9h18s-3-2-3-9M13.73 21a2 2 0 01-3.46 0',
    terminal: 'M2 4h20v16H2zM8 10l3 2-3 2M13 15h3',
    hosts: 'M4 4h16v6H4zM4 14h16v6H4z',
    topology: 'M12 12m-3 0a3 3 0 106 0 3 3 0 10-6 0M5 18m-2 0a2 2 0 104 0 2 2 0 10-4 0M19 18m-2 0a2 2 0 104 0 2 2 0 10-4 0',
    health: 'M22 12h-4l-3 9L9 3l-3 9H2',
    ops: 'M18 20V10M12 20V4M6 20v-4',
    tunnels: 'M12 2a10 10 0 100 20 10 10 0 000-20M2 12h20',
    snippets: 'M16 18l6-6-6-6M8 6l-6 6 6 6',
    recordings: 'M12 2a10 10 0 100 20 10 10 0 000-20M12 8a4 4 0 100 8 4 4 0 000-8',
    notes: 'M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8zM14 2v6h6M16 13H8M16 17H8',
    sync: 'M23 4v6h-6M1 20v-6h6',
    plugins: 'M21 16V8l-9-5-9 5v8l9 5 9-5z',
    compliance: 'M9 11l3 3L22 4M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11',
    vault: 'M3 11h18v11H3zM7 11V7a5 5 0 0110 0v4',
    settings: 'M12 15a3 3 0 100-6 3 3 0 000 6z',
    security: 'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z',
    forensics: 'M11 19a8 8 0 100-16 8 8 0 000 16zM21 21l-4.35-4.35',
    agents: 'M4 4h16v16H4zM9 9h.01M15 9h.01M9 15h6',
    soc: 'M3 3h18v18H3zM3 9h18M9 21V9',
    ueba: 'M16 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2M8.5 11a4 4 0 100-8 4 4 0 000 8M20 8v6M23 11h-6',
    hunter: 'M11 19a8 8 0 100-16 8 8 0 000 16zM21 21l-4.35-4.35M8 11h6M11 8v6',
    ndr: 'M6 9a3 3 0 100-6 3 3 0 000 6zM18 9a3 3 0 100-6 3 3 0 000 6zM6 21a3 3 0 100-6 3 3 0 000 6zM18 21a3 3 0 100-6 3 3 0 000 6z',
    purple: 'M13 2L3 14h9l-1 8 10-12h-9l1-8z',
    graph: 'M12 8a3 3 0 100-6 3 3 0 000 6zM5 22a3 3 0 100-6 3 3 0 000 6zM19 22a3 3 0 100-6 3 3 0 000 6z',
    war: 'M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z',
    response: 'M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1zM4 22v-7',
    executive: 'M12 20V10M18 20V4M6 20v-4',
    ai: 'M12 2a10 10 0 100 20h10M12 12L2.69 7.11M12 12l4.89 8.69',
    mitre: 'M3 3h18v18H3zM3 9h18M3 15h18M9 3v18M15 3v18',
    identity: 'M3 4h18v16H3zM9 12a2 2 0 100-4 2 2 0 000 4M15 8h2M15 12h2M7 16h10',
    audit: 'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10zM9 12l2 2 4-4',
  };

  // ── Nav sections ──────────────────────────────────────────────────────
  const observe: NavItem[] = [
    { id: 'dashboard', icon: 'dashboard', label: 'Dash' },
    { id: 'siem', icon: 'siem', label: 'SIEM' },
    { id: 'siem-search', icon: 'hunter', label: 'Search', context: 'browser' },
    { id: 'alerts', icon: 'alerts', label: 'Alerts' },
    { id: 'alert-management', icon: 'alerts', label: 'AlertMgr', context: 'browser' },
    { id: 'recordings', icon: 'recordings', label: 'Recs', context: 'desktop' },
    { id: 'topology', icon: 'topology', label: 'Net' },
    { id: 'mitre-heatmap', icon: 'mitre', label: 'Mitre' },
    { id: 'health', icon: 'health', label: 'Health' },
  ];

  const operate: NavItem[] = [
    { id: 'terminal', icon: 'terminal', label: 'Shell', context: 'desktop' },
    { id: 'tunnels', icon: 'tunnels', label: 'Tunnels', context: 'desktop' },
    { id: 'hosts', icon: 'hosts', label: 'Hosts' },
    { id: 'agents', icon: 'agents', label: 'Agents', context: 'browser' },
    { id: 'fleet-management', icon: 'agents', label: 'Fleet', context: 'browser' },
    { id: 'ops', icon: 'ops', label: 'Ops' },
    { id: 'soc', icon: 'soc', label: 'SOC', context: 'browser' },
    { id: 'escalation', icon: 'response', label: 'Escalate', context: 'browser' },
    { id: 'playbook-builder', icon: 'purple', label: 'Playbooks', context: 'browser' },
    { id: 'snippets', icon: 'snippets', label: 'Snips', context: 'desktop' },
    { id: 'notes', icon: 'notes', label: 'Notes', context: 'desktop' },
    { id: 'ai-assistant', icon: 'ai', label: 'AI Shell' },
    { id: 'response', icon: 'response', label: 'SOAR' },
  ];

  const intel: NavItem[] = [
    { id: 'ueba', icon: 'ueba', label: 'UEBA' },
    { id: 'ueba-overview', icon: 'ueba', label: 'UEBA+', context: 'browser' },
    { id: 'threat-hunter', icon: 'hunter', label: 'Hunt' },
    { id: 'threat-intel-dashboard', icon: 'security', label: 'TI', context: 'browser' },
    { id: 'enrichment', icon: 'forensics', label: 'Enrich', context: 'browser' },
    { id: 'ndr', icon: 'ndr', label: 'NDR' },
    { id: 'ndr-overview', icon: 'ndr', label: 'NDR+', context: 'browser' },
    { id: 'purple-team', icon: 'purple', label: 'Purple' },
    { id: 'graph', icon: 'graph', label: 'Graph' },
  ];

  const govern: NavItem[] = [
    { id: 'compliance', icon: 'compliance', label: 'Comply' },
    { id: 'vault', icon: 'vault', label: 'Vault' },
    { id: 'identity', icon: 'identity', label: 'Users', context: 'browser' },
    { id: 'identity-admin', icon: 'identity', label: 'IdAdmin', context: 'browser' },
    { id: 'security', icon: 'security', label: 'Trust' },
    { id: 'forensics', icon: 'forensics', label: 'Forensics' },
    { id: 'remote-forensics', icon: 'forensics', label: 'RemForen', context: 'browser' },
    { id: 'ransomware', icon: 'war', label: 'Ransom' },
    { id: 'ransomware-ui', icon: 'war', label: 'RansomW', context: 'browser' },
    { id: 'war-mode', icon: 'war', label: 'WarMode' },
  ];

  const system: NavItem[] = [
    { id: 'executive', icon: 'executive', label: 'Exec' },
    { id: 'plugins', icon: 'plugins', label: 'Plugins' },
    { id: 'sync', icon: 'sync', label: 'Sync', context: 'desktop' },
    { id: 'license', icon: 'vault', label: 'License' },
    { id: 'settings', icon: 'settings', label: 'Config' },
  ];

  const auditItems = [
    { id: 'temporal', label: 'Temporal Integrity' },
    { id: 'lineage', label: 'Data Lineage' },
    { id: 'decisions', label: 'Decision Log' },
    { id: 'ledger', label: 'Evidence Ledger' },
    { id: 'replay', label: 'Response Replay' },
  ];

  let auditOpen = $state(false);
  let flyoutTop = $state(0);

  const auditActive = $derived(auditItems.some(i => i.id === appStore.activeNavTab));

  function visibleItems(items: NavItem[]) {
    return items.filter(isItemVisible);
  }
</script>

<style>
  .cr-rail {
    width: 64px;
    min-width: 64px;
    height: 100%;
    background: var(--surface-1);
    border-right: 1px solid var(--border-primary);
    display: flex;
    flex-direction: column;
    z-index: 1000;
    overflow-y: auto;
    overflow-x: hidden;
  }
  .cr-rail::-webkit-scrollbar { width: 0; }

  .cr-logo {
    height: 48px;
    display: flex;
    align-items: center;
    justify-content: center;
    border-bottom: 1px solid var(--border-primary);
    flex-shrink: 0;
  }

  .cr-nav-btn {
    position: relative;
    background: transparent;
    border: none;
    color: var(--text-muted);
    width: 100%;
    padding: 8px 0 6px 0;
    cursor: pointer;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 3px;
    transition: color 100ms ease, background 100ms ease;
    border-radius: 0;
  }
  .cr-nav-btn:hover:not(.locked) {
    color: var(--text-secondary);
    background: rgba(87, 139, 255, 0.06);
  }
  .cr-nav-btn.active {
    color: var(--accent-primary) !important;
    background: rgba(87, 139, 255, 0.12) !important;
  }
  .cr-nav-btn.active::before {
    content: '';
    position: absolute;
    left: 0;
    top: 20%;
    bottom: 20%;
    width: 3px;
    background: var(--accent-primary);
    border-radius: 0 3px 3px 0;
  }
  .cr-nav-btn.locked {
    opacity: 0.28;
    cursor: not-allowed !important;
    pointer-events: none;
  }
  .cr-nav-icon {
    width: 18px;
    height: 18px;
    opacity: 0.5;
    transition: opacity 100ms ease;
  }
  .cr-nav-btn.active .cr-nav-icon {
    opacity: 1;
    filter: drop-shadow(0 0 6px rgba(87, 139, 255, 0.4));
  }
  .cr-nav-label {
    font-family: var(--font-ui);
    font-size: 9px;
    font-weight: 500;
    text-transform: uppercase;
    letter-spacing: 0.3px;
    line-height: 1;
  }
  .cr-nav-btn.active .cr-nav-label { font-weight: 700; }

  .cr-divider {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 8px 4px 3px 4px;
    margin-top: 2px;
  }
  .cr-divider-label {
    font-family: var(--font-mono);
    font-size: 6.5px;
    font-weight: 700;
    color: var(--text-muted);
    opacity: 0.35;
    letter-spacing: 1px;
    text-transform: uppercase;
  }

  .cr-flyout {
    position: fixed;
    left: 65px;
    background: var(--surface-2);
    border: 1px solid var(--border-secondary);
    border-radius: var(--radius-md);
    z-index: 2000;
    min-width: 192px;
    padding: 4px;
    box-shadow: var(--shadow-lg);
  }
  .cr-flyout-header {
    font-family: var(--font-mono);
    font-size: 9px;
    font-weight: 800;
    color: var(--text-muted);
    padding: 8px 10px 6px 10px;
    letter-spacing: 1px;
    text-transform: uppercase;
    border-bottom: 1px solid var(--border-primary);
    margin-bottom: 4px;
  }
  .cr-flyout-item {
    display: block;
    width: 100%;
    background: transparent;
    border: none;
    border-radius: var(--radius-sm);
    color: var(--text-secondary);
    padding: 7px 10px;
    text-align: left;
    font-family: var(--font-ui);
    font-size: 12px;
    cursor: pointer;
    transition: all 100ms ease;
  }
  .cr-flyout-item:hover {
    background: var(--surface-3);
    color: var(--text-primary);
  }
  .cr-flyout-item.active {
    background: rgba(87, 139, 255, 0.12);
    color: var(--accent-primary);
    font-weight: 600;
  }
</style>

<nav class="cr-rail">
  <!-- Logo -->
  <div class="cr-logo">
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M12 2L4 6.5v11L12 22l8-4.5v-11L12 2z" stroke="var(--accent-primary)" stroke-width="1.5" fill="none"/>
      <path d="M12 6.5L7 9.25v5.5L12 17.5l5-2.75v-5.5L12 6.5z" fill="var(--accent-primary)" opacity="0.2"/>
      <circle cx="12" cy="12" r="2" fill="var(--accent-primary)"/>
    </svg>
  </div>

  <!-- OBS section -->
  <div class="cr-divider"><span class="cr-divider-label">OBS</span></div>
  {#each visibleItems(observe) as item}
    {@const route = routeMap[item.id]}
    {@const available = route ? isRouteAvailable(route) : true}
    <button
      class="cr-nav-btn"
      class:active={appStore.activeNavTab === item.id}
      class:locked={!available}
      title="{item.label}{!available ? ' — not available in this mode' : ''}"
      onclick={() => available && go(item.id)}
    >
      <div class="cr-nav-icon">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d={icons[item.icon] ?? icons.dashboard}/>
        </svg>
      </div>
      <span class="cr-nav-label">{item.label}</span>
    </button>
  {/each}

  <!-- OPS section -->
  <div class="cr-divider"><span class="cr-divider-label">OPS</span></div>
  {#each visibleItems(operate) as item}
    {@const route = routeMap[item.id]}
    {@const available = route ? isRouteAvailable(route) : true}
    <button
      class="cr-nav-btn"
      class:active={appStore.activeNavTab === item.id}
      class:locked={!available}
      title="{item.label}{!available ? ' — not available in this mode' : ''}"
      onclick={() => available && go(item.id)}
    >
      <div class="cr-nav-icon">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d={icons[item.icon] ?? icons.dashboard}/>
        </svg>
      </div>
      <span class="cr-nav-label">{item.label}</span>
    </button>
  {/each}

  <!-- INTEL section -->
  <div class="cr-divider"><span class="cr-divider-label">INTEL</span></div>
  {#each visibleItems(intel) as item}
    {@const route = routeMap[item.id]}
    {@const available = route ? isRouteAvailable(route) : true}
    <button
      class="cr-nav-btn"
      class:active={appStore.activeNavTab === item.id}
      class:locked={!available}
      title="{item.label}{!available ? ' — not available in this mode' : ''}"
      onclick={() => available && go(item.id)}
    >
      <div class="cr-nav-icon">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d={icons[item.icon] ?? icons.dashboard}/>
        </svg>
      </div>
      <span class="cr-nav-label">{item.label}</span>
    </button>
  {/each}

  <!-- GOV section -->
  <div class="cr-divider"><span class="cr-divider-label">GOV</span></div>
  {#each visibleItems(govern) as item}
    {@const route = routeMap[item.id]}
    {@const available = route ? isRouteAvailable(route) : true}
    <button
      class="cr-nav-btn"
      class:active={appStore.activeNavTab === item.id}
      class:locked={!available}
      title="{item.label}{!available ? ' — not available in this mode' : ''}"
      onclick={() => available && go(item.id)}
    >
      <div class="cr-nav-icon">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d={icons[item.icon] ?? icons.dashboard}/>
        </svg>
      </div>
      <span class="cr-nav-label">{item.label}</span>
    </button>
  {/each}

  <!-- Audit flyout trigger -->
  <button
    class="cr-nav-btn"
    class:active={auditActive}
    title="Audit Trail"
    onmouseenter={(e) => { flyoutTop = e.currentTarget.getBoundingClientRect().top; auditOpen = true; }}
  >
    <div class="cr-nav-icon">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6">
        <path d={icons.audit}/>
      </svg>
    </div>
    <span class="cr-nav-label">Audit</span>
  </button>

  {#if auditOpen}
    <div class="cr-flyout" style="top: {flyoutTop}px;" role="menu" onmouseleave={() => auditOpen = false}>
      <div class="cr-flyout-header">AUDIT TRAIL</div>
      {#each auditItems as item}
        <button
          class="cr-flyout-item"
          class:active={appStore.activeNavTab === item.id}
          onclick={() => { go(item.id); auditOpen = false; }}
        >
          {item.label}
        </button>
      {/each}
    </div>
  {/if}

  <!-- Spacer -->
  <div class="flex-1"></div>

  <!-- SYS section -->
  <div class="cr-divider"><span class="cr-divider-label">SYS</span></div>
  {#each visibleItems(system) as item}
    {@const route = routeMap[item.id]}
    {@const available = route ? isRouteAvailable(route) : true}
    <button
      class="cr-nav-btn"
      class:active={appStore.activeNavTab === item.id}
      class:locked={!available}
      title="{item.label}{!available ? ' — not available in this mode' : ''}"
      onclick={() => available && go(item.id)}
    >
      <div class="cr-nav-icon">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d={icons[item.icon] ?? icons.dashboard}/>
        </svg>
      </div>
      <span class="cr-nav-label">{item.label}</span>
    </button>
  {/each}

  <div class="h-2"></div>
</nav>

// frontend/src/components/layout/CommandRail.tsx
import { Component, Show, For, createSignal } from 'solid-js';
import { useApp, AppState } from '@core/store';
import { useNavigate } from '@solidjs/router';

type NavTab = AppState['activeNavTab'] | 'temporal' | 'lineage' | 'decisions' | 'ledger' | 'replay' | 'soc'
    | 'agents' | 'ueba' | 'threat-hunter' | 'ndr' | 'purple-team' | 'graph'
    | 'war-mode' | 'forensics' | 'identity' | 'response' | 'ransomware' | 'credentials'
    | 'executive' | 'simulation' | 'data-destruction' | 'risk' | 'governance' | 'features';

// ── Icons ────────────────────────────────────────────────────────────────────
const Icons = {
    SIEM:       () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 3h6a4 4 0 014 4v14a3 3 0 00-3-3H2z"/><path d="M22 3h-6a4 4 0 00-4 4v14a3 3 0 013-3h7z"/></svg>,
    Ops:        () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>,
    Topology:   () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="3"/><circle cx="5" cy="18" r="2"/><circle cx="19" cy="18" r="2"/><circle cx="5" cy="6" r="2"/><circle cx="19" cy="6" r="2"/><path d="M7 16l4-2M17 16l-4-2M7 8l4 2M17 8l-4 2"/></svg>,
    Terminal:   () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="4" width="20" height="16" rx="2"/><polyline points="8 10 11 12 8 14"/><line x1="13" y1="15" x2="16" y2="15"/></svg>,
    Hosts:      () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="4" y="4" width="16" height="6" rx="1.5"/><rect x="4" y="14" width="16" height="6" rx="1.5"/><circle cx="7" cy="7" r="1"/><circle cx="7" cy="17" r="1"/></svg>,
    Compliance: () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/></svg>,
    Vault:      () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0110 0v4"/><circle cx="12" cy="16" r="1"/></svg>,
    Settings:   () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 01-2.83 2.83l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-4 0v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83-2.83l.06-.06A1.65 1.65 0 004.68 15a1.65 1.65 0 00-1.51-1H3a2 2 0 010-4h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06A1.65 1.65 0 009 4.68a1.65 1.65 0 001-1.51V3a2 2 0 014 0v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06A1.65 1.65 0 0019.4 9a1.65 1.65 0 001.51 1H21a2 2 0 010 4h-.09a1.65 1.65 0 00-1.51 1z"/></svg>,
    Dashboard:  () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="3" width="7" height="9"/><rect x="14" y="3" width="7" height="5"/><rect x="14" y="12" width="7" height="9"/><rect x="3" y="16" width="7" height="5"/></svg>,
    Tunnels:    () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>,
    Snippets:   () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>,
    Recordings: () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="3"/></svg>,
    Notes:      () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>,
    Team:       () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>,
    Sync:       () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg>,
    Plugins:    () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>,
    Health:     () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>,
    Metrics:    () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M21.21 15.89A10 10 0 1 1 8 2.83"/><path d="M22 12A10 10 0 0 0 12 2v10z"/></svg>,
    Updater:    () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>,
    Alerts:     () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>,
    Security:   () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>,
    SOC:        () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18"/><path d="M9 21V9"/></svg>,
    Audit:      () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><polyline points="9 12 11 14 15 10"/></svg>,
    ChevronRight: () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6"/></svg>,
    // New icons for missing pages
    Agents:     () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="4" y="4" width="16" height="16" rx="2"/><line x1="9" y1="9" x2="9.01" y2="9"/><line x1="15" y1="9" x2="15.01" y2="9"/><path d="M9 15h6"/></svg>,
    UEBA:       () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="8.5" cy="7" r="4"/><path d="M20 8v6M23 11h-6"/></svg>,
    Hunter:     () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/><line x1="8" y1="11" x2="14" y2="11"/><line x1="11" y1="8" x2="11" y2="14"/></svg>,
    NDR:        () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="6" cy="6" r="3"/><circle cx="18" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="18" r="3"/><line x1="6" y1="9" x2="6" y2="15"/><line x1="18" y1="9" x2="18" y2="15"/><line x1="9" y1="6" x2="15" y2="6"/><line x1="9" y1="18" x2="15" y2="18"/></svg>,
    Purple:     () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>,
    Graph:      () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="5" r="3"/><circle cx="5" cy="19" r="3"/><circle cx="19" cy="19" r="3"/><line x1="12" y1="8" x2="5" y2="16"/><line x1="12" y1="8" x2="19" y2="16"/><line x1="8" y1="19" x2="16" y2="19"/></svg>,
    War:        () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>,
    Forensics:  () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>,
    Identity:   () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="M15 8h2M15 12h2"/><path d="M7 16h10"/></svg>,
    Response:   () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><line x1="4" y1="22" x2="4" y2="15"/></svg>,
    Executive:  () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 20V10"/><path d="M18 20V4"/><path d="M6 20v-4"/></svg>,
};

// ── Route map ─────────────────────────────────────────────────────────────────
const routeMap: Record<string, string> = {
    // OBSERVE
    dashboard:  '/dashboard',
    siem:       '/siem',
    alerts:     '/siem',  // Alerts are within SIEM
    topology:   '/topology',
    health:     '/monitoring',
    // OPERATE
    terminal:   '/terminal',
    hosts:      '/hosts',
    agents:     '/agents',
    ops:        '/ops',
    soc:        '/soc',
    tunnels:    '/terminal',
    response:   '/response',
    // INTEL
    ueba:           '/ueba',
    'threat-hunter':'/threat-hunter',
    ndr:            '/ndr',
    'purple-team':  '/purple-team',
    graph:          '/graph',
    ransomware:     '/ransomware',
    simulation:     '/simulation',
    // GOVERN
    compliance: '/compliance',
    vault:      '/vault',
    identity:   '/identity',
    'war-mode': '/war-mode',
    forensics:  '/forensics',
    security:   '/trust',
    team:       '/team',
    // AUDIT flyout
    temporal:   '/temporal-integrity',
    lineage:    '/lineage',
    decisions:  '/decisions',
    ledger:     '/ledger',
    replay:     '/response-replay',
    // SYSTEM
    plugins:    '/plugins',
    executive:  '/executive',
    settings:   '/workspace',
};

// ── Primary nav items (always visible) ───────────────────────────────────────
type PrimaryItem = { id: NavTab; icon: () => any; label: string; badge?: () => number; urgent?: boolean };

// ── Audit submenu items ───────────────────────────────────────────────────────
const auditItems: { id: NavTab; label: string }[] = [
    { id: 'temporal',  label: 'Temporal Integrity' },
    { id: 'lineage',   label: 'Data Lineage' },
    { id: 'decisions', label: 'Decision Log' },
    { id: 'ledger',    label: 'Evidence Ledger' },
    { id: 'replay',    label: 'Response Replay' },
];

// ── NavButton ─────────────────────────────────────────────────────────────────
const NavButton: Component<{
    item: PrimaryItem;
    active: boolean;
    onClick: () => void;
}> = (props) => {
    const badge = props.item.badge?.() ?? 0;
    return (
        <button
            title={props.item.label}
            onClick={props.onClick}
            style={{
                background: props.active ? 'var(--surface-2)' : 'transparent',
                border: 'none',
                'border-left': props.active ? '2px solid var(--accent-primary)' : '2px solid transparent',
                color: props.active ? 'var(--text-primary)' : 'var(--text-secondary)',
                width: '100%',
                padding: '6px 0',
                cursor: 'pointer',
                display: 'flex',
                'flex-direction': 'column',
                'align-items': 'center',
                gap: '2px',
                position: 'relative',
                transition: 'background 0.15s, color 0.15s',
            }}
        >
            <div style={{ width: '16px', height: '16px' }}>
                <props.item.icon />
            </div>
            <span style={{
                'font-family': 'var(--font-ui)',
                'font-size': '8px',
                'font-weight': props.active ? 700 : 400,
                'text-transform': 'uppercase',
                'letter-spacing': '0.3px',
                'line-height': 1,
            }}>
                {props.item.label}
            </span>
            <Show when={badge > 0}>
                <div style={{
                    position: 'absolute',
                    top: '2px',
                    right: '6px',
                    background: props.item.urgent ? 'var(--alert-critical)' : 'var(--accent-primary)',
                    color: '#fff',
                    'font-family': 'var(--font-mono)',
                    'font-size': '7px',
                    'font-weight': 800,
                    padding: '1px 3px',
                    'line-height': 1,
                    'min-width': '12px',
                    'text-align': 'center',
                }}>
                    {badge}
                </div>
            </Show>
        </button>
    );
};

// ── AuditFlyout ───────────────────────────────────────────────────────────────
const AuditFlyout: Component<{
    active: boolean;
    currentTab: string;
    onSelect: (id: NavTab) => void;
    onClose: () => void;
}> = (props) => (
    <div
        style={{
            position: 'fixed',
            left: '64px',
            top: 'auto',
            background: 'var(--surface-1)',
            border: '1px solid var(--border-primary)',
            'border-left': '2px solid var(--accent-primary)',
            'z-index': 2000,
            'min-width': '180px',
            padding: '4px 0',
        }}
        onMouseLeave={props.onClose}
    >
        <div style={{
            'font-family': 'var(--font-mono)',
            'font-size': '9px',
            'font-weight': 800,
            color: 'var(--text-muted)',
            padding: '6px 12px 4px 12px',
            'letter-spacing': '1px',
            'text-transform': 'uppercase',
            'border-bottom': '1px solid var(--border-primary)',
            'margin-bottom': '2px',
        }}>
            AUDIT TRAIL
        </div>
        <For each={auditItems}>
            {(item) => (
                <button
                    onClick={() => { props.onSelect(item.id); props.onClose(); }}
                    style={{
                        display: 'block',
                        width: '100%',
                        background: props.currentTab === item.id ? 'var(--surface-2)' : 'transparent',
                        border: 'none',
                        'border-left': props.currentTab === item.id ? '2px solid var(--accent-primary)' : '2px solid transparent',
                        color: props.currentTab === item.id ? 'var(--text-primary)' : 'var(--text-secondary)',
                        padding: '8px 12px',
                        'text-align': 'left',
                        'font-family': 'var(--font-ui)',
                        'font-size': '11px',
                        cursor: 'pointer',
                    }}
                >
                    {item.label}
                </button>
            )}
        </For>
    </div>
);

// ── Divider ───────────────────────────────────────────────────────────────────
const Divider: Component<{ label: string }> = (props) => (
    <div style={{
        'font-family': 'var(--font-mono)',
        'font-size': '7px',
        'font-weight': 800,
        color: 'var(--text-muted)',
        'text-align': 'center',
        padding: '6px 0 3px 0',
        opacity: 0.5,
        'letter-spacing': '0.8px',
        'border-top': '1px solid var(--border-primary)',
        'margin-top': '2px',
    }}>
        {props.label}
    </div>
);

// ── CommandRail ───────────────────────────────────────────────────────────────
export const CommandRail: Component = () => {
    const [state, actions] = useApp();
    const navigate = useNavigate();
    const [auditOpen, setAuditOpen] = createSignal(false);
    const [flyoutTop, setFlyoutTop] = createSignal(0);

    const go = (id: NavTab) => {
        actions.setActiveNavTab(id as any);
        const route = routeMap[id as string];
        if (route) navigate(route);
    };

    const auditActive = () => auditItems.some(i => i.id === state.activeNavTab);

    // ── OBSERVE — Monitoring & Detection ──────────────────────────────────
    const observe: PrimaryItem[] = [
        { id: 'dashboard', icon: Icons.Dashboard, label: 'Dash' },
        { id: 'siem',      icon: Icons.SIEM,      label: 'SIEM' },
        { id: 'alerts',    icon: Icons.Alerts,     label: 'Alerts',
          badge: () => state.notifications.filter((n: any) => n.type === 'error').length,
          urgent: true },
        { id: 'topology',  icon: Icons.Topology,   label: 'Net' },
        { id: 'health',    icon: Icons.Health,      label: 'Health' },
    ];

    // ── OPERATE — Hands-on Infrastructure ─────────────────────────────────
    const operate: PrimaryItem[] = [
        { id: 'terminal',  icon: Icons.Terminal,  label: 'Shell' },
        { id: 'hosts',     icon: Icons.Hosts,     label: 'Hosts' },
        { id: 'agents',    icon: Icons.Agents,    label: 'Agents' },
        { id: 'ops',       icon: Icons.Ops,       label: 'Ops' },
        { id: 'soc',       icon: Icons.SOC,       label: 'SOC' },
        { id: 'response',  icon: Icons.Response,  label: 'SOAR' },
    ];

    // ── INTEL — Threat Intelligence & Hunting ─────────────────────────────
    const intel: PrimaryItem[] = [
        { id: 'ueba',           icon: Icons.UEBA,     label: 'UEBA' },
        { id: 'threat-hunter',  icon: Icons.Hunter,   label: 'Hunt' },
        { id: 'ndr',            icon: Icons.NDR,      label: 'NDR' },
        { id: 'purple-team',    icon: Icons.Purple,   label: 'Purple' },
        { id: 'graph',          icon: Icons.Graph,     label: 'Graph' },
    ];

    // ── GOVERN — Compliance, Identity, Security ───────────────────────────
    const govern: PrimaryItem[] = [
        { id: 'compliance',  icon: Icons.Compliance, label: 'Comply' },
        { id: 'vault',       icon: Icons.Vault,      label: 'Vault' },
        { id: 'identity',    icon: Icons.Identity,   label: 'Users' },
        { id: 'security',    icon: Icons.Security,   label: 'Trust' },
        { id: 'forensics',   icon: Icons.Forensics,  label: 'Forensic' },
        { id: 'war-mode',    icon: Icons.War,        label: 'WarMode' },
    ];

    // ── SYSTEM — Configuration & Admin ────────────────────────────────────
    const system: PrimaryItem[] = [
        { id: 'executive', icon: Icons.Executive, label: 'Exec' },
        { id: 'plugins',   icon: Icons.Plugins,   label: 'Plugin' },
        { id: 'settings',  icon: Icons.Settings,  label: 'Config' },
    ];

    return (
        <nav style={{
            width: '64px',
            'min-width': '64px',
            height: '100%',
            background: 'var(--surface-1)',
            'border-right': '1px solid var(--border-primary)',
            display: 'flex',
            'flex-direction': 'column',
            'padding-top': '4px',
            'z-index': 1000,
            'overflow-y': 'auto',
            'overflow-x': 'hidden',
        }}>
            {/* Wordmark */}
            <div style={{
                'font-family': 'var(--font-mono)',
                'font-weight': 800,
                color: 'var(--accent-primary)',
                'font-size': '10px',
                'text-align': 'center',
                padding: '4px 0 8px 0',
                'letter-spacing': '2px',
                'border-bottom': '1px solid var(--border-primary)',
                'margin-bottom': '2px',
            }}>
                OBV
            </div>

            {/* OBSERVE */}
            <Divider label="OBS" />
            <For each={observe}>
                {(item) => (
                    <NavButton
                        item={item}
                        active={state.activeNavTab === item.id}
                        onClick={() => go(item.id)}
                    />
                )}
            </For>

            {/* OPERATE */}
            <Divider label="OPS" />
            <For each={operate}>
                {(item) => (
                    <NavButton
                        item={item}
                        active={state.activeNavTab === item.id}
                        onClick={() => go(item.id)}
                    />
                )}
            </For>

            {/* INTEL */}
            <Divider label="INTEL" />
            <For each={intel}>
                {(item) => (
                    <NavButton
                        item={item}
                        active={state.activeNavTab === item.id}
                        onClick={() => go(item.id)}
                    />
                )}
            </For>

            {/* GOVERN */}
            <Divider label="GOV" />
            <For each={govern}>
                {(item) => (
                    <NavButton
                        item={item}
                        active={state.activeNavTab === item.id}
                        onClick={() => go(item.id)}
                    />
                )}
            </For>

            {/* AUDIT — single entry that opens flyout */}
            <button
                title="Audit Trail"
                onMouseEnter={(e) => {
                    setFlyoutTop(e.currentTarget.getBoundingClientRect().top);
                    setAuditOpen(true);
                }}
                style={{
                    background: auditActive() ? 'var(--surface-2)' : 'transparent',
                    border: 'none',
                    'border-left': auditActive() ? '2px solid var(--accent-primary)' : '2px solid transparent',
                    color: auditActive() ? 'var(--text-primary)' : 'var(--text-secondary)',
                    width: '100%',
                    padding: '6px 0',
                    cursor: 'pointer',
                    display: 'flex',
                    'flex-direction': 'column',
                    'align-items': 'center',
                    gap: '2px',
                    position: 'relative',
                }}
            >
                <div style={{ width: '16px', height: '16px' }}>
                    <Icons.Audit />
                </div>
                <span style={{
                    'font-family': 'var(--font-ui)',
                    'font-size': '8px',
                    'font-weight': auditActive() ? 700 : 400,
                    'text-transform': 'uppercase',
                    'letter-spacing': '0.3px',
                    'line-height': 1,
                }}>
                    Audit
                </span>
                <div style={{ position: 'absolute', right: '2px', top: '50%', transform: 'translateY(-50%)', width: '8px', height: '8px', opacity: 0.4 }}>
                    <Icons.ChevronRight />
                </div>
            </button>

            <Show when={auditOpen()}>
                <div style={{ position: 'fixed', left: '64px', top: `${flyoutTop()}px`, 'z-index': 2000 }}>
                    <AuditFlyout
                        active={auditActive()}
                        currentTab={state.activeNavTab as string}
                        onSelect={go}
                        onClose={() => setAuditOpen(false)}
                    />
                </div>
            </Show>

            {/* Push system to bottom */}
            <div style={{ flex: 1 }} />

            {/* SYSTEM */}
            <Divider label="SYS" />
            <For each={system}>
                {(item) => (
                    <NavButton
                        item={item}
                        active={state.activeNavTab === item.id}
                        onClick={() => go(item.id)}
                    />
                )}
            </For>
            <div style={{ height: '4px' }} />
        </nav>
    );
};
