// frontend/src/components/layout/StatusBar.svelte
<!--
  OBLIVRA — StatusBar (Svelte 5)
  Bottom status bar showing session info, vault status, health grade, and clock.
-->
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { appStore } from '@lib/stores/app.svelte';
  import { IS_BROWSER, APP_CONTEXT, IS_DESKTOP, IS_HYBRID } from '@lib/context';
  import { subscribe } from '@lib/bridge';

  interface Props {
    onToggleTransfers?: () => void;
  }

  let { onToggleTransfers }: Props = $props();

  let time = $state('');
  let diagGrade = $state<string | null>(null);

  const activeCount = $derived(appStore.sessions.filter(s => s.status === 'active').length);
  const transferCount = $derived(appStore.transfers.filter(t => t.status === 'active' || t.status === 'pending').length);

  const activeHost = $derived.by(() => {
    if (!appStore.activeSessionId) return null;
    const session = appStore.sessions.find(s => s.id === appStore.activeSessionId);
    if (!session) return null;
    return { id: session.hostId, label: session.hostLabel || session.hostId };
  });

  const contextLabel: Record<string, string> = {
    desktop: 'DESKTOP',
    browser: 'BROWSER',
    hybrid:  'HYBRID',
  };

  const contextColor: Record<string, string> = {
    desktop: 'bg-status-online',
    browser: 'bg-accent',
    hybrid:  'bg-warning',
  };

  let timer: ReturnType<typeof setInterval>;
  let unsubDiag: (() => void) | undefined;

  onMount(() => {
    // Clock
    const updateTime = () => {
      time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    };
    updateTime();
    timer = setInterval(updateTime, 30_000);

    // Diagnostics health grade
    unsubDiag = subscribe('diagnostics:snapshot', (data: any) => {
      if (data?.health_grade) diagGrade = data.health_grade;
    });
  });

  onDestroy(() => {
    clearInterval(timer);
    unsubDiag?.();
  });
</script>

<footer class="flex items-center justify-between h-6 bg-surface-1 border-t border-border-primary px-3 text-[10px] font-mono text-text-muted font-medium tracking-wide shrink-0 z-50">
  <!-- Left cluster -->
  <div class="flex items-center gap-2.5">
    <!-- Context badge -->
    <div class="flex items-center gap-1.5">
      <span class="w-1.5 h-1.5 rounded-full {contextColor[APP_CONTEXT]}"></span>
      <span class="text-[8px] font-bold uppercase tracking-widest opacity-60">{contextLabel[APP_CONTEXT]}</span>
    </div>

    <span class="text-border-secondary font-mono">|</span>

    <!-- Active session -->
    <span
      class="inline-block w-[5px] h-[5px] rounded-full shrink-0"
      style="background: {activeHost ? 'var(--status-online)' : 'var(--text-muted)'}; box-shadow: {activeHost ? '0 0 6px var(--status-online)' : 'none'};"
    ></span>
    <span class="text-{activeHost ? 'text-secondary' : 'text-muted'}">
      {activeHost ? activeHost.label : 'no active session'}
    </span>
  </div>

  <!-- Right cluster -->
  <div class="flex items-center gap-2.5">
    <!-- Plugin status icons -->
    {#each appStore.pluginStatusIcons as icon}
      <span title="{icon.plugin_id}: {icon.tooltip}" class="cursor-help opacity-70">{icon.icon}</span>
    {/each}

    <!-- Transfer count -->
    {#if transferCount > 0}
      <button
        class="text-accent cursor-pointer bg-transparent border-none font-mono text-[10px] p-0"
        onclick={() => onToggleTransfers?.()}
      >⇅ {transferCount} xfer</button>
      <span class="text-border-secondary font-mono">|</span>
    {/if}

    <!-- Session / host counts -->
    <span>
      <span class="text-text-muted">{activeCount}</span>
      <span class="opacity-35"> sess · </span>
      <span class="text-text-muted">{appStore.hosts.length}</span>
      <span class="opacity-35"> hosts</span>
    </span>

    <span class="text-border-secondary font-mono">|</span>

    <!-- Health grade -->
    {#if diagGrade}
      <span
        class="font-mono text-[9px] font-extrabold tracking-wider cursor-pointer hover:opacity-70"
        style="color: {diagGrade === 'A' ? 'var(--status-online)' : diagGrade === 'B' ? '#d29922' : diagGrade === 'C' ? '#f0883e' : '#f85149'};"
        title="Platform health"
      >● {diagGrade}</span>
      <span class="text-border-secondary font-mono">|</span>
    {/if}

    <!-- Vault status -->
    {#if appStore.vaultUnlocked}
      <span class="text-accent">● secure</span>
    {:else}
      <span class="text-text-muted opacity-40">locked</span>
    {/if}

    <span class="text-border-secondary font-mono">|</span>

    <!-- Clock -->
    <span class="text-text-secondary font-semibold tracking-wider">{time}</span>
  </div>
</footer>

// frontend/src/components/layout/StatusBar.tsx
import { Component, createMemo, createSignal, onMount, onCleanup, Show, For } from 'solid-js';
import { useApp } from '@core/store';
import { IS_BROWSER } from '@core/context';
import { subscribe } from '@core/bridge';
import { usePanelManager } from './PanelManager';
import { DiagnosticsModal } from '../monitoring/DiagnosticsModal';
import { ContextBadge } from './ContextBadge';

export const StatusBar: Component<{ onToggleTransfers?: () => void }> = (props) => {
    const [state] = useApp();
    const activeCount = () => state.sessions.filter((s) => s.status === 'active').length;
    const transferCount = () => state.transfers.filter(t => t.status === 'active' || t.status === 'pending').length;
    const [time, setTime] = createSignal('');
    const [healthMap, setHealthMap] = createSignal<Record<string, unknown>>({});
    const [diagGrade, setDiagGrade] = createSignal<string | null>(null);
    const [showDiag, setShowDiag] = createSignal(false);
    const { openPanelCount } = usePanelManager();

    // Subscribe to diagnostics broadcast for live health grade in status bar
    // subscribe() is a no-op in browser mode so this is safe everywhere
    let unsubDiag: (() => void) | undefined;
    onMount(() => {
        unsubDiag = subscribe('diagnostics:snapshot', (data: any) => {
            if (data?.health_grade) setDiagGrade(data.health_grade);
        });
    });
    onCleanup(() => unsubDiag?.());

    const activeHost = createMemo(() => {
        if (!state.activeSessionId) return null;
        const session = state.sessions.find(s => s.id === state.activeSessionId);
        if (!session) return null;
        return {
            id: session.hostId,
            label: session.hostLabel || session.hostId
        };
    });

    const activeLatency = createMemo(() => {
        const host = activeHost();
        if (!host || !(healthMap()[host.id] as any)?.latency_ms) return null;
        return (healthMap()[host.id] as any).latency_ms;
    });

    let timer: ReturnType<typeof setInterval>;

    onMount(() => {
        const updateTimeAndHealth = async () => {
            setTime(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
            // GetAllHealth is a Wails binding — only call it in desktop/hybrid mode
            if (!IS_BROWSER) {
                try {
                    const { GetAllHealth } = await import('../../../wailsjs/go/services/HealthService');
                    const h = await GetAllHealth();
                    setHealthMap(h || {});
                } catch { /* ignore in statusbar */ }
            }
        };
        updateTimeAndHealth();
        timer = setInterval(updateTimeAndHealth, 30_000);
    });

    onCleanup(() => clearInterval(timer));

    const sep = () => <span style="color: var(--border-secondary); font-family: var(--font-mono);">|</span>;

    return (
    <>
        <footer style="
            display: flex;
            align-items: center;
            justify-content: space-between;
            height: 24px;
            background: var(--surface-1);
            border-top: 1px solid var(--border-primary);
            padding: 0 12px;
            font-size: 10px;
            font-family: var(--font-mono);
            color: var(--text-muted);
            font-weight: 500;
            letter-spacing: 0.3px;
            flex-shrink: 0;
            z-index: 50;
        ">
            {/* Left cluster */}
            <div style="display: flex; align-items: center; gap: 10px;">
                <ContextBadge />
                {sep()}
                <span style={`
                    display: inline-block;
                    width: 5px;
                    height: 5px;
                    border-radius: 50%;
                    background: ${activeHost() ? 'var(--status-online)' : 'var(--text-muted)'};
                    box-shadow: ${activeHost() ? '0 0 6px var(--status-online)' : 'none'};
                    flex-shrink: 0;
                `} />
                <span style={`color: ${activeHost() ? 'var(--text-secondary)' : 'var(--text-muted)'}`}>
                    {activeHost() ? activeHost()?.label : 'no active session'}
                </span>
                <Show when={activeLatency() !== null}>
                    {sep()}
                    <span style="color: var(--text-muted);">{activeLatency()}ms</span>
                </Show>
            </div>

            {/* Right cluster */}
            <div style="display: flex; align-items: center; gap: 10px;">
                <For each={state.pluginStatusIcons}>
                    {(icon: any) => (
                        <span title={`${icon.plugin_id}: ${icon.tooltip}`} style="cursor: help; opacity: 0.7;">{icon.icon}</span>
                    )}
                </For>

                <Show when={transferCount() > 0}>
                    <span
                        style="color: var(--accent-primary); cursor: pointer;"
                        onClick={props.onToggleTransfers}
                    >⇅ {transferCount()} xfer</span>
                    {sep()}
                </Show>

                <span>
                    <span style="color: var(--text-muted);">{activeCount()}</span>
                    <span style="opacity: 0.35;"> sess · </span>
                    <span style="color: var(--text-muted);">{state.hosts.length}</span>
                    <span style="opacity: 0.35;"> hosts</span>
                </span>

                <Show when={openPanelCount() > 0}>
                    {sep()}
                    <span style="color: var(--accent-primary); font-weight: 700;">{openPanelCount()} panel{openPanelCount() === 1 ? '' : 's'}</span>
                </Show>

                {sep()}

                <Show when={diagGrade()}>
                    <span
                        title="Platform health — click to open diagnostics"
                        onClick={() => setShowDiag(true)}
                        style={{
                            'font-family': 'var(--font-mono)',
                            'font-size': '9px',
                            'font-weight': '800',
                            'letter-spacing': '0.5px',
                            cursor: 'pointer',
                            color: diagGrade() === 'A' ? 'var(--status-online)'
                                 : diagGrade() === 'B' ? '#d29922'
                                 : diagGrade() === 'C' ? '#f0883e'
                                 : '#f85149',
                        }}
                        onMouseEnter={e => (e.currentTarget as HTMLElement).style.opacity = '0.7'}
                        onMouseLeave={e => (e.currentTarget as HTMLElement).style.opacity = '1'}
                    >
                        ● {diagGrade()}
                    </span>
                    {sep()}
                </Show>

                <Show
                    when={state.vaultUnlocked}
                    fallback={<span style="color: var(--text-muted); opacity: 0.4;">locked</span>}
                >
                    <span style="color: var(--accent-primary);">&#9679; secure</span>
                </Show>

                {sep()}

                <span style="color: var(--text-secondary); font-weight: 600; letter-spacing: 0.5px;">{time()}</span>
            </div>
        </footer>

        <Show when={showDiag()}>
            <DiagnosticsModal onClose={() => setShowDiag(false)} />
        </Show>
    </>
    );
};
