// frontend/src/lib/components/StatusBar.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { ping, type Health } from '../bridge';

  let health = $state<Health | null>(null);
  let uptime = $state(0);
  let timer: ReturnType<typeof setInterval> | null = null;

  async function tick() {
    try {
      health = await ping();
    } catch (err) {
      health = { status: 'error', timestamp: new Date().toISOString() };
    }
    uptime++;
  }

  onMount(() => {
    void tick();
    timer = setInterval(() => void tick(), 5000);
  });

  onDestroy(() => {
    if (timer) clearInterval(timer);
  });

  const statusColor = $derived(
    health?.status === 'ok'    ? 'var(--color-sig-ok)' :
    health?.status === 'error' ? 'var(--color-sig-error)' :
                                 'var(--color-sig-warn)'
  );
  const statusLabel = $derived(health?.status?.toUpperCase() ?? 'CONNECTING');
</script>

<footer
  class="flex h-7 items-center justify-between border-t border-base-700 px-4"
  style="background: var(--color-base-900); flex-shrink: 0;"
>
  <!-- Left cluster -->
  <div class="flex items-center gap-4">
    <!-- Health dot + label -->
    <span class="flex items-center gap-1.5">
      <span
        class={health?.status === 'ok' ? 'animate-glow' : health?.status === 'error' ? 'animate-glow-err' : 'animate-glow-warn'}
        style="display:inline-block; width:6px; height:6px; border-radius:50%; background:{statusColor};"
      ></span>
      <span style="font-family:'Share Tech Mono',monospace; font-size:10px; letter-spacing:1px; color:{statusColor};">{statusLabel}</span>
    </span>

    <span style="color:var(--color-base-600);">·</span>

    <!-- Ping timestamp -->
    {#if health?.timestamp}
      <span style="font-family:'Share Tech Mono',monospace; font-size:10px; letter-spacing:0.5px; color:var(--color-base-300);">
        LAST PING {new Date(health.timestamp).toLocaleTimeString()}
      </span>
    {/if}
  </div>

  <!-- Right cluster -->
  <div class="flex items-center gap-3" style="font-family:'Share Tech Mono',monospace; font-size:10px; letter-spacing:1px; color:var(--color-base-300);">
    <span style="color:var(--color-cyan-500); opacity:0.6;">OBLIVRA</span>
    <span style="color:var(--color-base-600);">·</span>
    <span>PHASE 0</span>
    <span style="color:var(--color-base-600);">·</span>
    <span style="color:var(--color-base-200);">v0.1.0</span>
    <span style="color:var(--color-base-600);">·</span>
    <span>SOVEREIGN LOG PLATFORM</span>
  </div>
</footer>

// frontend/src/components/layout/StatusBar.tsx
import { Component, createMemo, createSignal, onMount, onCleanup, Show, For } from 'solid-js';
import { useApp } from '@core/store';
import { GetAllHealth } from '../../../wailsjs/go/app/HealthService';

export const StatusBar: Component<{ onToggleTransfers?: () => void }> = (props) => {
    const [state] = useApp();
    const activeCount = () => state.sessions.filter((s) => s.status === 'active').length;
    const transferCount = () => state.transfers.filter(t => t.status === 'active' || t.status === 'pending').length;
    const [time, setTime] = createSignal('');
    const [healthMap, setHealthMap] = createSignal<Record<string, unknown>>({});

    const activeHost = createMemo(() => {
        if (!state.activeSessionId) return null;
        const session = state.sessions.find(s => s.id === state.activeSessionId);
        if (!session) return null;
        return {
            id: session.hostId,
            label: session.hostLabel || session.hostId
        };
    });

    const activeLatency = createMemo(() => {
        const host = activeHost();
        if (!host || !(healthMap()[host.id] as any)?.latency_ms) return null;
        return (healthMap()[host.id] as any).latency_ms;
    });

    let timer: ReturnType<typeof setInterval>;

    onMount(() => {
        const updateTimeAndHealth = async () => {
            setTime(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
            try {
                const h = await GetAllHealth();
                setHealthMap(h || {});
            } catch { /* ignore in statusbar */ }
        };
        updateTimeAndHealth();
        timer = setInterval(updateTimeAndHealth, 30_000);
    });

    onCleanup(() => clearInterval(timer));

    const sep = () => <span style="color: var(--border-secondary); font-family: var(--font-mono);">|</span>;

    return (
        <footer style="
            display: flex;
            align-items: center;
            justify-content: space-between;
            height: 24px;
            background: var(--surface-1);
            border-top: 1px solid var(--border-primary);
            padding: 0 12px;
            font-size: 10px;
            font-family: var(--font-mono);
            color: var(--text-muted);
            font-weight: 500;
            letter-spacing: 0.3px;
            flex-shrink: 0;
            z-index: 50;
        ">
            {/* Left cluster */}
            <div style="display: flex; align-items: center; gap: 10px;">
                <span style={`
                    display: inline-block;
                    width: 5px;
                    height: 5px;
                    border-radius: 50%;
                    background: ${activeHost() ? 'var(--status-online)' : 'var(--text-muted)'};
                    box-shadow: ${activeHost() ? '0 0 6px var(--status-online)' : 'none'};
                    flex-shrink: 0;
                `} />
                <span style={`color: ${activeHost() ? 'var(--text-secondary)' : 'var(--text-muted)'}`}>
                    {activeHost() ? activeHost()?.label : 'no active session'}
                </span>
                <Show when={activeLatency() !== null}>
                    {sep()}
                    <span style="color: var(--text-muted);">{activeLatency()}ms</span>
                </Show>
            </div>

            {/* Right cluster */}
            <div style="display: flex; align-items: center; gap: 10px;">
                <For each={state.pluginStatusIcons}>
                    {(icon: any) => (
                        <span title={`${icon.plugin_id}: ${icon.tooltip}`} style="cursor: help; opacity: 0.7;">{icon.icon}</span>
                    )}
                </For>

                <Show when={transferCount() > 0}>
                    <span
                        style="color: var(--accent-primary); cursor: pointer;"
                        onClick={props.onToggleTransfers}
                    >⇅ {transferCount()} xfer</span>
                    {sep()}
                </Show>

                <span>
                    <span style="color: var(--text-muted);">{activeCount()}</span>
                    <span style="opacity: 0.35;"> sess · </span>
                    <span style="color: var(--text-muted);">{state.hosts.length}</span>
                    <span style="opacity: 0.35;"> hosts</span>
                </span>

                {sep()}

                <Show
                    when={state.vaultUnlocked}
                    fallback={<span style="color: var(--text-muted); opacity: 0.4;">locked</span>}
                >
                    <span style="color: var(--accent-primary);">&#9679; secure</span>
                </Show>

                {sep()}

                <span style="color: var(--text-secondary); font-weight: 600; letter-spacing: 0.5px;">{time()}</span>
            </div>
        </footer>
    );
};
