// frontend/src/components/ui/CommandPalette.svelte
<!--
  OBLIVRA — CommandPalette (Svelte 5)
  Global command palette (Cmd+K / Cmd+P) for navigation and host discovery.
-->
<script lang="ts">
  import { fade, fly } from 'svelte/transition';
  import { appStore } from '@lib/stores/app.svelte';

  interface Props {
    open: boolean;
    onClose: () => void;
  }

  let { open, onClose }: Props = $props();

  let query = $state('');
  let selectedIndex = $state(0);
  let inputRef = $state<HTMLInputElement>();

  const results = $derived.by(() => {
    const q = query.toLowerCase().trim();
    if (!q) return [];

    const matches: { id: string; label: string; sublabel: string; type: 'route' | 'host' | 'action' }[] = [];

    // Search Routes (simplified for migration)
    const routes = [
      { id: 'dashboard', label: 'Dashboard', sublabel: 'Main Overview' },
      { id: 'siem', label: 'SIEM', sublabel: 'Security Information & Events' },
      { id: 'terminal', label: 'Terminal', sublabel: 'Active Shell Sessions' },
      { id: 'hosts', label: 'Hosts', sublabel: 'Infrastructure Management' },
      { id: 'vault', label: 'Vault', sublabel: 'Credential Manager' }
    ];

    for (const r of routes) {
      if (r.label.toLowerCase().includes(q)) {
        matches.push({ ...r, type: 'route' });
      }
    }

    // Search Hosts
    for (const h of appStore.hosts) {
      if (h.label.toLowerCase().includes(q) || h.hostname.toLowerCase().includes(q)) {
        matches.push({ id: h.id, label: h.label, sublabel: h.hostname, type: 'host' });
      }
    }

    return matches.slice(0, 10);
  });

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      onClose();
    } else if (e.key === 'ArrowDown') {
      e.preventDefault();
      selectedIndex = (selectedIndex + 1) % results.length;
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      selectedIndex = (selectedIndex - 1 + results.length) % results.length;
    } else if (e.key === 'Enter') {
      e.preventDefault();
      if (results[selectedIndex]) {
        execute(results[selectedIndex]);
      }
    }
  }

  function execute(item: any) {
    if (item.type === 'route') {
      appStore.setActiveNavTab(item.id);
      window.location.hash = `#/${item.id}`;
    } else if (item.type === 'host') {
      appStore.connectToHost(item.id);
    }
    onClose();
    query = '';
  }

  $effect(() => {
    if (open) {
      query = '';
      selectedIndex = 0;
      setTimeout(() => inputRef?.focus(), 10);
    }
  });
</script>

{#if open}
  <div
    class="fixed inset-0 z-[10000] flex items-start justify-center pt-[15vh] px-4"
    transition:fade={{ duration: 150 }}
    role="button"
    tabindex="-1"
    onclick={onClose}
    onkeydown={(e) => e.key === 'Escape' && onClose()}
  >
    <div class="fixed inset-0 bg-black/60 backdrop-blur-sm"></div>

    <!-- Palette -->
    <div
      class="relative w-full max-w-2xl bg-surface-2 border border-border-secondary rounded-xl shadow-2xl overflow-hidden"
      transition:fly={{ y: -20, duration: 200 }}
      role="dialog"
      aria-modal="true"
      tabindex="-1"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => e.stopPropagation()}
    >
      <!-- Input Area -->
      <div class="flex items-center gap-3 px-4 py-3 border-b border-border-primary bg-surface-1" role="combobox" aria-controls="palette-results" aria-haspopup="listbox" aria-expanded={results.length > 0}>
        <span class="text-accent text-lg font-bold" aria-hidden="true">⌕</span>
        <input
          bind:this={inputRef}
          type="text"
          bind:value={query}
          onkeydown={handleKeydown}
          placeholder="Search commands, hosts, or navigate..."
          class="flex-1 bg-transparent border-none outline-none text-text-primary text-sm font-[var(--font-ui)] placeholder:text-text-muted"
          role="searchbox"
          aria-autocomplete="list"
          aria-controls="palette-results"
          aria-activedescendant={results.length > 0 ? `palette-item-${selectedIndex}` : undefined}
        />
        <div class="flex items-center gap-1" aria-hidden="true">
          <span class="text-[9px] font-mono text-text-muted bg-surface-3 px-1.5 py-0.5 rounded border border-border-primary">ESC</span>
        </div>
      </div>

      <!-- Results Area -->
      <div class="max-h-[400px] overflow-auto py-2" id="palette-results" role="listbox">
        {#if results.length > 0}
          {#each results as item, i}
            <button
              id={`palette-item-${i}`}
              role="option"
              aria-selected={i === selectedIndex}
              class="w-full flex items-center justify-between px-4 py-2.5 text-left transition-colors duration-fast outline-hidden
                {i === selectedIndex ? 'bg-accent/10 border-l-2 border-accent' : 'hover:bg-surface-3 border-l-2 border-transparent'}"
              onclick={() => execute(item)}
              onmouseenter={() => selectedIndex = i}
            >
              <div class="flex flex-col">
                <span class="text-xs font-bold {i === selectedIndex ? 'text-accent' : 'text-text-heading'}">
                  {item.label}
                </span>
                <span class="text-[10px] text-text-muted font-mono">{item.sublabel}</span>
              </div>
              <div class="flex items-center gap-2">
                <span class="text-[9px] font-mono font-bold uppercase tracking-wider text-text-muted opacity-50 px-1.5 py-0.5 border border-border-primary rounded bg-surface-2" aria-label="Type: {item.type}">
                  {item.type}
                </span>
              </div>
            </button>
          {/each}
        {:else if query}
          <div class="px-6 py-8 text-center">
            <div class="text-text-muted text-xs">No matches found for "{query}"</div>
          </div>
        {:else}
          <div class="px-6 py-6 text-center">
            <div class="text-[10px] font-bold uppercase tracking-widest text-text-muted opacity-40 mb-2">QUICK NAVIGATION</div>
            <div class="grid grid-cols-2 gap-2 text-left">
              <div class="text-[10px] text-text-muted flex items-center gap-2"><span class="text-accent">→</span> Dashboard</div>
              <div class="text-[10px] text-text-muted flex items-center gap-2"><span class="text-accent">→</span> Active Shells</div>
              <div class="text-[10px] text-text-muted flex items-center gap-2"><span class="text-accent">→</span> SIEM Feed</div>
              <div class="text-[10px] text-text-muted flex items-center gap-2"><span class="text-accent">→</span> Global Search</div>
            </div>
          </div>
        {/if}
      </div>

      <!-- Footer -->
      <div class="px-4 py-2 border-t border-border-primary bg-surface-1 flex items-center justify-between text-[9px] font-mono text-text-muted opacity-50">
        <div class="flex items-center gap-3">
          <span><span class="text-text-secondary">↑↓</span> to navigate</span>
          <span><span class="text-text-secondary">↵</span> to select</span>
        </div>
        <div>v0.1</div>
      </div>
    </div>
  </div>
{/if}

// frontend-web/src/components/CommandPalette.tsx
import { createSignal, createMemo, For, Show, createEffect } from 'solid-js';

export interface PaletteAction {
  id: string;
  label: string;
  description?: string;
  icon: string;
  shortcut?: string;
  action: () => void;
}

interface CommandPaletteProps {
  open: boolean;
  onClose: () => void;
  actions: PaletteAction[];
}

export default function CommandPalette(props: CommandPaletteProps) {
  const [query, setQuery] = createSignal('');
  const [selectedIndex, setSelectedIndex] = createSignal(0);
  const [announcement, setAnnouncement] = createSignal('');
  let inputRef: HTMLInputElement | undefined;

  const filtered = createMemo(() => {
    const q = query().toLowerCase().trim();
    if (!q) return props.actions.slice(0, 10);
    return props.actions
      .filter(a => a.label.toLowerCase().includes(q) || a.description?.toLowerCase().includes(q))
      .slice(0, 10);
  });

  createEffect(() => {
    // Reset selection when results change
    filtered();
    setSelectedIndex(0);
    
    // Accessibility: Announce result count to screen readers
    const visibleCount = filtered().length;
    if (props.open) {
      setAnnouncement(`${visibleCount} result${visibleCount === 1 ? '' : 's'} available.`);
    }
  });

  createEffect(() => {
    if (props.open) {
      setTimeout(() => inputRef?.focus(), 50);
    }
  });

  const handleKeyDown = (e: KeyboardEvent) => {
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        setSelectedIndex((i) => Math.min(i + 1, filtered().length - 1));
        const nextItem = filtered()[selectedIndex()];
        if (nextItem) setAnnouncement(`Selected ${nextItem.label}`);
        break;
      case 'ArrowUp':
        e.preventDefault();
        setSelectedIndex((i) => Math.max(i - 1, 0));
        const prevItem = filtered()[selectedIndex()];
        if (prevItem) setAnnouncement(`Selected ${prevItem.label}`);
        break;
      case 'Enter':
        e.preventDefault();
        const selected = filtered()[selectedIndex()];
        if (selected) {
          selected.action();
          props.onClose();
        }
        break;
      case 'Escape':
        e.preventDefault();
        props.onClose();
        break;
    }
  };

  return (
    <Show when={props.open}>
      <div 
        class="fixed inset-0 bg-black/80 z-[100] flex items-start justify-center pt-[15vh] p-4 animate-in fade-in duration-200"
        onClick={props.onClose}
      >
        <div 
          class="w-full max-w-2xl bg-zinc-900 border border-zinc-700 shadow-2xl font-mono"
          onClick={(e) => e.stopPropagation()}
          role="dialog"
          aria-modal="true"
          aria-label="Command Palette"
        >
          {/* ARIA Live Region for dynamic announcements */}
          <div class="sr-only" role="status" aria-live="polite">
            {announcement()}
          </div>

          <div class="p-4 border-b border-zinc-800 flex items-center gap-4">
            <span class="text-zinc-500 text-lg">🔍</span>
            <input
              ref={inputRef}
              type="text"
              class="w-full bg-transparent border-none focus:outline-none text-white text-lg"
              placeholder="Search commands or sessions..."
              value={query()}
              onInput={(e) => setQuery(e.currentTarget.value)}
              onKeyDown={handleKeyDown}
              role="combobox"
              aria-autocomplete="list"
              aria-expanded="true"
              aria-haspopup="listbox"
              aria-controls="palette-results"
              aria-activedescendant={`palette-item-${selectedIndex()}`}
            />
            <kbd class="text-[10px] bg-zinc-800 px-1.5 py-0.5 border border-zinc-700 text-zinc-500 rounded">ESC</kbd>
          </div>

          <div 
            id="palette-results"
            class="max-h-[60vh] overflow-y-auto p-2"
            role="listbox"
          >
            <For each={filtered()}>
              {(item, index) => (
                <div
                  id={`palette-item-${index()}`}
                  role="option"
                  aria-selected={selectedIndex() === index()}
                  class={`p-3 flex items-center justify-between cursor-pointer transition-colors ${
                    selectedIndex() === index() ? 'bg-red-600 text-white' : 'hover:bg-zinc-800 text-zinc-400'
                  }`}
                  onClick={() => {
                    item.action();
                    props.onClose();
                  }}
                >
                  <div class="flex items-center gap-3">
                    <span class="text-lg opacity-80">{item.icon}</span>
                    <div class="flex flex-col">
                      <span class={`font-bold uppercase tracking-tight ${selectedIndex() === index() ? 'text-white' : 'text-zinc-200'}`}>
                        {item.label}
                      </span>
                      {item.description && (
                        <span class="text-[10px] uppercase opacity-60 tracking-widest">{item.description}</span>
                      )}
                    </div>
                  </div>
                  {item.shortcut && (
                    <kbd class={`text-[10px] px-1 py-0.5 rounded border ${
                      selectedIndex() === index() ? 'border-red-400 bg-red-700' : 'border-zinc-700 bg-zinc-800'
                    }`}>
                      {item.shortcut}
                    </kbd>
                  )}
                </div>
              )}
            </For>
            <Show when={filtered().length === 0}>
              <div class="p-8 text-center text-zinc-600 uppercase text-xs tracking-widest">
                No telemetry matches found.
              </div>
            </Show>
          </div>

          <div class="p-3 border-t border-zinc-800 bg-black/20 flex justify-between items-center text-[9px] uppercase tracking-widest text-zinc-600">
             <div class="flex gap-4">
               <span><kbd class="bg-zinc-800 p-0.5 border border-zinc-700 text-zinc-400">↑↓</kbd> Navigate</span>
               <span><kbd class="bg-zinc-800 p-0.5 border border-zinc-700 text-zinc-400">↵</kbd> Execute</span>
             </div>
             <div>OBLIVRA-OS // COMMANDS_READY</div>
          </div>
        </div>
      </div>
    </Show>
  );
}
