// frontend-web/src/core/Dashboard.svelte
<!-- OBLIVRA Web — Dashboard (Svelte 5) -->
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { logout } from '../services/auth';
  import { APP_CONTEXT } from '../context';
  import type { Severity } from '../components/SeverityIcon.svelte';
  import SeverityIcon from '../components/SeverityIcon.svelte';
  import CommandPalette, { type PaletteAction } from '../components/CommandPalette.svelte';
  import WarRoomGrid from '../components/WarRoomGrid.svelte';
  import FleetOverview from '../components/FleetOverview.svelte';
  import AccessibleTerminal from '../components/AccessibleTerminal.svelte';
  import { push } from './router.svelte';

  const nav = (path: string) => () => push(path);

  let status = $state<'INITIALIZING'|'READY'>('INITIALIZING');
  let heatmapData = $state<Severity[]>([]);
  let isPaletteOpen = $state(false);
  let isWarRoomMode = $state(false);

  const paletteActions: PaletteAction[] = [
    { id:'war-room',    label:'Toggle War Room Mode',      description:'High-density tactical view',           icon:'⚔️',  shortcut:'W',     action:() => { isWarRoomMode = !isWarRoomMode; } },
    { id:'onboard',     label:'Fleet Onboarding',          description:'Deploy new agents',                    icon:'🖥️',  shortcut:'G O',   action:nav('/onboarding') },
    { id:'fleet',       label:'Fleet Management',          description:'Agent status and bulk config',         icon:'🛰️',  action:nav('/fleet') },
    { id:'siem',        label:'SIEM Search',               description:'Search the event substrate',          icon:'🛡️',  shortcut:'G S',   action:nav('/siem/search') },
    { id:'alerts',      label:'Alert Management',          description:'Triage and manage alerts',             icon:'🚨',  action:nav('/alerts') },
    { id:'escalation',  label:'Escalation Center',         description:'Escalation policies and on-call',     icon:'⚡',  action:nav('/escalation') },
    { id:'playbooks',   label:'Playbook Builder',          description:'Build and execute SOAR playbooks',    icon:'🔧',  action:nav('/playbooks') },
    { id:'identity',    label:'Identity Administration',   description:'Users, roles, and federated SSO',     icon:'👥',  action:nav('/identity') },
    { id:'threatintel', label:'Threat Intelligence',       description:'IOC browser and campaign correlation', icon:'🔴',  action:nav('/threatintel') },
    { id:'enrich',      label:'Enrichment Viewer',         description:'GeoIP, DNS, asset mapping',            icon:'🔬',  action:nav('/enrich') },
    { id:'ueba',        label:'UEBA Dashboard',            description:'Entity behavior and risk scoring',    icon:'🧠',  action:nav('/ueba') },
    { id:'ndr',         label:'NDR Dashboard',             description:'Network flows and lateral movement',  icon:'🌐',  action:nav('/ndr') },
    { id:'ransomware',  label:'Ransomware Defense',        description:'Fleet-wide ransomware protection',    icon:'🦠',  action:nav('/ransomware') },
    { id:'mitre',       label:'MITRE ATT&CK Heatmap',     description:'Technique coverage visualization',    icon:'📊',  action:nav('/mitre-heatmap') },
    { id:'evidence',    label:'Evidence Vault',            description:'Legal-grade chain of custody',        icon:'🔍',  action:nav('/evidence') },
    { id:'regulator',   label:'Regulator Portal',          description:'Audit export and compliance packages',icon:'📄',  action:nav('/regulator') },
    { id:'lookups',     label:'Lookup Tables',             description:'CIDR/Exact/Regex enrichment tables',  icon:'🗒️',  action:nav('/lookups') },
    { id:'pb-metrics',  label:'Playbook Metrics',          description:'MTTR, success rates, bottlenecks',   icon:'📊',  action:nav('/playbook-metrics') },
    { id:'peer',        label:'Peer Analytics',            description:'Behavioral peer group outliers',      icon:'🧠',  action:nav('/peer-analytics') },
    { id:'fusion',      label:'Fusion Engine',             description:'Kill chain and campaign clustering',  icon:'🔗',  action:nav('/fusion') },
    { id:'logout',      label:'Terminate Session',         description:'Securely exit OBLIVRA',               icon:'🔌',  shortcut:'ALT+X', action:async () => { await logout(); push('/login'); } },
  ];

  function handleGlobalKey(e: KeyboardEvent) {
    if ((e.metaKey || e.ctrlKey) && (e.key === 'k' || e.key === 'p')) {
      e.preventDefault();
      isPaletteOpen = true;
    }
  }

  const severities: Severity[] = ['info','low','medium','high','critical'];

  onMount(() => {
    window.addEventListener('keydown', handleGlobalKey);
    setTimeout(() => { status = 'READY'; }, 800);
    heatmapData = Array.from({ length: 48 }, () => severities[Math.floor(Math.random() * severities.length)]);
  });

  onDestroy(() => window.removeEventListener('keydown', handleGlobalKey));
</script>

<main class="db-main" style:--war-header={isWarRoomMode ? 'rgba(127,29,29,0.2)' : 'transparent'}>
  <a href="#main-content" class="skip-link">Skip to main content</a>
  <div class="sr-only" role="status" aria-live="polite">
    {status === 'READY' ? 'Sovereign Substrate is READY.' : 'Initializing OBLIVRA Enterprise…'}
  </div>

  <!-- Header -->
  <header class="db-header" class:db-header--war={isWarRoomMode}>
    <div class="db-header-left">
      <div class="db-logo" class:db-logo--war={isWarRoomMode}>{isWarRoomMode ? '!' : 'O'}</div>
      <div>
        <h1 class="db-brand">OBLIVRA <span class:text-red-400={isWarRoomMode} class:text-accent={!isWarRoomMode}>{isWarRoomMode ? 'WAR ROOM' : 'ENTERPRISE'}</span></h1>
        <p class="db-context">{isWarRoomMode ? 'HIGH_DENSITY_TELEMETRY' : 'Sovereign SOC Platform'} // Context: {APP_CONTEXT}</p>
      </div>
    </div>
    <div class="db-header-right">
      <button class="db-war-btn" class:db-war-btn--active={isWarRoomMode} onclick={() => isWarRoomMode = !isWarRoomMode}>
        {isWarRoomMode ? 'Disable War Mode' : 'Enter War Room'}
      </button>
      <div class="db-status-block">
        <span class="db-status-label">System Status</span>
        <div class="db-status-row">
          <span class="db-dot" class:db-dot--ready={status==='READY'} class:db-dot--war={isWarRoomMode && status==='READY'}></span>
          <span class="db-status-val">{status}</span>
        </div>
      </div>
      <button class="db-logout" onclick={async () => { await logout(); push('/login'); }}>Terminate Session</button>
    </div>
  </header>

  <!-- Main -->
  <div id="main-content" class="db-content" tabindex="-1">
    {#if !isWarRoomMode}
      <section class="db-hero">
        <div class="db-phase-badge">Deployment Phase 0.5.0 // Svelte Migration Complete</div>
        <h2 class="db-headline">Multi-Tenant <br /><span class="db-headline-accent">Orchestration.</span></h2>
        <p class="db-subtext">Managing secure telemetry across distributed infrastructure. The OBLIVRA <strong>War Room</strong> mode provides zero-latency visibility into multi-tenant threat patterns and fleet health.</p>
      </section>

      <div class="db-stats-grid">
        {#each [
          { label:'Active Nodes',  value:'001', sub:'Primary Headless Server' },
          { label:'Event Velocity',value:'12.4',sub:'EPS (Ingest Active)' },
          { label:'Active Alerts', value:'003', sub:'Requires Intervention', severity:'high' as Severity },
          { label:'Threat Index',  value:'ELEVATED', sub:'Pattern Delta Detected', severity:'medium' as Severity },
        ] as stat}
          <div class="db-stat">
            <div class="db-stat-top">
              <span class="db-stat-label">{stat.label}</span>
              {#if stat.severity}<SeverityIcon severity={stat.severity} size={14} />{/if}
            </div>
            <div class="db-stat-value">{stat.value}</div>
            <p class="db-stat-sub">{stat.sub}</p>
          </div>
        {/each}
      </div>

      <FleetOverview />

      <section class="db-heatmap-section">
        <div class="db-heatmap-header">
          <h3 class="db-section-label">Inbound Event Density (Pattern-Fills)</h3>
          <div class="db-legend">
            {#each [['low','Low'],['medium','Med'],['high','High'],['critical','Crit']] as [s,l]}
              <div class="db-legend-item">
                <div class="db-legend-swatch" style="background:var(--alert-{s}); background-image:var(--pattern-{s});"></div>
                <span>{l}</span>
              </div>
            {/each}
          </div>
        </div>
        <div class="db-heatmap-grid">
          {#each heatmapData as s, i}
            <div
              class="db-heatmap-cell"
              style="background-color:var(--alert-{s}); background-image:var(--pattern-{s});"
              title="Severity: {s.toUpperCase()}"
              role="img"
              aria-label="{s} severity event block"
            ></div>
          {/each}
        </div>
      </section>

      <div class="db-actions-grid">
        {#each [
          { title:'Fleet Onboarding',    desc:'Deploy sovereign agents to your infrastructure.', shortcut:'F1', onClick:() => push('/onboarding') },
          { title:'Vault Orchestration', desc:'Access shared enterprise secrets and manage multi-tenant compliance.', shortcut:'F2', onClick:() => {} },
        ] as card}
          <div class="db-action-card" onclick={card.onClick} role="button" tabindex="0" onkeydown={(e) => e.key==='Enter' && card.onClick()}>
            <span class="db-action-shortcut">CMD + {card.shortcut}</span>
            <h3 class="db-action-title">{card.title}</h3>
            <p class="db-action-desc">{card.desc}</p>
            <div class="db-action-cta">Launch Operation →</div>
          </div>
        {/each}
      </div>
    {:else}
      <div class="db-warroom">
        <div class="db-warroom-left"><WarRoomGrid /></div>
        <div class="db-warroom-right">
          <section>
            <h3 class="db-warroom-section-title" style="color:#f87171">Node Criticality</h3>
            <div class="db-criticality-card">
              <div class="db-crit-row">
                <span class="db-crit-host">LNUX-PROD-01</span>
                <span class="db-crit-status">CRITICAL</span>
              </div>
              <div class="db-crit-bar-bg"><div class="db-crit-bar"></div></div>
            </div>
          </section>
          <section>
            <h3 class="db-warroom-section-title">Global Ingest Load</h3>
            <div class="db-ingest-chart"></div>
          </section>
          <AccessibleTerminal />
        </div>
      </div>
    {/if}
  </div>

  <footer class="db-footer" aria-hidden="true">
    <div class="db-marquee">SECURE_SUBSTRATE // RAFT_CONSENSUS_STABLE // SIEM_PIPELINE_ACTIVE // NO_THREATS_DETECTED // OBLIVRA_ENTERPRISE_READY</div>
  </footer>

  <CommandPalette open={isPaletteOpen} onClose={() => isPaletteOpen = false} actions={paletteActions} />
</main>

<style>
  .db-main { min-height: 100vh; background: var(--surface-0); color: var(--text-primary); font-family: var(--font-mono); display: flex; flex-direction: column; }
  .skip-link { position: absolute; left: -9999px; }
  .skip-link:focus { position: fixed; top: 0; left: 0; z-index: 100; background: var(--accent-primary); color: #000; padding: 12px 16px; font-weight: 700; }
  .sr-only { position: absolute; width:1px; height:1px; overflow:hidden; clip:rect(0,0,0,0); }

  /* Header */
  .db-header { display:flex; justify-content:space-between; align-items:center; padding:16px 24px; border-bottom:1px solid var(--border-primary); background:var(--surface-1); position:sticky; top:0; z-index:50; transition:background 300ms ease; }
  .db-header--war { background:rgba(127,29,29,0.15); border-bottom-color:rgba(220,38,38,0.3); }
  .db-header-left { display:flex; align-items:center; gap:14px; }
  .db-logo { width:32px; height:32px; background:var(--accent-primary); display:grid; place-items:center; font-weight:900; color:#000; font-size:15px; transition:background 300ms; }
  .db-logo--war { background:#dc2626; box-shadow:0 0 15px rgba(224,64,64,0.4); }
  .db-brand { font-size:18px; font-weight:900; text-transform:uppercase; letter-spacing:-.03em; color:var(--text-heading); margin:0; }
  .text-accent { color:var(--accent-primary); }
  .text-red-400 { color:#f87171; }
  .db-context { font-size:10px; text-transform:uppercase; letter-spacing:.2em; color:var(--text-muted); margin:2px 0 0; opacity:0.7; }
  .db-header-right { display:flex; align-items:center; gap:20px; }
  .db-war-btn { font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:.1em; padding:4px 12px; border:1px solid #3a3d44; color:#9b9ea4; background:transparent; cursor:pointer; transition:all 100ms; font-family:var(--font-mono); }
  .db-war-btn--active { border-color:#dc2626; color:#f87171; background:rgba(127,29,29,0.15); }
  .db-status-block { display:flex; flex-direction:column; align-items:flex-end; }
  .db-status-label { font-size:10px; text-transform:uppercase; letter-spacing:.15em; color:var(--text-muted); }
  .db-status-row { display:flex; align-items:center; gap:7px; }
  .db-dot { width:8px; height:8px; border-radius:50%; background:var(--status-offline); animation:pulse 2s infinite; }
  .db-dot--ready { background:var(--status-online); box-shadow:0 0 8px var(--status-online); }
  .db-dot--war   { background:#f87171; box-shadow:0 0 8px #f87171; }
  .db-status-val { font-size:12px; font-weight:700; }
  .db-logout { height:40px; padding:0 20px; border:1px solid var(--border-primary); color:var(--text-muted); font-weight:700; text-transform:uppercase; letter-spacing:.06em; background:transparent; cursor:pointer; font-family:var(--font-mono); transition:all 150ms; font-size:11px; }
  .db-logout:hover { background:#dc2626; color:#fff; border-color:#dc2626; }

  /* Content */
  .db-content { flex:1; padding:32px; max-width:1280px; margin:0 auto; width:100%; display:flex; flex-direction:column; gap:40px; }

  /* Hero */
  .db-hero { display:flex; flex-direction:column; gap:16px; }
  .db-phase-badge { display:inline-block; padding:4px 12px; background:var(--accent-secondary,#0077b3); font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:.2em; color:#fff; }
  .db-headline { font-size:clamp(40px,6vw,72px); font-weight:900; font-style:italic; letter-spacing:-.04em; text-transform:uppercase; color:var(--text-heading); margin:0; line-height:0.92; }
  .db-headline-accent { color:var(--accent-primary); }
  .db-subtext { font-size:16px; color:var(--text-muted); max-width:560px; line-height:1.65; font-family:var(--font-ui); }

  /* Stats */
  .db-stats-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:1px; border:1px solid rgba(255,255,255,0.04); background:rgba(255,255,255,0.04); }
  .db-stat { background:var(--surface-0); padding:24px; display:flex; flex-direction:column; gap:4px; position:relative; overflow:hidden; }
  .db-stat-top { display:flex; justify-content:space-between; align-items:flex-start; }
  .db-stat-label { font-size:10px; text-transform:uppercase; letter-spacing:.15em; color:var(--text-muted); }
  .db-stat-value { font-size:36px; font-weight:900; font-style:italic; letter-spacing:-.04em; color:var(--text-heading); }
  .db-stat-sub { font-size:12px; color:var(--text-muted); opacity:0.6; letter-spacing:.04em; margin:0; }

  /* Heatmap */
  .db-heatmap-section { display:flex; flex-direction:column; gap:12px; }
  .db-heatmap-header { display:flex; justify-content:space-between; align-items:flex-end; }
  .db-section-label { font-size:10px; font-weight:900; text-transform:uppercase; letter-spacing:.2em; color:var(--text-muted); margin:0; }
  .db-legend { display:flex; gap:16px; }
  .db-legend-item { display:flex; align-items:center; gap:5px; font-size:10px; text-transform:uppercase; font-weight:700; color:var(--text-muted); }
  .db-legend-swatch { width:12px; height:12px; background-size:4px 4px; }
  .db-heatmap-grid { display:grid; grid-template-columns:repeat(24,1fr); gap:3px; }
  .db-heatmap-cell { aspect-ratio:1; cursor:help; border:1px solid rgba(0,0,0,0.2); background-size:4px 4px; transition:transform 100ms ease; }
  .db-heatmap-cell:hover { transform:scale(1.1); z-index:1; }

  /* Action cards */
  .db-actions-grid { display:grid; grid-template-columns:1fr 1fr; gap:24px; padding-bottom:40px; }
  .db-action-card { border:1px solid var(--border-primary); background:var(--surface-1); padding:32px; cursor:pointer; position:relative; overflow:hidden; transition:border-color 150ms; }
  .db-action-card:hover { border-color:var(--accent-primary); }
  .db-action-card:hover .db-action-cta { opacity:1; transform:translateX(0); }
  .db-action-shortcut { position:absolute; top:8px; right:8px; font-size:8px; font-weight:700; color:var(--text-muted); opacity:0.2; transition:opacity 150ms; }
  .db-action-card:hover .db-action-shortcut { opacity:1; }
  .db-action-title { font-size:28px; font-weight:900; text-transform:uppercase; font-style:italic; letter-spacing:-.04em; color:var(--text-heading); margin:0 0 12px; transition:color 150ms; }
  .db-action-card:hover .db-action-title { color:var(--accent-primary); }
  .db-action-desc  { color:var(--text-muted); font-size:14px; font-family:var(--font-ui); line-height:1.5; margin:0 0 16px; }
  .db-action-cta   { font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.15em; color:var(--accent-primary); opacity:0; transform:translateX(-10px); transition:all 200ms ease; }

  /* War room */
  .db-warroom { display:grid; grid-template-columns:1fr 380px; gap:24px; }
  .db-warroom-left {}
  .db-warroom-right { display:flex; flex-direction:column; gap:24px; }
  .db-warroom-section-title { font-size:10px; font-weight:900; text-transform:uppercase; letter-spacing:.2em; color:var(--text-muted); margin:0 0 10px; }
  .db-criticality-card { border:1px solid rgba(127,29,29,0.3); background:rgba(127,29,29,0.08); padding:14px; }
  .db-crit-row { display:flex; justify-content:space-between; margin-bottom:10px; }
  .db-crit-host   { font-size:10px; color:#9b9ea4; }
  .db-crit-status { font-size:10px; color:#f87171; font-weight:700; }
  .db-crit-bar-bg { width:100%; background:#1e2937; height:4px; }
  .db-crit-bar    { width:85%; height:100%; background:#dc2626; box-shadow:0 0 10px rgba(224,64,64,0.5); }
  .db-ingest-chart { height:100px; border:1px solid #1e2937; background:rgba(0,0,0,0.4); position:relative; overflow:hidden; }

  /* Footer marquee */
  .db-footer { border-top:1px solid var(--border-primary); overflow:hidden; padding:6px 0; background:var(--surface-0); }
  .db-marquee { white-space:nowrap; font-size:10px; text-transform:uppercase; letter-spacing:.3em; color:var(--text-muted); opacity:0.3; animation:marquee 30s linear infinite; display:inline-block; }
  @keyframes marquee { from { transform:translateX(100vw); } to { transform:translateX(-100%); } }
  @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.5} }
</style>

// frontend-web/src/core/Dashboard.tsx
import { createSignal, onMount, For, onCleanup, Show } from 'solid-js';
import { APP_CONTEXT } from './context';
import { logout } from '../services/auth';
import SeverityIcon, { type Severity } from '../components/SeverityIcon';
import CommandPalette, { type PaletteAction } from '../components/CommandPalette';
import WarRoomGrid from '../components/WarRoomGrid';
import FleetOverview from '../components/FleetOverview';
import AccessibleTerminal from '../components/AccessibleTerminal';

export default function Dashboard() {
  const handleLogout = async () => {
    await logout();
    window.location.href = '/login';
  };

  const [status, setStatus] = createSignal('INITIALIZING');
  const [heatmapData, setHeatmapData] = createSignal<Severity[]>([]);
  const [isPaletteOpen, setIsPaletteOpen] = createSignal(false);
  const [isWarRoomMode, setIsWarRoomMode] = createSignal(false);

  const nav = (path: string) => () => { window.location.href = path; };

  const paletteActions: PaletteAction[] = [
    { id: 'war-room',    label: 'Toggle War Room Mode',      description: 'High-density tactical view',             icon: '⚔️',  shortcut: 'W',     action: () => setIsWarRoomMode(!isWarRoomMode()) },
    { id: 'onboard',    label: 'Fleet Onboarding',           description: 'Deploy new agents',                      icon: '🖥️',  shortcut: 'G O',   action: nav('/onboarding') },
    { id: 'fleet',      label: 'Fleet Management',           description: 'Agent status and bulk config',            icon: '🛰️',  action: nav('/fleet') },
    { id: 'siem',       label: 'SIEM Search',                description: 'Search the event substrate',             icon: '🛡️',  shortcut: 'G S',   action: nav('/siem/search') },
    { id: 'alerts',     label: 'Alert Management',           description: 'Triage and manage alerts',                icon: '🚨',  action: nav('/alerts') },
    { id: 'escalation', label: 'Escalation Center',          description: 'Escalation policies and on-call',        icon: '⚡',  action: nav('/escalation') },
    { id: 'playbooks',  label: 'Playbook Builder',           description: 'Build and execute SOAR playbooks',       icon: '🔧',  action: nav('/playbooks') },
    { id: 'identity',   label: 'Identity Administration',    description: 'Users, roles, and federated SSO',        icon: '👥',  action: nav('/identity') },
    { id: 'threatintel',label: 'Threat Intelligence',        description: 'IOC browser and campaign correlation',   icon: '🔴',  action: nav('/threatintel') },
    { id: 'enrich',     label: 'Enrichment Viewer',          description: 'GeoIP, DNS, asset mapping',               icon: '🔬',  action: nav('/enrich') },
    { id: 'ueba',       label: 'UEBA Dashboard',             description: 'Entity behavior and risk scoring',       icon: '🧠',  action: nav('/ueba') },
    { id: 'ndr',        label: 'NDR Dashboard',              description: 'Network flows and lateral movement',     icon: '🌐',  action: nav('/ndr') },
    { id: 'ransomware', label: 'Ransomware Defense',         description: 'Fleet-wide ransomware protection',       icon: '🦠',  action: nav('/ransomware') },
    { id: 'mitre',      label: 'MITRE ATT&CK Heatmap',       description: 'Technique coverage visualization',       icon: '📊',  action: nav('/mitre-heatmap') },
    { id: 'evidence',   label: 'Evidence Vault',             description: 'Legal-grade chain of custody',           icon: '🔍',  action: nav('/evidence') },
    { id: 'regulator',  label: 'Regulator Portal',           description: 'Audit export and compliance packages',   icon: '📄',  action: nav('/regulator') },
    { id: 'lookups',       label: 'Lookup Tables',               description: 'CIDR/Exact/Regex enrichment tables',     icon: '🗒️',  action: nav('/lookups') },
    { id: 'pb-metrics',  label: 'Playbook Metrics',            description: 'MTTR, success rates, bottlenecks',       icon: '📊',  action: nav('/playbook-metrics') },
    { id: 'peer',        label: 'Peer Analytics',              description: 'Behavioral peer group outliers',          icon: '🧠',  action: nav('/peer-analytics') },
    { id: 'fusion',      label: 'Fusion Engine',               description: 'Kill chain and campaign clustering',      icon: '🔗',  action: nav('/fusion') },
    { id: 'logout',     label: 'Terminate Session',          description: 'Securely exit OBLIVRA',                  icon: '🔌',  shortcut: 'ALT+X', action: handleLogout },
  ];

  const handleGlobalKey = (e: KeyboardEvent) => {
    if ((e.metaKey || e.ctrlKey) && (e.key === 'k' || e.key === 'p')) {
      e.preventDefault();
      setIsPaletteOpen(true);
    }
  };

  onMount(() => {
    window.addEventListener('keydown', handleGlobalKey);
    setTimeout(() => setStatus('READY'), 1000);
    const severities: Severity[] = ['info', 'low', 'medium', 'high', 'critical'];
    setHeatmapData(Array.from({ length: 48 }, () => severities[Math.floor(Math.random() * severities.length)]));
  });

  onCleanup(() => {
    window.removeEventListener('keydown', handleGlobalKey);
  });

  return (
    <main class="min-h-screen bg-[var(--bg-deep)] text-[var(--text-primary)] font-mono selection:bg-[var(--accent-primary)] selection:text-[var(--bg-deep)]">
      <a href="#main-content" class="sr-only focus:not-sr-only focus:fixed focus:top-0 focus:left-0 focus:z-[100] focus:bg-[var(--accent-primary)] focus:text-[var(--bg-deep)] focus:p-4 focus:font-bold">
        Skip to main content
      </a>

      <div class="sr-only" role="status" aria-live="polite">
        {status() === 'READY' ? 'Sovereign Substrate is READY.' : 'Initializing OBLIVRA Enterprise...'}
      </div>

      <header class={`border-b border-[var(--border-bold)] bg-[var(--bg-muted)] p-4 flex justify-between items-center sticky top-0 z-50 transition-colors duration-500 ${isWarRoomMode() ? 'border-red-900/50 bg-red-950/20' : ''}`}>
        <div class="flex items-center gap-4">
          <div class={`w-8 h-8 ${isWarRoomMode() ? 'bg-red-600 shadow-[0_0_15px_rgba(224,64,64,0.4)]' : 'bg-[var(--accent-primary)]'} grid place-items-center font-bold text-[var(--bg-deep)] transition-all`}>
            {isWarRoomMode() ? '!' : 'O'}
          </div>
          <div>
            <h1 class="text-lg font-black tracking-tighter uppercase leading-none text-[var(--text-heading)]">
              OBLIVRA <span class={isWarRoomMode() ? 'text-red-500' : 'text-[var(--accent-primary)]'}>{isWarRoomMode() ? 'WAR ROOM' : 'ENTERPRISE'}</span>
            </h1>
            <p class="text-[10px] text-[var(--text-muted)] tracking-widest uppercase opacity-70">
              {isWarRoomMode() ? 'HIGH_DENSITY_TELEMETRY' : 'Sovereign SOC Platform'} // Context: {APP_CONTEXT}
            </p>
          </div>
        </div>

        <div class="flex items-center gap-6">
          <button onClick={() => setIsWarRoomMode(!isWarRoomMode())} class={`text-[10px] font-bold uppercase tracking-widest px-3 py-1 border transition-all ${isWarRoomMode() ? 'border-red-600 text-red-500 bg-red-900/20' : 'border-zinc-700 text-zinc-500'}`}>
            {isWarRoomMode() ? 'Disable War Mode' : 'Enter War Room'}
          </button>
          <div class="flex flex-col items-end">
            <span class="text-[10px] uppercase tracking-widest text-[var(--text-muted)]">System Status</span>
            <div class="flex items-center gap-2">
              <span class={`w-2 h-2 rounded-full ${status() === 'READY' ? (isWarRoomMode() ? 'bg-red-500 shadow-[0_0_8px_#ff5252]' : 'bg-[var(--status-online)] shadow-[0_0_8px_var(--status-online)]') : 'bg-[var(--status-offline)] animate-pulse'}`}></span>
              <span class="text-xs font-bold tracking-tight">{status()}</span>
            </div>
          </div>
          <button onClick={handleLogout} class="h-10 px-6 border border-[var(--border-bold)] text-[var(--text-muted)] font-bold uppercase tracking-tighter hover:bg-red-600 hover:text-white hover:border-red-600 transition-all">
            Terminate Session
          </button>
        </div>
      </header>

      <div id="main-content" class="p-8 max-w-7xl mx-auto space-y-12" tabindex="-1">
        <Show when={!isWarRoomMode()}>
          <section class="space-y-6">
            <div class="inline-block px-3 py-1 bg-[var(--accent-secondary)] text-[10px] font-bold uppercase tracking-[0.2em]">
              Deployment Phase 0.4.1 // Enterprise Scaling
            </div>
            <h2 class="text-6xl font-black italic tracking-tighter leading-[0.9] uppercase text-[var(--text-heading)]">
              Multi-Tenant <br />
              <span class="text-[var(--accent-primary)]">Orchestration.</span>
            </h2>
            <p class="text-xl text-[var(--text-muted)] max-w-2xl leading-relaxed">
              Managing secure telemetry across distributed infrastructure. The OBLIVRA <strong>War Room</strong> mode provides zero-latency visibility into multi-tenant threat patterns and fleet health.
            </p>
          </section>

          <div class="grid grid-cols-1 md:grid-cols-4 gap-1 border border-[var(--border-subtle)] bg-[var(--border-subtle)]">
            <StatBox label="Active Nodes" value="001" sub="Primary Headless Server" />
            <StatBox label="Event Velocity" value="12.4" sub="EPS (Ingest Active)" />
            <StatBox label="Active Alerts" value="003" sub="Requires Intervention" severity="high" />
            <StatBox label="Threat Index" value="ELEVATED" sub="Pattern Delta Detected" color="var(--alert-high)" severity="medium" />
          </div>

          <FleetOverview />

          <section class="space-y-4">
            <div class="flex justify-between items-end">
              <h3 class="text-xs font-black uppercase tracking-[0.2em] text-[var(--text-muted)]">Inbound Event Density (Pattern-Fills)</h3>
              <div class="flex gap-4 text-[10px] uppercase font-bold text-[var(--text-muted)]">
                <div class="flex items-center gap-1"><div class="w-3 h-3 bg-[var(--alert-low)]" style={{ "background-image": "var(--pattern-low)" }}></div> Low</div>
                <div class="flex items-center gap-1"><div class="w-3 h-3 bg-[var(--alert-medium)]" style={{ "background-image": "var(--pattern-medium)" }}></div> Med</div>
                <div class="flex items-center gap-1"><div class="w-3 h-3 bg-[var(--alert-high)]" style={{ "background-image": "var(--pattern-high)" }}></div> High</div>
                <div class="flex items-center gap-1"><div class="w-3 h-3 bg-[var(--alert-critical)]" style={{ "background-image": "var(--pattern-critical)" }}></div> Crit</div>
              </div>
            </div>
            <div class="grid grid-cols-12 md:grid-cols-24 gap-1 bg-[var(--border-subtle)] border border-[var(--border-subtle)]">
              <For each={heatmapData()}>
                {(s) => (
                  <div class="aspect-square transition-all hover:scale-110 hover:z-10 cursor-help border border-black/20" style={{ "background-color": `var(--alert-${s})`, "background-image": `var(--pattern-${s})`, "background-size": "4px 4px" }} title={`Severity: ${s.toUpperCase()}`} role="img" aria-label={`${s} severity event block`}></div>
                )}
              </For>
            </div>
          </section>
        </Show>

        <Show when={isWarRoomMode()}>
          <div class="animate-in fade-in slide-in-from-bottom-4 duration-500 space-y-12">
            <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">
              <div class="lg:col-span-8">
                <WarRoomGrid />
              </div>
              <div class="lg:col-span-4 space-y-8">
                <section class="space-y-4">
                  <h3 class="text-xs font-black uppercase tracking-[0.2em] text-red-500">Node Criticality</h3>
                  <div class="border border-red-900/30 bg-red-950/10 p-4 space-y-4">
                    <div class="flex justify-between items-center">
                      <span class="text-[10px] text-zinc-400">LNUX-PROD-01</span>
                      <span class="text-[10px] text-red-500 font-bold">CRITICAL</span>
                    </div>
                    <div class="w-full bg-zinc-800 h-1">
                      <div class="bg-red-600 h-full w-[85%] shadow-[0_0_10px_rgba(224,64,64,0.5)]"></div>
                    </div>
                  </div>
                </section>
                <section class="space-y-4">
                  <h3 class="text-xs font-black uppercase tracking-[0.2em] text-zinc-500">Global Ingest Load</h3>
                  <div class="h-32 border border-zinc-800 bg-black/40 relative overflow-hidden">
                    <div class="absolute inset-0 opacity-10" style={{ "background-image": "var(--pattern-medium)", "background-size": "8px 8px" }}></div>
                    <div class="absolute bottom-0 left-0 right-0 h-1/2 bg-gradient-to-t from-red-600/20 to-transparent"></div>
                  </div>
                </section>
                <AccessibleTerminal />
              </div>
            </div>
          </div>
        </Show>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-8 pb-12">
          <ActionCard title="Fleet Onboarding" desc="Deploy sovereign agents to your infrastructure and establish real-time telemetry." shortcut="F1" onClick={() => window.location.href = '/onboarding'} />
          <ActionCard title="Vault Orchestration" desc="Access shared enterprise secrets and manage multi-tenant compliance policies." shortcut="F2" />
        </div>
      </div>

      <footer class="fixed bottom-0 w-full border-t border-[var(--border-bold)] bg-[var(--bg-deep)] p-2 pointer-events-none overflow-hidden">
        <div class="whitespace-nowrap animate-marquee inline-block text-[10px] tracking-[0.3em] uppercase text-[var(--text-muted)] opacity-30">SECURE_SUBSTRATE // RAFT_CONSENSUS_STABLE // SIEM_PIPELINE_ACTIVE // NO_THREATS_DETECTED // OBLIVRA_ENTERPRISE_READY</div>
      </footer>

      <CommandPalette open={isPaletteOpen()} onClose={() => setIsPaletteOpen(false)} actions={paletteActions} />
    </main>
  );
}

function StatBox(props: { label: string; value: string; sub: string; color?: string; severity?: Severity }) {
  return (
    <div class="bg-[var(--bg-deep)] p-6 space-y-1 relative overflow-hidden group">
      <div class="flex justify-between items-start">
        <span class="text-[10px] uppercase tracking-widest text-[var(--text-muted)]">{props.label}</span>
        {props.severity && <SeverityIcon severity={props.severity} size={14} class="opacity-80" />}
      </div>
      <div class="text-4xl font-black italic tracking-tighter" style={{ color: props.color || 'inherit' }}>{props.value}</div>
      <p class="text-xs text-[var(--text-muted)] opacity-60 tracking-tight">{props.sub}</p>
      {props.severity && <div class="absolute inset-0 opacity-[0.03] pointer-events-none" style={{ "background-image": `var(--pattern-${props.severity})`, "background-size": "4px 4px" }}></div>}
    </div>
  );
}

function ActionCard(props: { title: string; desc: string; shortcut: string; onClick?: () => void }) {
  return (
    <div onClick={props.onClick} class="border border-[var(--border-bold)] bg-[var(--bg-muted)] p-8 space-y-4 hover:border-[var(--accent-primary)] transition-colors group cursor-pointer relative overflow-hidden">
      <div class="absolute top-0 right-0 p-2 text-[8px] font-bold text-[var(--text-muted)] opacity-20 group-hover:opacity-100 transition-opacity">CMD + {props.shortcut}</div>
      <h3 class="text-3xl font-black uppercase tracking-tighter italic group-hover:text-[var(--accent-primary)] transition-colors">{props.title}</h3>
      <p class="text-[var(--text-muted)] leading-snug">{props.desc}</p>
      <div class="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[var(--accent-primary)] opacity-0 group-hover:opacity-100 transition-all translate-x-[-10px] group-hover:translate-x-0">Launch Operation <span>→</span></div>
    </div>
  );
}
